package calc

import (
	"github.com/blackchip-org/zc"
	"github.com/blackchip-org/zc/zlib"
)

var ops = []zc.OpDecl{
	zc.GenOp("abs",
		zc.Func(zlib.AbsBigInt, zc.BigInt),
		zc.Func(zlib.AbsDecimal, zc.Decimal),
		zc.Func(zlib.AbsFloat, zc.Float),
		zc.Func(zlib.AbsRational, zc.Rational),
		zc.Func(zlib.AbsComplex, zc.Complex),
	),
	zc.GenOp("add",
		zc.Func(zlib.AddBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.AddDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.AddFloat, zc.Float, zc.Float),
		zc.Func(zlib.AddRational, zc.Rational, zc.Rational),
		zc.Func(zlib.AddComplex, zc.Complex, zc.Complex),
	),
	zc.GenOp("and",
		zc.Func(zlib.AndBigInt, zc.BigInt),
	),
	zc.GenOp("ceil",
		zc.Func(zc.NoOp, zc.BigInt),
		zc.Func(zlib.CeilDecimal, zc.Decimal),
		zc.Func(zlib.CeilFloat, zc.Float),
	),
	zc.GenOp("div",
		zc.Func(zlib.DivDecimal, zc.Decimal),
		zc.Func(zlib.DivFloat, zc.Float, zc.Float),
		zc.Func(zlib.DivRational, zc.Rational, zc.Rational),
		zc.Func(zlib.DivComplex, zc.Complex, zc.Complex),
	),
	zc.GenOp("eq",
		zc.Func(zlib.EqBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.EqDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.EqFloat, zc.Float, zc.Float),
		zc.Func(zlib.EqRational, zc.Rational, zc.Rational),
		zc.Func(zlib.EqComplex, zc.Complex, zc.Complex),
	),
	zc.GenOp("floor",
		zc.Func(zc.NoOp, zc.BigInt),
		zc.Func(zlib.FloorDecimal, zc.Decimal),
		zc.Func(zlib.FloorFloat, zc.Float),
	),
	zc.GenOp("gt",
		zc.Func(zlib.GtBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.GtDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.GtRational, zc.Rational, zc.Rational),
		zc.Func(zlib.GtFloat, zc.Float, zc.Float),
	),
	zc.GenOp("gte",
		zc.Func(zlib.GteBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.GteDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.GteRational, zc.Rational, zc.Rational),
		zc.Func(zlib.GteFloat, zc.Float, zc.Float),
	),
	zc.Op("hex", zlib.HexBigInt, zc.BigInt),
	zc.GenOp("lt",
		zc.Func(zlib.LtBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.LtDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.LtRational, zc.Rational, zc.Rational),
		zc.Func(zlib.LtFloat, zc.Float, zc.Float),
	),
	zc.GenOp("lte",
		zc.Func(zlib.LteBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.LteDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.LteRational, zc.Rational, zc.Rational),
		zc.Func(zlib.LteFloat, zc.Float, zc.Float),
	),
	zc.GenOp("mod",
		zc.Func(zlib.ModBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.ModDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.ModFloat, zc.Float, zc.Float),
	),
	zc.GenOp("mul",
		zc.Func(zlib.MulBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.MulDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.MulFloat, zc.Float, zc.Float),
		zc.Func(zlib.MulRational, zc.Rational, zc.Rational),
		zc.Func(zlib.MulComplex, zc.Complex, zc.Complex),
	),
	zc.GenOp("neq",
		zc.Func(zlib.NeqBigInt, zc.BigInt),
		zc.Func(zlib.NeqDecimal, zc.Decimal),
		zc.Func(zlib.NeqFloat, zc.Float, zc.Float),
		zc.Func(zlib.NeqRational, zc.Rational, zc.Rational),
		zc.Func(zlib.NeqComplex, zc.Complex, zc.Complex),
	),
	zc.GenOp("sign",
		zc.Func(zlib.SignBigInt, zc.BigInt),
		zc.Func(zlib.SignDecimal, zc.Decimal),
		zc.Func(zlib.SignFloat, zc.Float),
		zc.Func(zlib.SignRational, zc.Rational),
	),
	zc.GenOp("sub",
		zc.Func(zlib.SubBigInt, zc.BigInt, zc.BigInt),
		zc.Func(zlib.SubDecimal, zc.Decimal, zc.Decimal),
		zc.Func(zlib.SubFloat, zc.Float, zc.Float),
		zc.Func(zlib.SubRational, zc.Rational, zc.Rational),
		zc.Func(zlib.SubComplex, zc.Complex, zc.Complex),
	),
}

var opsTable map[string]zc.CalcFunc

func init() {
	opsTable = make(map[string]zc.CalcFunc)
	for _, v := range ops {
		k := v.Name
		if _, exists := opsTable[k]; exists {
			panic(zc.ErrDuplicateOp(k))
		}
		opsTable[k] = zc.EvalOp(v)
	}
}
