package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var About = zc.Vol{
	Name: "about",
	Ops: []zc.Op{
		ops.Version,
	},
	Macros: []zc.Macro{},
}
