package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Angle = zc.Vol{
	Name: "angle",
	Ops: []zc.Op{
		ops.Dec,
		ops.DegMin,
		ops.DegMinRound,
		ops.DegMinSec,
		ops.DegMinSecRound,
		ops.DmsGet,
		ops.Minutes,
		ops.Seconds,
	},
	Macros: []zc.Macro{
		{Name: "dd", Expr: "dec"},
		{Name: "deg-rad", Expr: "pi 180 div mul"},
		{Name: "dm", Expr: "deg.min"},
		{Name: "dmr", Expr: "deg.min.round"},
		{Name: "dms", Expr: "deg.min.sec"},
		{Name: "dmsr", Expr: "deg.min.sec.round"},
		{Name: "rad-deg", Expr: "180 pi div mul"},
		{Name: "secs", Expr: "seconds"},
	},
}
