package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicFloat = zc.Vol{
	Name: "basic/Float",
	Ops: []zc.Op{
		ops.AddF,
		ops.CbrtF,
		ops.DivF,
		ops.ExpF,
		ops.Log10F,
		ops.MulF,
		ops.NegF,
		ops.SignF,
		ops.SqrtF,
		ops.SubF,
	},
	Macros: []zc.Macro{},
}
