package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicDecSS = zc.Vol{
	Name: "basic/Dec/SS",
	Ops: []zc.Op{
		ops.AddDecimalSS,
		ops.DivDecimalSS,
		ops.ModDecimalSS,
		ops.MulDecimalSS,
		ops.NegDecimalSS,
		ops.PowDecimalSS,
		ops.RemDecimalSS,
		ops.SubDecimalSS,
	},
	Macros: []zc.Macro{},
}
