package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicRat = zc.Vol{
	Name: "basic/Rat",
	Ops: []zc.Op{
		ops.AddRat,
		ops.DivRat,
		ops.MulRat,
		ops.NegRat,
		ops.SubRat,
	},
	Macros: []zc.Macro{},
}
