package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Basic = zc.Vol{
	Name: "basic",
	Ops: []zc.Op{
		ops.Abs,
		ops.Add,
		ops.Cbrt,
		ops.Ceil,
		ops.Div,
		ops.DivMod,
		ops.DivRem,
		ops.DivI,
		ops.Exp,
		ops.Floor,
		ops.Log,
		ops.Log10,
		ops.Mod,
		ops.Mul,
		ops.Neg,
		ops.Pow,
		ops.Rem,
		ops.Sign,
		ops.Sqrt,
		ops.Sub,
	},
	Macros: []zc.Macro{
		{Name: "a", Expr: "add"},
		{Name: "+", Expr: "add"},
		{Name: "cb", Expr: "dup dup mul mul"},
		{Name: "d", Expr: "div"},
		{Name: "/", Expr: "div"},
		{Name: "dr", Expr: "div.rem"},
		{Name: "m", Expr: "mul"},
		{Name: "*", Expr: "mul"},
		{Name: "**", Expr: "pow"},
		{Name: "%", Expr: "rem"},
		{Name: "sq", Expr: "dup mul"},
		{Name: "s", Expr: "sub"},
		{Name: "-", Expr: "sub"},
	},
}
