package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicComplex = zc.Vol{
	Name: "basic/Complex",
	Ops: []zc.Op{
		ops.AddComplex,
		ops.DivComplex,
		ops.MulComplex,
		ops.NegComplex,
		ops.SqrtComplex,
		ops.SubComplex,
	},
	Macros: []zc.Macro{},
}
