package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicFloat = zc.Vol{
	Name: "basic/Float",
	Ops: []zc.Op{
		ops.AddBigFloat,
		ops.DivBigFloat,
		ops.MulBigFloat,
		ops.NegBigFloat,
		ops.SignBigFloat,
		ops.SqrtBigFloat,
		ops.SubBigFloat,
	},
	Macros: []zc.Macro{
		{Name: "sqrt/f", Expr: "square.root/f"},
	},
}
