package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicInt = zc.Vol{
	Name: "basic/Int",
	Ops: []zc.Op{
		ops.DivBigInt,
		ops.SqrtBigInt,
	},
	Macros: []zc.Macro{},
}
