package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicIntU64 = zc.Vol{
	Name: "basic/Int/u64",
	Ops: []zc.Op{
		ops.AddUint64,
	},
	Macros: []zc.Macro{},
}
