package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Basic = zc.Vol{
	Name: "basic",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "cube", Expr: "dup dup mul mul"},
		{Name: "cb", Expr: "cube"},
		{Name: "square", Expr: "dup mul"},
		{Name: "sq", Expr: "square"},
	},
}
