package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var BasicIntU8 = zc.Vol{
	Name: "basic/Int/u8",
	Ops: []zc.Op{
		ops.AddUint8,
	},
	Macros: []zc.Macro{},
}
