package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Bool = zc.Vol{
	Name: "bool",
	Ops: []zc.Op{
		ops.AndBool,
		ops.NotBool,
		ops.OrBool,
	},
	Macros: []zc.Macro{
		{Name: "false", Expr: "/false"},
		{Name: "true", Expr: "/true"},
	},
}
