package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Cmp = zc.Vol{
	Name: "cmp",
	Ops: []zc.Op{
		ops.Eq,
		ops.Gt,
		ops.Gte,
		ops.Lt,
		ops.Lte,
		ops.Neq,
		ops.Sort,
		ops.SortT,
	},
	Macros: []zc.Macro{},
}
