package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Color = zc.Vol{
	Name: "color",
	Ops: []zc.Op{
		ops.CmykRgb,
		ops.HslRgb,
		ops.RgbCmyk,
		ops.RgbHsl,
	},
	Macros: []zc.Macro{},
}
