package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Complex = zc.Vol{
	Name: "complex",
	Ops: []zc.Op{
		ops.SquareRootC,
	},
	Macros: []zc.Macro{
		{Name: "sqrt/c", Expr: "square.root/c"},
	},
}
