package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Conf = zc.Vol{
	Name: "conf",
	Ops: []zc.Op{
		ops.RoundingModeSet,
		ops.RoundingModeGet,
	},
	Macros: []zc.Macro{},
}
