package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Const = zc.Vol{
	Name: "const",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "e", Expr: "2.71828182845904523536028747135266249775724709369995957496696763"},
		{Name: "pi", Expr: "3.14159265358979323846264338327950288419716939937510582097494459"},
	},
}
