package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Crypto = zc.Vol{
	Name: "crypto",
	Ops: []zc.Op{
		ops.Md5,
		ops.Rotate13,
		ops.Sha1,
		ops.Sha1Hmac,
		ops.Sha224,
		ops.Sha224Hmac,
		ops.Sha256,
		ops.Sha256Hmac,
		ops.Sha384,
		ops.Sha384Hmac,
		ops.Sha512,
		ops.Sha512Hmac,
	},
	Macros: []zc.Macro{
		{Name: "rot13", Expr: "rotate.13"},
	},
}
