package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Dec = zc.Vol{
	Name: "dec",
	Ops: []zc.Op{
		ops.Dec,
		ops.RoundingModeD,
		ops.RoundingModeDQ,
		ops.Trunc,
	},
	Macros: []zc.Macro{},
}
