package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Epsg = zc.Vol{
	Name: "epsg",
	Ops: []zc.Op{
		ops.EpsgUtm,
	},
	Macros: []zc.Macro{
		{Name: "epsg.web-mercator", Expr: "'EPSG:3857'"},
		{Name: "epsg.wgs-84", Expr: "'EPSG:4326'"},
	},
}
