package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Float = zc.Vol{
	Name: "float",
	Ops: []zc.Op{
		ops.AddF,
		ops.AddSp,
		ops.AddV,
		ops.CbrtF,
		ops.DivF,
		ops.DivSp,
		ops.DivV,
		ops.ExpF,
		ops.LogF,
		ops.Log10F,
		ops.MulF,
		ops.MulSp,
		ops.MulV,
		ops.NegF,
		ops.NegV,
		ops.PrecV,
		ops.PrecVQ,
		ops.SignF,
		ops.SqrtF,
		ops.SqrtV,
		ops.SubF,
		ops.SubSp,
		ops.SubV,
	},
	Macros: []zc.Macro{},
}
