package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Format = zc.Vol{
	Name: "format",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "r", Expr: "round"},
		{Name: "sci", Expr: "scientific.notation"},
	},
}
