package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Format = zc.Vol{
	Name: "format",
	Ops: []zc.Op{
		ops.RoundDecimal,
		ops.RoundComplex,
		ops.ScientificNotationDecimal,
	},
	Macros: []zc.Macro{
		{Name: "r", Expr: "round"},
		{Name: "sci", Expr: "scientific.notation"},
	},
}
