package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Geo = zc.Vol{
	Name: "geo",
	Ops: []zc.Op{
		ops.Haversine,
		ops.Proj,
	},
	Macros: []zc.Macro{
		{Name: "earth.radius", Expr: "6,371,000 /m unit"},
		{Name: "earth.radius.equatorial", Expr: "6,378,137 /m unit"},
		{Name: "earth.radius.polar", Expr: "6,356,752 /m unit"},
	},
}
