package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Hof = zc.Vol{
	Name: "hof",
	Ops: []zc.Op{
		ops.Eval,
		ops.Map,
	},
	Macros: []zc.Macro{},
}
