package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Iec = zc.Vol{
	Name: "iec",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "kibi", Expr: "2 10 pow"},
		{Name: "mebi", Expr: "2 20 pow"},
		{Name: "gibi", Expr: "2 30 pow"},
		{Name: "tebi", Expr: "2 40 pow"},
		{Name: "pebi", Expr: "2 50 pow"},
		{Name: "exbi", Expr: "2 60 pow"},
	},
}
