package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Int = zc.Vol{
	Name: "int",
	Ops: []zc.Op{
		ops.AddS,
		ops.AddS16,
		ops.AddS32,
		ops.AddS64,
		ops.AddS8,
		ops.AddU,
		ops.AddU16,
		ops.AddU32,
		ops.AddU64,
		ops.AddU8,
		ops.DataInt,
		ops.IntData,
		ops.IntQ,
		ops.IntQS,
		ops.IntQS16,
		ops.IntQS32,
		ops.IntQS64,
		ops.IntQS8,
		ops.IntQU,
		ops.IntQU16,
		ops.IntQU32,
		ops.IntQU64,
		ops.IntQU8,
		ops.MaxIntS,
		ops.MaxIntU,
		ops.MinIntS,
		ops.SubS,
		ops.SubS16,
		ops.SubS32,
		ops.SubS64,
		ops.SubS8,
		ops.SubU,
		ops.SubU16,
		ops.SubU32,
		ops.SubU64,
		ops.SubU8,
	},
	Macros: []zc.Macro{
		{Name: "max.int/s16", Expr: "32767"},
		{Name: "max.int/s32", Expr: "2147483647"},
		{Name: "max.int/s64", Expr: "9223372036854775807"},
		{Name: "max.int/s8", Expr: "127"},
		{Name: "max.int/u16", Expr: "65535"},
		{Name: "max.int/u32", Expr: "4294967295"},
		{Name: "max.int/u64", Expr: "18446744073709551615"},
		{Name: "max.int/u8", Expr: "255"},
		{Name: "min.int/s16", Expr: "-32768"},
		{Name: "min.int/s32", Expr: "-2147483648"},
		{Name: "min.int/s64", Expr: "-9223372036854775808"},
		{Name: "min.int/s8", Expr: "-128"},
	},
}
