package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Len = zc.Vol{
	Name: "len",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "ft-m", Expr: "0.3048 mul /m unit"},
		{Name: "ft-mi", Expr: "5280 div /mi unit"},
		{Name: "ft-yd", Expr: "3 div /yd unit"},
		{Name: "in-mm", Expr: "25.4 mul /mm unit"},
		{Name: "km-m", Expr: "1000 mul /m unit"},
		{Name: "km-mi", Expr: "0.62137119 mul /mi unit"},
		{Name: "km-nmi", Expr: "0.539957 mul /nmi unit"},
		{Name: "m-ft", Expr: "0.3048 div /ft unit"},
		{Name: "m-km", Expr: "1000 div /km unit"},
		{Name: "m-nmi", Expr: "0.000539957 mul /nmi unit"},
		{Name: "m-yd", Expr: "0.9144 div /yd unit"},
		{Name: "mi-ft", Expr: "5280 mul /ft unit"},
		{Name: "mi-km", Expr: "1.609344 mul /km unit"},
		{Name: "mi-nmi", Expr: "0.868976 mul /nmi unit"},
		{Name: "mm-in", Expr: "25.4 div /in unit"},
		{Name: "nmi-km", Expr: "1.852 mul /km unit"},
		{Name: "nmi-m", Expr: "1852 mul /m unit"},
		{Name: "yd-ft", Expr: "3 mul /ft unit"},
		{Name: "yd-m", Expr: "0.9144 mul /m unit"},
	},
}
