package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Mass = zc.Vol{
	Name: "mass",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "g-kg", Expr: "1000 div /kg unit"},
		{Name: "g-oz", Expr: "1 28.349523125 div mul /oz unit"},
		{Name: "g-ozt", Expr: "1 31.1034768 div mul [oz t] unit"},
		{Name: "kg-g", Expr: "1000 mul /kg unit"},
		{Name: "kg-lb", Expr: "1 0.45359237 div mul /lb unit"},
		{Name: "lb-kg", Expr: "0.45359237 mul /kg unit"},
		{Name: "oz-g", Expr: "28.349523125 mul /g unit"},
		{Name: "ozt-g", Expr: "31.1034768 mul /g unit"},
	},
}
