package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var ProgIntU8 = zc.Vol{
	Name: "prog/Int/u8",
	Ops: []zc.Op{
		ops.AddUint8,
		ops.Uint8Uint64,
		ops.Uint8Int64,
		ops.LeftRotateUint8,
		ops.LeftShiftUint8,
		ops.NegUint8,
		ops.NotUint8,
		ops.RightRotateUint8,
		ops.RightShiftUint8,
		ops.SubUint8,
	},
	Macros: []zc.Macro{
		{Name: "lro/u8", Expr: "left.rotate/u8"},
		{Name: "lsh/u8", Expr: "left.shift/u8"},
		{Name: "max.int/u8", Expr: "255"},
		{Name: "rro/u8", Expr: "right.rotate/u8"},
		{Name: "rsh/u8", Expr: "right.shift/u8"},
	},
}
