package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Prog = zc.Vol{
	Name: "prog",
	Ops: []zc.Op{
		ops.AndBigInt,
		ops.BcdDec,
		ops.Bin,
		ops.Bit,
		ops.Bits,
		ops.Bytes,
		ops.DecBcd,
		ops.DecBigInt,
		ops.Hex,
		ops.Lsh,
		ops.NotBigInt,
		ops.Oct,
		ops.OrBigInt,
		ops.Rsh,
		ops.XorBigInt,
	},
	Macros: []zc.Macro{
		{Name: "lsh", Expr: "left.shift"},
		{Name: "rsh", Expr: "right.shift"},
	},
}
