package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var ProgLimits = zc.Vol{
	Name: "prog/limits",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.int/u16", Expr: "65535"},
		{Name: "max.int/u8", Expr: "255"},
	},
}
