package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var ProgIntS8 = zc.Vol{
	Name: "prog/Int/s8",
	Ops: []zc.Op{
		ops.AddInt8,
	},
	Macros: []zc.Macro{},
}
