package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Prog = zc.Vol{
	Name: "prog",
	Ops: []zc.Op{
		ops.And,
		ops.Bin,
		ops.Bit,
		ops.Bits,
		ops.Bytes,
		ops.Dec,
		ops.Hex,
		ops.LeftShift,
		ops.Not,
		ops.Oct,
		ops.Or,
		ops.RightShift,
		ops.Xor,
	},
	Macros: []zc.Macro{
		{Name: "lsh", Expr: "left.shift"},
		{Name: "rsh", Expr: "right.shift"},
	},
}
