package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var ProgIntS32 = zc.Vol{
	Name: "prog/Int/s32",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.int/s32", Expr: "2147483647"},
	},
}
