package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Rand = zc.Vol{
	Name: "rand",
	Ops: []zc.Op{
		ops.Rand,
		ops.RandSeed,
		ops.RandSeedGet,
		ops.RandTake,
		ops.RandI,
		ops.Roll,
	},
	Macros: []zc.Macro{
		{Name: "rand/f", Expr: "rand"},
	},
}
