package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Real = zc.Vol{
	Name: "real",
	Ops: []zc.Op{
		ops.Dec,
		ops.RoundingMode,
		ops.RoundingModeQ,
		ops.Trunc,
	},
	Macros: []zc.Macro{},
}
