package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciFloat64 = zc.Vol{
	Name: "sci/Float/64",
	Ops: []zc.Op{
		ops.AbsFloat64,
		ops.AcosFloat64,
		ops.AcoshFloat64,
		ops.AsinFloat64,
		ops.AsinhFloat64,
		ops.AtanFloat64,
		ops.AtanhFloat64,
	},
	Macros: []zc.Macro{},
}
