package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciInt = zc.Vol{
	Name: "sci/Int",
	Ops: []zc.Op{
		ops.AbsBigInt,
	},
	Macros: []zc.Macro{},
}
