package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciDec = zc.Vol{
	Name: "sci/Dec",
	Ops: []zc.Op{
		ops.AbsDecimal,
		ops.CbrtDecimal,
	},
	Macros: []zc.Macro{},
}
