package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Sci = zc.Vol{
	Name: "sci",
	Ops: []zc.Op{
		ops.Acos,
		ops.Acosh,
		ops.Asin,
		ops.Asinh,
		ops.Atan,
		ops.Atan2,
		ops.Atanh,
		ops.Cos,
		ops.Cosh,
		ops.Sin,
		ops.Sinh,
		ops.Tan,
		ops.Tanh,
	},
	Macros: []zc.Macro{},
}
