package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciComplex128 = zc.Vol{
	Name: "sci/Complex/128",
	Ops: []zc.Op{
		ops.AbsComplex128,
	},
	Macros: []zc.Macro{},
}
