package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciComplex = zc.Vol{
	Name: "sci/Complex",
	Ops: []zc.Op{
		ops.AbsComplex,
		ops.AcosComplex,
		ops.AcoshComplex,
		ops.AsinComplex,
		ops.AsinhComplex,
		ops.AtanComplex,
		ops.AtanhComplex,
	},
	Macros: []zc.Macro{},
}
