package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Seq = zc.Vol{
	Name: "seq",
	Ops: []zc.Op{
		ops.Fibonacci,
		ops.Sequence,
	},
	Macros: []zc.Macro{
		{Name: "fib", Expr: "fibonacci"},
		{Name: "seq", Expr: "sequence"},
	},
}
