package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Si = zc.Vol{
	Name: "si",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "quetta", Expr: "1e30"},
		{Name: "ronna", Expr: "1e27"},
		{Name: "yotta", Expr: "1e24"},
		{Name: "zetta", Expr: "1e21"},
		{Name: "exa", Expr: "1e18"},
		{Name: "peta", Expr: "1e15"},
		{Name: "terra", Expr: "1e12"},
		{Name: "giga", Expr: "1e09"},
		{Name: "mega", Expr: "1e06"},
		{Name: "kilo", Expr: "1e03"},
		{Name: "hecto", Expr: "1e02"},
		{Name: "deca", Expr: "1e01"},
		{Name: "deci", Expr: "1e-01"},
		{Name: "centi", Expr: "1e-02"},
		{Name: "milli", Expr: "1e-03"},
		{Name: "micro", Expr: "1e-06"},
		{Name: "nano", Expr: "1e-09"},
		{Name: "pico", Expr: "1e-12"},
		{Name: "femto", Expr: "1e-15"},
		{Name: "atto", Expr: "1e-18"},
		{Name: "zepto", Expr: "1e-21"},
		{Name: "yocto", Expr: "1e-24"},
		{Name: "ronto", Expr: "1e-27"},
		{Name: "quecto", Expr: "1e-30"},
	},
}
