package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Stack = zc.Vol{
	Name: "stack",
	Ops: []zc.Op{
		ops.Clear,
		ops.Drop,
		ops.Dup,
		ops.N,
		ops.Swap,
		ops.Tuck,
	},
	Macros: []zc.Macro{
		{Name: "c", Expr: "clear"},
		{Name: "sw", Expr: "swap"},
	},
}
