package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Stat = zc.Vol{
	Name: "stat",
	Ops: []zc.Op{
		ops.Factorial,
		ops.FactorialF,
	},
	Macros: []zc.Macro{
		{Name: "average", Expr: "n push sum pop div"},
		{Name: "avg", Expr: "average"},
		{Name: "fact", Expr: "factorial"},
		{Name: "fact/f", Expr: "factorial/f"},
		{Name: "sum", Expr: "0 /add fold"},
	},
}
