package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Temp = zc.Vol{
	Name: "temp",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "c-f", Expr: "9 5 div mul 32 add /°F unit"},
		{Name: "c-k", Expr: "273.15 add /K unit"},
		{Name: "f-c", Expr: "32 sub 5 9 div mul /°C unit"},
		{Name: "k-c", Expr: "273.15 sub /°C unit"},
	},
}
