package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Text = zc.Vol{
	Name: "text",
	Ops: []zc.Op{
		ops.Len,
	},
	Macros: []zc.Macro{},
}
