package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Time = zc.Vol{
	Name: "time",
	Ops: []zc.Op{
		ops.AddTime,
		ops.LocalZoneSet,
		ops.Now,
		ops.NowSet,
		ops.Time,
	},
	Macros: []zc.Macro{},
}
