package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Time = zc.Vol{
	Name: "time",
	Ops: []zc.Op{
		ops.AddTime,
		ops.Date,
		ops.DateTime,
		ops.DateTimeGet,
		ops.DateGet,
		ops.DayYear,
		ops.Hours,
		ops.LocalZone,
		ops.LocalZoneSet,
		ops.MinutesTime,
		ops.Now,
		ops.NowReset,
		ops.NowSet,
		ops.SecondsTime,
		ops.SubTime,
		ops.Time,
		ops.TimeZone,
		ops.TimeGet,
	},
	Macros: []zc.Macro{
		{Name: "dt", Expr: "date.time"},
		{Name: "dt?", Expr: "date.time?"},
		{Name: "doy", Expr: "day.year"},
		{Name: "now-", Expr: "now.reset"},
		{Name: "tz", Expr: "time.zone"},
	},
}
