package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var TypesIntU64 = zc.Vol{
	Name: "types/Int/u64",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.u64", Expr: "18446744073709551615"},
	},
}
