package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var TypesIntU16 = zc.Vol{
	Name: "types/Int/u16",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.val/u16", Expr: "65535"},
	},
}
