package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var TypesIntU8 = zc.Vol{
	Name: "types/Int/u8",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.val/u8", Expr: "255"},
	},
}
