package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Types = zc.Vol{
	Name: "types",
	Ops: []zc.Op{
		ops.Types,
	},
	Macros: []zc.Macro{},
}
