package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var TypesInt = zc.Vol{
	Name: "types/Int",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.val/u16", Expr: "65535"},
		{Name: "max.val/u8", Expr: "255"},
	},
}
