package floatb

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	AddFloat = zc.Op{
		Name:      "add.float",
		Overloads: "add",
		Aliases: []string{
			"addf",
		},
		Params:  []string{kinds.Float, kinds.Float},
		Returns: []string{kinds.Float},
		Prec:    kinds.PrecFloat,
		Func:    add,
	}
)
