package floatb

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	Add = zc.Op{
		Name: "add",
		Aliases: []string{
			"add.float",
			"addf",
			"+",
		},
		Params:  []string{kinds.Float, kinds.Float},
		Returns: []string{kinds.Float},
		Prec:    kinds.PrecFloat,
		Func:    add,
	}
)
