// Code generated by 'gen-ops'; DO NOT EDIT
package floatb

import (
	"github.com/blackchip-org/zc/v6"
)

var Volume = zc.Vol{
	Name: "float",
	Kinds: []zc.Kind{
		FloatKind,
	},
	Ops: []zc.Op{
		Add,
	},
}
