package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Anno_Label(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("42")
	c.AssertStack("42")

	c.Eval("/answer label")
	c.AssertStack("42 :answer")
}

func TestOpDocs_Anno_Unit(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("42")
	c.AssertStack("42")

	c.Eval("/°F unit")
	c.AssertStack("42°F")
}
