package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicDec_AddD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("add/d")
	c.AssertStack("8.8")
}

func TestOpDocs_BasicDec_CubeRootD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.25 cube")
	c.AssertStack("1.953125")

	c.Eval("cbrt/d")
	c.AssertStack("1.25")
}

func TestOpDocs_BasicDec_CubeRootD_negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 cbrt/d")
	c.AssertError("cube.root/d: invalid argument, -1 < 0")
}

func TestOpDocs_BasicDec_DivD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2")
	c.AssertStack("6.6", "2")

	c.Eval("div/d")
	c.AssertStack("3.3")
}

func TestOpDocs_BasicDec_DivD_Thirds(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 3 div/d")
	c.AssertStack("0.6666666666666667")
}

func TestOpDocs_BasicDec_DivD_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 0 div/d")
	c.AssertError("div/d: division by zero")
}

func TestOpDocs_BasicDec_MulD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("mul/d")
	c.AssertStack("14.52")
}

func TestOpDocs_BasicDec_NegD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6")
	c.AssertStack("-6.6")

	c.Eval("neg/d")
	c.AssertStack("6.6")

	c.Eval("neg/d")
	c.AssertStack("-6.6")
}

func TestOpDocs_BasicDec_PowD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("pow/d")
	c.AssertStack("63.53260431279859")
}

func TestOpDocs_BasicDec_PowD_NegativeSqrt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 0.5 pow/d")
	c.AssertError("pow/d: invalid operation")
}

func TestOpDocs_BasicDec_PowD_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 0 pow/d")
	c.AssertError("pow/d: invalid operation")
}

func TestOpDocs_BasicDec_PowD_Inf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 -1 pow/d")
	c.AssertError("pow/d: infinity")
}

func TestOpDocs_BasicDec_RemD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.75")
	c.AssertStack("6.75")

	c.Eval("0.5")
	c.AssertStack("6.75", "0.5")

	c.Eval("rem/d")
	c.AssertStack("0.25")
}

func TestOpDocs_BasicDec_RemD_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 rem/d")
	c.AssertError("rem/d: division by zero")
}

func TestOpDocs_BasicDec_SignD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -6.4 sign/d")
	c.AssertStack("-1")

	c.Eval("c 6.4 sign/d")
	c.AssertStack("1")

	c.Eval("c 0 sign/d")
	c.AssertStack("0")
}

func TestOpDocs_BasicDec_SquareRootD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.25 sq")
	c.AssertStack("1.5625")

	c.Eval("sqrt/d")
	c.AssertStack("1.25")
}

func TestOpDocs_BasicDec_SquareRootD_Negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 sqrt/d")
	c.AssertError("square.root/d: invalid argument, -1 < 0")
}

func TestOpDocs_BasicDec_SubD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("sub/d")
	c.AssertStack("4.4")
}
