package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicIntU32_AddU32(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("4294967295 1 add/u32")
	c.AssertStack("0")
}
