package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicRat_AddR(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1/2 1/4 add/r")
	c.AssertStack("3/4")
}

func TestOpDocs_BasicRat_DivR(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("5 2 div/r")
	c.AssertStack("2 1/2")
}

func TestOpDocs_BasicRat_DivR_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("5 0 div/r")
	c.AssertError("div/r: division by zero")
}

func TestOpDocs_BasicRat_MulR(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1/16 4 mul/r")
	c.AssertStack("1/4")
}

func TestOpDocs_BasicRat_NegR(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 neg/r")
	c.AssertStack("-1/2")
}

func TestOpDocs_BasicRat_SubR(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("3/4 1/2 sub/r")
	c.AssertStack("1/4")
}
