package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Basic_Abs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6 abs")
	c.AssertStack("6")

	c.Eval("c 2+2i abs 5 round")
	c.AssertStack("2.82843")
}

func TestOpDocs_Basic_Abs_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6 abs")
	c.AssertStack("6.6")
}

func TestOpDocs_Basic_Add(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 2 a")
	c.AssertStack("8")

	c.Eval("c 1.1 2.2 a")
	c.AssertStack("3.3")

	c.Eval("c 1/2 1/4 add")
	c.AssertStack("3/4")

	c.Eval("c 6+6i 2+2i a")
	c.AssertStack("8+8i")
}

func TestOpDocs_Basic_Cbrt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("27")
	c.AssertStack("27")

	c.Eval("cbrt")
	c.AssertStack("3")
}

func TestOpDocs_Basic_Ceil(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 ceil")
	c.AssertStack("7")
}

func TestOpDocs_Basic_Div(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 12 4 d")
	c.AssertStack("3")

	c.Eval("c 11 2 d")
	c.AssertStack("5.5")

	c.Eval("c 1/4 4 div")
	c.AssertStack("1/16")

	c.Eval("c 12+12i 4+12i d")
	c.AssertStack("1.2-0.6i")
}

func TestOpDocs_Basic_Div_Thirds(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 3 div")
	c.AssertStack("0.6666666666666666666666666667")
}

func TestOpDocs_Basic_Div_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 0 div")
	c.AssertError("div: division by zero")
}

func TestOpDocs_Basic_DivMod(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -21 4 div.mod")
	c.AssertStack("-6 :quo", "3 :mod")

	c.Eval("c -21 4 div.rem")
	c.AssertStack("-5 :quo", "-1 :rem")
}

func TestOpDocs_Basic_DivMod_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 div.mod")
	c.AssertError("div.mod: division by zero")
}

func TestOpDocs_Basic_DivRem(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -21 4 div.mod")
	c.AssertStack("-6 :quo", "3 :mod")

	c.Eval("c -21 4 div.rem")
	c.AssertStack("-5 :quo", "-1 :rem")
}

func TestOpDocs_Basic_DivRem_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 div.rem")
	c.AssertError("div.rem: division by zero")
}

func TestOpDocs_Basic_DivI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-21 4 div/i")
	c.AssertStack("-6")
}

func TestOpDocs_Basic_DivI_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 div/i")
	c.AssertError("div/i: division by zero")
}

func TestOpDocs_Basic_Exp(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 exp 5 round")
	c.AssertStack("7.38906")
}

func TestOpDocs_Basic_Floor(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.12 floor")
	c.AssertStack("6")
}

func TestOpDocs_Basic_Ln(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("7.5 ln 4 round")
	c.AssertStack("2.0149")
}

func TestOpDocs_Basic_Log10(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("50 log10 5 round")
	c.AssertStack("1.69897")
}

func TestOpDocs_Basic_Mod(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -21 4 mod")
	c.AssertStack("3")

	c.Eval("c -21 4 rem")
	c.AssertStack("-1")
}

func TestOpDocs_Basic_Mod_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 mod")
	c.AssertError("mod: division by zero")
}

func TestOpDocs_Basic_Mul(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 2 mul")
	c.AssertStack("12")

	c.Eval("c 6.6 2.2 mul")
	c.AssertStack("14.52")

	c.Eval("c 1/16 4 mul")
	c.AssertStack("1/4")

	c.Eval("c 2+3i 4+4i m")
	c.AssertStack("-4+20i")
}

func TestOpDocs_Basic_Neg(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6")
	c.AssertStack("-6")

	c.Eval("neg")
	c.AssertStack("6")

	c.Eval("neg")
	c.AssertStack("-6")
}

func TestOpDocs_Basic_Neg_Decimal(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6 neg")
	c.AssertStack("6.6")
}

func TestOpDocs_Basic_Pow(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 2 pow")
	c.AssertStack("36")

	c.Eval("c 6.6 2.2 pow 2 round")
	c.AssertStack("63.53")

	c.Eval("c 6+6i 2+2i pow 2 round")
	c.AssertStack("13.57-6.32i")
}

func TestOpDocs_Basic_Pow_BigIntZero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 0 pow")
	c.AssertStack("1")
}

func TestOpDocs_Basic_Pow_BigIntInf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 -1 pow")
	c.AssertStack("1")
}

func TestOpDocs_Basic_Pow_DecimalNegativeSqrt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 0.5 pow")
	c.AssertError("pow: invalid operation")
}

func TestOpDocs_Basic_Pow_DecimalZero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.0 0.0 pow")
	c.AssertError("pow: invalid operation")
}

func TestOpDocs_Basic_Pow_DecimalInf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.0 -1 pow")
	c.AssertError("pow: infinity")
}

func TestOpDocs_Basic_Rem(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -21 4 mod")
	c.AssertStack("3")

	c.Eval("c -21 4 rem")
	c.AssertStack("-1")
}

func TestOpDocs_Basic_Rem_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 rem")
	c.AssertError("rem: division by zero")
}

func TestOpDocs_Basic_Sign(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -6 sign")
	c.AssertStack("-1")

	c.Eval("c 6 sign")
	c.AssertStack("1")

	c.Eval("c 0 sign")
	c.AssertStack("0")
}

func TestOpDocs_Basic_Sign_Decimal(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.4 sign")
	c.AssertStack("-1")
}

func TestOpDocs_Basic_Sq(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("3 sq")
	c.AssertStack("9")
}

func TestOpDocs_Basic_Sqrt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 1.5625 sqrt")
	c.AssertStack("1.25")

	c.Eval("c -4+0i sqrt")
	c.AssertStack("0+2i")
}

func TestOpDocs_Basic_Sqrt_Negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 sqrt")
	c.AssertError("sqrt: invalid argument, -1 < 0")
}

func TestOpDocs_Basic_Sub(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 2 sub")
	c.AssertStack("4")

	c.Eval("c 6.6 2.2 sub")
	c.AssertStack("4.4")

	c.Eval("c 3/4 1/2 sub")
	c.AssertStack("1/4")

	c.Eval("c 6+6i 2+2i sub")
	c.AssertStack("4+4i")
}
