package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicIntU8_AddU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("255 1 add/u8")
	c.AssertStack("0")
}
