package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicIntU16_AddU16(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("65535 1 add/u16")
	c.AssertStack("0")
}
