package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicDecSS_AddDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("add/d/ss")
	c.AssertStack("8.8")
}

func TestOpDocs_BasicDecSS_DivDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2")
	c.AssertStack("6.6", "2")

	c.Eval("div/d/ss")
	c.AssertStack("3.3")
}

func TestOpDocs_BasicDecSS_DivDSs_Thirds(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 3 div/d/ss")
	c.AssertStack("0.6666666666666667")
}

func TestOpDocs_BasicDecSS_DivDSs_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 0 div/d/ss")
	c.AssertError("div/d/ss: division by zero")
}

func TestOpDocs_BasicDecSS_ModDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.75")
	c.AssertStack("6.75")

	c.Eval("0.5")
	c.AssertStack("6.75", "0.5")

	c.Eval("mod/d/ss")
	c.AssertStack("0.25")
}

func TestOpDocs_BasicDecSS_ModDSs_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 mod/d/ss")
	c.AssertError("mod/d/ss: division by zero")
}

func TestOpDocs_BasicDecSS_MulDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("mul/d/ss")
	c.AssertStack("14.52")
}

func TestOpDocs_BasicDecSS_NegDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6")
	c.AssertStack("-6.6")

	c.Eval("neg/d/ss")
	c.AssertStack("6.6")

	c.Eval("neg/d/ss")
	c.AssertStack("-6.6")
}

func TestOpDocs_BasicDecSS_PowDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("pow/d/ss")
	c.AssertStack("63.53260431279859336003829262")
}

func TestOpDocs_BasicDecSS_PowDSs_NegativeSqrt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 0.5 pow/d/ss")
	c.AssertError("pow/d/ss: invalid argument, root of negative number: -1")
}

func TestOpDocs_BasicDecSS_PowDSs_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 0 pow/d/ss")
	c.AssertError("pow/d/ss: undefined")
}

func TestOpDocs_BasicDecSS_PowDSs_Inf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 -1 pow/d/ss")
	c.AssertError("pow/d/ss: infinity")
}

func TestOpDocs_BasicDecSS_RemDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("$100")
	c.AssertStack("$100")

	c.Eval("3")
	c.AssertStack("$100", "3")

	c.Eval("2 rem/d/ss")
	c.AssertStack("0.01")
}

func TestOpDocs_BasicDecSS_RemDSs_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 0 rem/d/ss")
	c.AssertError("rem/d/ss: division by zero")
}

func TestOpDocs_BasicDecSS_SubDSs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("sub/d/ss")
	c.AssertStack("4.4")
}
