package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicInt_DivE(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -7 2 div/i")
	c.AssertStack("-3")

	c.Eval("c -7 2 div.e")
	c.AssertStack("-4")
}

func TestOpDocs_BasicInt_DivModE(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-7 2 div.mod.e")
	c.AssertStack("-4 :quo", "1 :mod")
}

func TestOpDocs_BasicInt_DivI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -7 2 div/i")
	c.AssertStack("-3")

	c.Eval("c -7 2 div.e")
	c.AssertStack("-4")
}

func TestOpDocs_BasicInt_SqrtI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("7 sqrt/i")
	c.AssertStack("2")
}
