package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicInt_AddI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6")
	c.AssertStack("6")

	c.Eval("2")
	c.AssertStack("6", "2")

	c.Eval("add/i")
	c.AssertStack("8")
}

func TestOpDocs_BasicInt_MulI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6")
	c.AssertStack("6")

	c.Eval("2")
	c.AssertStack("6", "2")

	c.Eval("mul/i")
	c.AssertStack("12")
}

func TestOpDocs_BasicInt_PowI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6")
	c.AssertStack("6")

	c.Eval("2")
	c.AssertStack("6", "2")

	c.Eval("pow/i")
	c.AssertStack("36")
}

func TestOpDocs_BasicInt_SqrtI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("65536")
	c.AssertStack("65536")

	c.Eval("sqrt/i")
	c.AssertStack("256")
}

func TestOpDocs_BasicInt_SqrtI_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 sqrt/i")
	c.AssertStack("0")
}

func TestOpDocs_BasicInt_SqrtI_Neg(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 sqrt/i")
	c.AssertError("sqrt/i: invalid argument, -1 < 0")
}

func TestOpDocs_BasicInt_SubI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6")
	c.AssertStack("6")

	c.Eval("2")
	c.AssertStack("6", "2")

	c.Eval("sub/i")
	c.AssertStack("4")
}
