package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicFloat_AddF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1")
	c.AssertStack("1.1")

	c.Eval("2.2")
	c.AssertStack("1.1", "2.2")

	c.Eval("add/f")
	c.AssertStack("3.3000000000000003")
}

func TestOpDocs_BasicFloat_DivF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2")
	c.AssertStack("2")

	c.Eval("3")
	c.AssertStack("2", "3")

	c.Eval("div/f")
	c.AssertStack("0.6666666666666666")
}

func TestOpDocs_BasicFloat_DivF_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6 0 div/f")
	c.AssertError("div/f: division by zero")
}

func TestOpDocs_BasicFloat_MulF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("mul/f")
	c.AssertStack("14.52")
}

func TestOpDocs_BasicFloat_NegF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6")
	c.AssertStack("-6.6")

	c.Eval("neg/f")
	c.AssertStack("6.6")

	c.Eval("neg/f")
	c.AssertStack("-6.6")
}

func TestOpDocs_BasicFloat_SignF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -6.4 sign/f")
	c.AssertStack("-1")

	c.Eval("c 6.4 sign/f")
	c.AssertStack("1")

	c.Eval("c 0 sign/f")
	c.AssertStack("0")
}

func TestOpDocs_BasicFloat_SqrtF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.25 sq")
	c.AssertStack("1.5625")

	c.Eval("sqrt/f")
	c.AssertStack("1.25")
}

func TestOpDocs_BasicFloat_SqrtF_Negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 sqrt/f")
	c.AssertError("sqrt/f: invalid argument, -1 < 0")
}

func TestOpDocs_BasicFloat_SubF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6")
	c.AssertStack("6.6")

	c.Eval("2.2")
	c.AssertStack("6.6", "2.2")

	c.Eval("sub/f")
	c.AssertStack("4.3999999999999995")
}
