package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Color_CmykRgb(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 127 191 127 cmyk-rgb")
	c.AssertStack("128", "64", "32")
}

func TestOpDocs_Color_HslRgb(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("20 0.6 0.314 hsl-rgb")
	c.AssertStack("128", "64", "32")
}

func TestOpDocs_Color_RgbCmyk(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("128 64 32 rgb-cmyk")
	c.AssertStack("0", "127", "191", "127")
}

func TestOpDocs_Color_RgbHsl(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("128 64 32 rgb-hsl [3 round] map")
	c.AssertStack("20", "0.6", "0.314")
}
