package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Conf_RoundingModeSet(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("rounding.mode?")
	c.AssertStack("half.even")

	c.Eval("c 5.55 1 round")
	c.AssertStack("5.6")

	c.Eval("/down rounding.mode=")
	c.AssertNotice("rounding mode set to down")

	c.Eval("c 5.55 1 round")
	c.AssertStack("5.5")
}

func TestOpDocs_Conf_RoundingModeGet(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("rounding.mode?")
	c.AssertStack("half.even")
}
