package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Format_Round(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("200000 3 div")
	c.AssertStack("66666.66666666667")

	c.Eval("3 round/d")
	c.AssertStack("66666.667")

	c.Eval("0 round/d")
	c.AssertStack("66667")

	c.Eval("-3 round/d")
	c.AssertStack("67000")
}

func TestOpDocs_Format_ScientificNotation(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("123 sn")
	c.AssertStack("1.23e2")
}
