package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Hof_Eval(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'1 2 add' eval")
	c.AssertStack("3")
}

func TestOpDocs_Hof_Map(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2 3 4 5")
	c.AssertStack("1", "2", "3", "4", "5")

	c.Eval("[2 mul] map")
	c.AssertStack("2", "4", "6", "8", "10")
}
