package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Len_FtM(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1000 ft-m")
	c.AssertStack("304.8 m")
}

func TestOpDocs_Len_FtMi(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2640 ft-mi")
	c.AssertStack("0.5 mi")
}

func TestOpDocs_Len_FtYd(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("300 ft-yd")
	c.AssertStack("100 yd")
}

func TestOpDocs_Len_InMm(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 in-mm")
	c.AssertStack("2540 mm")
}

func TestOpDocs_Len_KmM(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6378.137 km-m")
	c.AssertStack("6378137 m")
}

func TestOpDocs_Len_KmMi(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 km-mi 2 round")
	c.AssertStack("62.14 mi")
}

func TestOpDocs_Len_KmNmi(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 km-nmi 2 round")
	c.AssertStack("54 nmi")
}

func TestOpDocs_Len_MFt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("304.8 m-ft 2 round")
	c.AssertStack("1000 ft")
}

func TestOpDocs_Len_MKm(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6378137 m-km")
	c.AssertStack("6378.137 km")
}

func TestOpDocs_Len_MNmi(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100,000 m-nmi 2 round")
	c.AssertStack("54 nmi")
}

func TestOpDocs_Len_MYd(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("91.44 m-yd 2 round")
	c.AssertStack("100 yd")
}

func TestOpDocs_Len_MiFt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 mi-ft")
	c.AssertStack("2640 ft")
}

func TestOpDocs_Len_MiKm(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 mi-km 2 round")
	c.AssertStack("160.93 km")
}

func TestOpDocs_Len_MiNmi(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 mi-nmi 2 round")
	c.AssertStack("86.9 nmi")
}

func TestOpDocs_Len_MmIn(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2540 mm-in 2 round")
	c.AssertStack("100 in")
}

func TestOpDocs_Len_NmiKm(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 nmi-km")
	c.AssertStack("185.2 km")
}

func TestOpDocs_Len_NmiM(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 nmi-m")
	c.AssertStack("185200 m")
}

func TestOpDocs_Len_YdFt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 yd-ft")
	c.AssertStack("300 ft")
}

func TestOpDocs_Len_YdM(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 yd-m")
	c.AssertStack("91.44 m")
}
