package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Mass_GKg(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("52124 g-kg")
	c.AssertStack("52.124 kg")
}

func TestOpDocs_Mass_GOz(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2834.95 g-oz 2 round")
	c.AssertStack("100 oz")
}

func TestOpDocs_Mass_GOzt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("326.59 g-ozt 2 round")
	c.AssertStack("10.5 oz t")
}

func TestOpDocs_Mass_KgG(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("52.124 kg-g")
	c.AssertStack("52124 kg")
}

func TestOpDocs_Mass_KgLb(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("45.36 kg-lb 2 round")
	c.AssertStack("100 lb")
}

func TestOpDocs_Mass_LbKg(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 lb-kg 2 round")
	c.AssertStack("45.36 kg")
}

func TestOpDocs_Mass_OzG(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 oz-g 2 round")
	c.AssertStack("2834.95 g")
}

func TestOpDocs_Mass_OztG(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10.5 ozt-g 2 round")
	c.AssertStack("326.59 g")
}
