package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_ProgIntU8_AddU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("255 1 add/u8")
	c.AssertStack("0")

	c.Eval("info")
	c.AssertInfo("Int/u8: carry")

	c.Eval("c 127 1 add/u8")
	c.AssertStack("128")

	c.Eval("info")
	c.AssertInfo("Int/u8: overflow")
}

func TestOpDocs_ProgIntU8_NegU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x01 neg/u8 hex")
	c.AssertStack("0xff")
}

func TestOpDocs_ProgIntU8_SubU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 1 sub/u8")
	c.AssertStack("255")

	c.Eval("info")
	c.AssertInfo("Int/u8: carry")

	c.Eval("c 128 1 sub/u8")
	c.AssertStack("127")

	c.Eval("info")
	c.AssertInfo("Int/u8: overflow")
}
