package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_ProgIntS32_MaxIntS32(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.int/s32")
	c.AssertStack("2147483647")
}
