package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Prog_And(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b1100")
	c.AssertStack("0b1100")

	c.Eval("0b1010")
	c.AssertStack("0b1100", "0b1010")

	c.Eval("and bin")
	c.AssertStack("0b1000")
}

func TestOpDocs_Prog_Bin(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x0f")
	c.AssertStack("0x0f")

	c.Eval("bin")
	c.AssertStack("0b1111")
}

func TestOpDocs_Prog_Bit(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b100")
	c.AssertStack("0b100")

	c.Eval("2 bit")
	c.AssertStack("1")
}

func TestOpDocs_Prog_Bits(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b11111")
	c.AssertStack("0b11111")

	c.Eval("bits")
	c.AssertStack("5")
}

func TestOpDocs_Prog_Bytes(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x1ff")
	c.AssertStack("0x1ff")

	c.Eval("bytes")
	c.AssertStack("2")
}

func TestOpDocs_Prog_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0xf")
	c.AssertStack("0xf")

	c.Eval("dec")
	c.AssertStack("15")
}

func TestOpDocs_Prog_Hex(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b1111")
	c.AssertStack("0b1111")

	c.Eval("hex")
	c.AssertStack("0xf")
}

func TestOpDocs_Prog_LeftShift(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b10")
	c.AssertStack("0b10")

	c.Eval("2 lsh bin")
	c.AssertStack("0b1000")
}

func TestOpDocs_Prog_Not(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b101")
	c.AssertStack("0b101")

	c.Eval("not bin")
	c.AssertStack("-0b110")
}

func TestOpDocs_Prog_Oct(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b1111")
	c.AssertStack("0b1111")

	c.Eval("oct")
	c.AssertStack("0o17")
}

func TestOpDocs_Prog_Or(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b1100")
	c.AssertStack("0b1100")

	c.Eval("0b1010")
	c.AssertStack("0b1100", "0b1010")

	c.Eval("or bin")
	c.AssertStack("0b1110")
}

func TestOpDocs_Prog_RightShift(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b1000")
	c.AssertStack("0b1000")

	c.Eval("2 rsh bin")
	c.AssertStack("0b10")
}

func TestOpDocs_Prog_Xor(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b1100")
	c.AssertStack("0b1100")

	c.Eval("0b1010")
	c.AssertStack("0b1100", "0b1010")

	c.Eval("xor bin")
	c.AssertStack("0b110")
}
