package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_ProgIntS8_AddS8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("127")
	c.AssertStack("127")

	c.Eval("1")
	c.AssertStack("127", "1")

	c.Eval("add/s8")
	c.AssertStack("-128")

	c.Eval("info")
	c.AssertInfo("Int/s8: overflow")
}
