package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_ProgIntU8_AddU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("255 1 add/u8")
	c.AssertStack("0")

	c.Eval("info")
	c.AssertInfo("Int/u8: carry")

	c.Eval("c 127 1 add/u8")
	c.AssertStack("128")

	c.Eval("info")
	c.AssertInfo("Int/u8: overflow")
}

func TestOpDocs_ProgIntU8_IntU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x1234 int/u8 hex")
	c.AssertStack("0x34")
}

func TestOpDocs_ProgIntU8_IntU8_Negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 int/u8 hex")
	c.AssertStack("0xff")
}

func TestOpDocs_ProgIntU8_LeftRotateU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b11000000 lro/u8")
	c.AssertStack("129")

	c.Eval("bin")
	c.AssertStack("0b10000001")
}

func TestOpDocs_ProgIntU8_LeftShiftU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b11000000 lsh/u8")
	c.AssertStack("128")

	c.Eval("?")
	c.AssertInfo("Int/u8: carry")

	c.Eval("bin")
	c.AssertStack("0b10000000")

	c.Eval("?")
	c.AssertInfo("Int: carry")
}

func TestOpDocs_ProgIntU8_MaxIntU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.int/u8")
	c.AssertStack("255")
}

func TestOpDocs_ProgIntU8_MaxIntU8_Example(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2 8 pow 1 sub")
	c.AssertStack("255")
}

func TestOpDocs_ProgIntU8_NegU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x01 neg/u8 hex")
	c.AssertStack("0xff")
}

func TestOpDocs_ProgIntU8_NotU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x01 not/u8 hex")
	c.AssertStack("0xfe")
}

func TestOpDocs_ProgIntU8_RightRotateU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b11000000 lro/u8")
	c.AssertStack("129")

	c.Eval("bin")
	c.AssertStack("0b10000001")
}

func TestOpDocs_ProgIntU8_RightShiftU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0b11 rsh/u8")
	c.AssertStack("1")

	c.Eval("?")
	c.AssertInfo("Int/u8: carry")

	c.Eval("bin")
	c.AssertStack("0b1")

	c.Eval("?")
	c.AssertInfo("Int: carry")
}

func TestOpDocs_ProgIntU8_SubU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 1 sub/u8")
	c.AssertStack("255")

	c.Eval("info")
	c.AssertInfo("Int/u8: carry")

	c.Eval("c 128 1 sub/u8")
	c.AssertStack("127")

	c.Eval("info")
	c.AssertInfo("Int/u8: overflow")
}
