package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_SciComplex_AbsC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2+2i abs/c 5 round")
	c.AssertStack("2.82843")
}

func TestOpDocs_SciComplex_AcosC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5+1i acos/c 5 round")
	c.AssertStack("1.22136-0.92613i")
}

func TestOpDocs_SciComplex_AcoshC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2+2i acosh/c 5 round")
	c.AssertStack("1.73432+0.81655i")
}

func TestOpDocs_SciComplex_AsinC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5+2i asin/c 5 round")
	c.AssertStack("0.22102+1.46572i")
}

func TestOpDocs_SciComplex_AsinhC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2+2i asinh/c 5 round")
	c.AssertStack("1.73432+0.75425i")
}

func TestOpDocs_SciComplex_AtanC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5+2i atan/c 5 round")
	c.AssertStack("1.42155+0.50037i")
}

func TestOpDocs_SciComplex_AtanhC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5+2i atanh/c 5 round")
	c.AssertStack("0.09642+1.12656i")
}
