package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_SciInt_AbsI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6")
	c.AssertStack("-6")

	c.Eval("abs")
	c.AssertStack("6")
}
