package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_SciDec_AbsD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6")
	c.AssertStack("-6.6")

	c.Eval("abs/d")
	c.AssertStack("6.6")
}

func TestOpDocs_SciDec_CbrtD(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10.648")
	c.AssertStack("10.648")

	c.Eval("cbrt/d")
	c.AssertStack("2.2")
}
