package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Sci_Abs(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6 abs")
	c.AssertStack("6")

	c.Eval("c 2+2i abs 5 round")
	c.AssertStack("2.82843")
}

func TestOpDocs_Sci_Acos(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 acos 5 round")
	c.AssertStack("1.0472")
}

func TestOpDocs_Sci_Acosh(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 acosh 5 round")
	c.AssertStack("1.31696")
}

func TestOpDocs_Sci_Asin(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 asin 5 round")
	c.AssertStack("0.5236")
}

func TestOpDocs_Sci_Asinh(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 asinh 5 round")
	c.AssertStack("1.44364")
}

func TestOpDocs_Sci_Atan(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 atan 5 round")
	c.AssertStack("0.46365")
}

func TestOpDocs_Sci_Atan2(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2 atan2 5 round")
	c.AssertStack("0.46365")
}

func TestOpDocs_Sci_Atanh(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 atanh 5 round")
	c.AssertStack("0.54931")
}
