package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_SciFloat64_AbsF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6.6")
	c.AssertStack("-6.6")

	c.Eval("abs/f64")
	c.AssertStack("6.6")
}

func TestOpDocs_SciFloat64_AcosF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 acos/f64 5 round")
	c.AssertStack("1.0472")
}

func TestOpDocs_SciFloat64_AcoshF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 acosh/f64 5 round")
	c.AssertStack("1.31696")
}

func TestOpDocs_SciFloat64_AsinF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 asin/f64 5 round")
	c.AssertStack("0.5236")
}

func TestOpDocs_SciFloat64_AsinhF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 asinh/f64 5 round")
	c.AssertStack("1.44364")
}

func TestOpDocs_SciFloat64_AtanF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 atan/f64 5 round")
	c.AssertStack("0.46365")
}

func TestOpDocs_SciFloat64_AtanhF64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0.5 atanh/f64 5 round")
	c.AssertStack("0.54931")
}
