package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Stack_Tuck(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2")
	c.AssertStack("1", "2")

	c.Eval("tuck")
	c.AssertStack("2", "1", "2")

	c.Eval("add")
	c.AssertStack("2", "3")

	c.Eval("tuck add")
	c.AssertStack("3", "5")

	c.Eval("tuck add")
	c.AssertStack("5", "8")
}
