package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Stack_Clear(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2 3")
	c.AssertStack("1", "2", "3")

	c.Eval("c")
	c.AssertStack()
}
