package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Stat_Factorial(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 3 fact")
	c.AssertStack("6")

	c.Eval("c 10 fact")
	c.AssertStack("3628800")
}
