package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_TypesIntU64_MaxValU64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.val/u64")
	c.AssertStack("18446744073709551615")
}

func TestOpDocs_TypesIntU64_MaxValU64_Example(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2 64 pow 1 sub")
	c.AssertStack("18446744073709551615")
}
