package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_TypesIntU8_MaxValU8(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.val/u8")
	c.AssertStack("255")
}

func TestOpDocs_TypesIntU8_MaxValU8_Example(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2 8 pow 1 sub")
	c.AssertStack("255")
}
