package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_TypesIntU32_MaxU32(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.u32")
	c.AssertStack("4294967295")
}

func TestOpDocs_TypesIntU32_MaxU32_Example(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2 32 pow 1 sub")
	c.AssertStack("4294967295")
}
