package zcalc

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	Clear = zc.Op{
		Name: "clear",
		Aliases: []string{
			"c",
		},
		Params:   []string{},
		VarParam: "Val",
		Returns:  []string{},
		Func:     clear,
	}
	Down = zc.Op{
		Name: "down",
		Aliases: []string{
			"dn",
		},
		Params:    []string{},
		VarParam:  "Val",
		Returns:   []string{},
		VarReturn: "Val",
		Func:      down,
	}
	Dup = zc.Op{
		Name:    "dup",
		Aliases: []string{},
		Params:  []string{kinds.Val},
		Returns: []string{kinds.Val, kinds.Val},
		Func:    dup,
	}
)
