package zcalc

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	Down = zc.Op{
		Name: "down",
		Aliases: []string{
			"dn",
		},
		Params:     []string{kinds.Val},
		VarParams:  true,
		Returns:    []string{kinds.Val},
		VarReturns: true,
		Func:       down,
	}
	Dup = zc.Op{
		Name:    "dup",
		Aliases: []string{},
		Params:  []string{kinds.Val},
		Returns: []string{kinds.Val, kinds.Val},
		Func:    dup,
	}
)
