package zcalc

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Volume = zc.Vol{
	Name:  "zcalc",
	Kinds: []zc.Kind{},
	Ops: []zc.Op{
		Down,
		Dup,
	},
}
