import assert

func test-and
    t t and
    assert.true
    f t and
    assert.false
    f f and
    assert.false

func test-eq
    1 1 eq
    assert.true
    1 2 eq
    assert.false

func test-eq-int
    1234 '1,234' eq
    assert.true

func test-gt
    1 0 gt
    assert.true
    0 0 gt
    assert.false
    -1 0 gt
    assert.false

func test-gte
    1 0 gte
    assert.true
    0 0 gte
    assert.true
    -1 0 gte
    assert.false

func test-lt
    1 0 lt
    assert.false
    0 0 lt
    assert.false
    -1 0 lt
    assert.true

func test-lte
    1 0 lte
    assert.false
    0 0 lte
    assert.true
    -1 0 lte
    assert.true

func test-neq
    1 1 neq
    assert.false
    1 2 neq
    assert.true

func test-or
    t t or
    assert.true
    t f or
    assert.true
    f f or
    assert.false