import test

func test-and
    t t and
    true test.eq
    f t and
    false test.eq
    f f and
    false test.eq

func test-eq
    1 1 eq
    true test.eq
    1 2 eq
    false test.eq

func test-eq-int
    1234 '1,234' eq
    true test.eq

func test-gt
    1 0 gt
    true test.eq
    0 0 gt
    false test.eq
    -1 0 gt
    false test.eq

func test-gte
    1 0 gte
    true test.eq
    0 0 gte
    true test.eq
    -1 0 gte
    false test.eq

func test-lt
    1 0 lt
    false test.eq
    0 0 lt
    false test.eq
    -1 0 lt
    true test.eq

func test-lte
    1 0 lte
    false test.eq
    0 0 lte
    true test.eq
    -1 0 lte
    true test.eq

func test-neq
    1 1 neq
    false test.eq
    1 2 neq
    true test.eq

func test-or
    t t or
    true test.eq
    t f or
    true test.eq
    f f or
    false test.eq