import assert

func test-add
	6 2 add
	8 assert.eq

func test-a
	6 2 a
	8 assert.eq

func test-+
	6 2 +
	8 assert.eq

func test-add-dec
	6.6 2.2 add
	8.8 assert.eq

func test-add-hex
	0x11 0x22 add
	0x33 assert.eq

func test-add-oct
	0o11 0o22 add
	0o33 assert.eq

func test-add-bin
	0b1 0b01 add
	0b10 assert.eq

func test-div
	6 2 div
	3 assert.eq

func test-d
	6 2 d
	3 assert.eq

func test-/
	6 2 /
	3 assert.eq

func test-div-dec
	6.6 2.2 div
	3 assert.eq

func test-div-repeat
	1 3 div
	0.3333333333333333 assert.eq

func test-mul
	6 2 mul
	12 assert.eq

func test-m
	6 2 m
	12 assert.eq

func test-*
	6 2 *
	12 assert.eq

func test-mul-dec
	6.6 2.2 mul
	14.52 assert.eq

func test-round
	2 3 div 2 round
	0.67 assert.eq

func test-sub
	6 2 sub
	4 assert.eq

func test-s
	6 2 s
	4 assert.eq

func test--
	6 2 -
	4 assert.eq

func test-sub-dec
	6.6 2.2 sub
	4.4 assert.eq

func test-sum
	1 2 3 4 sum
	10 assert.eq
