import test

func test-left
	0 test.sub
	'abcd' 0 str.left
	'abcd' test.eq

	4 test.sub
	'abcd' 4 str.left
	'abcd' test.eq

	-4 test.sub
	'abcd' -4 str.left
	'' test.eq

	5 test.sub
	try 'abcd' 5 str.left
	test.false clear

	-5 test.sub
	try 'abcd' 5 str.left
	test.false clear


func test-len
	'abcd' str.len
	4 test.eq
	'' str.len
	0 test.eq


func test-right
	0 test.sub
	'abcd' 0 str.right
	'abcd' test.eq

	4 test.sub
	'abcd' 4 str.right
	'abcd' test.eq

	-4 test.sub
	'abcd' -4 str.right
	'' test.eq

	5 test.sub
	try 'abcd' 5 str.right
	test.false clear

	-5 test.sub
	try 'abcd' 5 str.right
	test.false clear


func test-starts-with
	'foobar' 'foo' str.starts-with
	'true' test.eq
	'foobar' 'bar' str.starts-with
	'false' test.eq
