use assert
use time
use io

'America/Denver' local
'Mon Jan 2 2006 3:04:05PM UTC +0000' travel

func test-formats
    formats; formats=
    expected; [
        'Jan 2 2006 3:04PM'      'Mon Jan 2 2006 3:04:00PM MST -0700'
    ]
    for format; //formats
        expect; //expected /format dict.get
        if /expect not-found eq
            'Mon Jan 2 2006 3:04:05PM MST -0700'
        else
            /expect
        'checking `format`' io.println
        /format dt assert.eq
