package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicComplex_AddC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6+6i 2+2i add/c")
	c.AssertStack("8+8i")
}

func TestOpDocs_BasicComplex_DivC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 12+12i 4+12i div/c")
	c.AssertStack("1.2-0.6i")
}

func TestOpDocs_BasicComplex_MulC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2+3i 4+4i mul/c")
	c.AssertStack("-4+20i")
}

func TestOpDocs_BasicComplex_NegC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6")
	c.AssertStack("-6")

	c.Eval("neg")
	c.AssertStack("6")

	c.Eval("neg")
	c.AssertStack("-6")
}

func TestOpDocs_BasicComplex_NegC_Complex(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -6+6i neg")
	c.AssertStack("6-6i")

	c.Eval("c 6-6i neg")
	c.AssertStack("-6+6i")
}

func TestOpDocs_BasicComplex_SqrtC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-4 sqrt/c")
	c.AssertStack("0+2i")
}

func TestOpDocs_BasicComplex_SubC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6+6i 2+2i sub")
	c.AssertStack("4+4i")
}
