package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_BasicIntU64_AddU64(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("18446744073709551615 1 add/u64")
	c.AssertStack("0")
}
