package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_SciFloat64_CbrtF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10.648")
	c.AssertStack("10.648")

	c.Eval("cbrt/f")
	c.AssertStack("2.2")
}

func TestOpDocs_SciFloat64_ExpF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 exp 5 round")
	c.AssertStack("7.38906")
}

func TestOpDocs_SciFloat64_Log10F(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("50 log10 5 round")
	c.AssertStack("1.69897")
}
