package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Types_Types(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2")
	c.AssertStack("1", "2")

	c.Eval("types")
	c.AssertStack("1 :Text", "2 :Text")

	c.Eval("add types")
	c.AssertStack("3 :Int")
}
