package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_TypesIntU16_MaxU16(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.u16")
	c.AssertStack("65535")
}

func TestOpDocs_TypesIntU16_MaxU16_Example(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2 16 pow 1 sub")
	c.AssertStack("65535")
}
