package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_TypesIntU_MaxU(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("max.u 1 add/u")
	c.AssertStack("0")
}
