package basic

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	Add = zc.Op{
		Name: "add",
		Aliases: []string{
			"a",
			"+",
		},
	}
	Sub = zc.Op{
		Name: "sub",
		Aliases: []string{
			"s",
			"-",
		},
	}
)
