package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_BasicInt_AddI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6")
	ct.AssertStack("6")

	ct.Eval("2")
	ct.AssertStack("6", "2")

	ct.Eval("add/i")
	ct.AssertStack("8")
}

func TestOpDocs_BasicInt_DivI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6")
	ct.AssertStack("6")

	ct.Eval("2")
	ct.AssertStack("6", "2")

	ct.Eval("div/i")
	ct.AssertStack("3")
}

func TestOpDocs_BasicInt_DivI_Zero(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6 0 div/i")
	ct.AssertError("div/i: division by zero")
}

func TestOpDocs_BasicInt_ModI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("-7")
	ct.AssertStack("-7")

	ct.Eval("2")
	ct.AssertStack("-7", "2")

	ct.Eval("mod/i")
	ct.AssertStack("1")
}

func TestOpDocs_BasicInt_ModI_Zero(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6 0 mod/i")
	ct.AssertError("mod/i: division by zero")
}

func TestOpDocs_BasicInt_MulI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6")
	ct.AssertStack("6")

	ct.Eval("2")
	ct.AssertStack("6", "2")

	ct.Eval("mul/i")
	ct.AssertStack("12")
}

func TestOpDocs_BasicInt_NegI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("-6")
	ct.AssertStack("-6")

	ct.Eval("neg/i")
	ct.AssertStack("6")

	ct.Eval("neg/i")
	ct.AssertStack("-6")
}

func TestOpDocs_BasicInt_PowI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6")
	ct.AssertStack("6")

	ct.Eval("2")
	ct.AssertStack("6", "2")

	ct.Eval("pow/i")
	ct.AssertStack("36")
}

func TestOpDocs_BasicInt_RemI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("-7")
	ct.AssertStack("-7")

	ct.Eval("2")
	ct.AssertStack("-7", "2")

	ct.Eval("rem/i")
	ct.AssertStack("-1")
}

func TestOpDocs_BasicInt_SignI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("c -6 sign/i")
	ct.AssertStack("-1")

	ct.Eval("c 6 sign/i")
	ct.AssertStack("1")

	ct.Eval("c 0 sign/i")
	ct.AssertStack("0")
}

func TestOpDocs_BasicInt_SqrtI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("65536")
	ct.AssertStack("65536")

	ct.Eval("sqrt/i")
	ct.AssertStack("256")
}

func TestOpDocs_BasicInt_SqrtI_Zero(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("0 sqrt/i")
	ct.AssertStack("0")
}

func TestOpDocs_BasicInt_SqrtI_Neg(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("-1 sqrt/i")
	ct.AssertError("sqrt/i: invalid argument, -1 < 0")
}

func TestOpDocs_BasicInt_SubI(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6")
	ct.AssertStack("6")

	ct.Eval("2")
	ct.AssertStack("6", "2")

	ct.Eval("sub/i")
	ct.AssertStack("4")
}
