package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_BasicFloat_AddF(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1.1")
	ct.AssertStack("1.1")

	ct.Eval("2.2")
	ct.AssertStack("1.1", "2.2")

	ct.Eval("add/f")
	ct.AssertStack("3.3000000000000000002")
}

func TestOpDocs_BasicFloat_DivF(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("2")
	ct.AssertStack("2")

	ct.Eval("3")
	ct.AssertStack("2", "3")

	ct.Eval("div/f")
	ct.AssertStack("0.6666666666666666667")
}
