package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_BasicInt_AddI(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.AssertStack(t, c, "6")

	c.Eval("2")
	zc.AssertStack(t, c, "6", "2")

	c.Eval("add/i")
	zc.AssertStack(t, c, "8")
}

func TestOpDocs_BasicInt_DivI(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.AssertStack(t, c, "6")

	c.Eval("2")
	zc.AssertStack(t, c, "6", "2")

	c.Eval("div/i")
	zc.AssertStack(t, c, "3")
}

func TestOpDocs_BasicInt_DivI_Zero(t *testing.T) {
	c := calc.New()

	c.Eval("6 0 div/i")
	zc.AssertError(t, c, "div/i: division by zero")
}

func TestOpDocs_BasicInt_ModI(t *testing.T) {
	c := calc.New()

	c.Eval("-7")
	zc.AssertStack(t, c, "-7")

	c.Eval("2")
	zc.AssertStack(t, c, "-7", "2")

	c.Eval("mod/i")
	zc.AssertStack(t, c, "1")
}

func TestOpDocs_BasicInt_ModI_Zero(t *testing.T) {
	c := calc.New()

	c.Eval("6 0 mod/i")
	zc.AssertError(t, c, "mod/i: division by zero")
}

func TestOpDocs_BasicInt_MulI(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.AssertStack(t, c, "6")

	c.Eval("2")
	zc.AssertStack(t, c, "6", "2")

	c.Eval("mul/i")
	zc.AssertStack(t, c, "12")
}

func TestOpDocs_BasicInt_NegI(t *testing.T) {
	c := calc.New()

	c.Eval("-6")
	zc.AssertStack(t, c, "-6")

	c.Eval("neg/i")
	zc.AssertStack(t, c, "6")

	c.Eval("neg/i")
	zc.AssertStack(t, c, "-6")
}

func TestOpDocs_BasicInt_PowI(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.AssertStack(t, c, "6")

	c.Eval("2")
	zc.AssertStack(t, c, "6", "2")

	c.Eval("pow/i")
	zc.AssertStack(t, c, "36")
}

func TestOpDocs_BasicInt_RemI(t *testing.T) {
	c := calc.New()

	c.Eval("-7")
	zc.AssertStack(t, c, "-7")

	c.Eval("2")
	zc.AssertStack(t, c, "-7", "2")

	c.Eval("rem/i")
	zc.AssertStack(t, c, "-1")
}

func TestOpDocs_BasicInt_SignI(t *testing.T) {
	c := calc.New()

	c.Eval("c -6 sign/i")
	zc.AssertStack(t, c, "-1")

	c.Eval("c 6 sign/i")
	zc.AssertStack(t, c, "1")

	c.Eval("c 0 sign/i")
	zc.AssertStack(t, c, "0")
}

func TestOpDocs_BasicInt_SqrtI(t *testing.T) {
	c := calc.New()

	c.Eval("65536")
	zc.AssertStack(t, c, "65536")

	c.Eval("sqrt/i")
	zc.AssertStack(t, c, "256")
}

func TestOpDocs_BasicInt_SqrtI_Zero(t *testing.T) {
	c := calc.New()

	c.Eval("0 sqrt/i")
	zc.AssertStack(t, c, "0")
}

func TestOpDocs_BasicInt_SqrtI_Neg(t *testing.T) {
	c := calc.New()

	c.Eval("-1 sqrt/i")
	zc.AssertError(t, c, "sqrt/i: invalid argument, -1 < 0")
}

func TestOpDocs_BasicInt_SubI(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.AssertStack(t, c, "6")

	c.Eval("2")
	zc.AssertStack(t, c, "6", "2")

	c.Eval("sub/i")
	zc.AssertStack(t, c, "4")
}
