package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_BasicDec_AddD(t *testing.T) {
	c := calc.New()

	c.Eval("6.6")
	zc.AssertStack(t, c, "6.6")

	c.Eval("2.2")
	zc.AssertStack(t, c, "6.6", "2.2")

	c.Eval("add/d")
	zc.AssertStack(t, c, "8.8")
}

func TestOpDocs_BasicDec_DivD(t *testing.T) {
	c := calc.New()

	c.Eval("6.6")
	zc.AssertStack(t, c, "6.6")

	c.Eval("2")
	zc.AssertStack(t, c, "6.6", "2")

	c.Eval("div/d")
	zc.AssertStack(t, c, "3.3")
}

func TestOpDocs_BasicDec_DivD_Thirds(t *testing.T) {
	c := calc.New()

	c.Eval("2 3 div/d")
	zc.AssertStack(t, c, "0.6666666666666667")
}

func TestOpDocs_BasicDec_DivD_Zero(t *testing.T) {
	c := calc.New()

	c.Eval("6.6 0 div/d")
	zc.AssertError(t, c, "div/d: division by zero")
}

func TestOpDocs_BasicDec_MulD(t *testing.T) {
	c := calc.New()

	c.Eval("6.6")
	zc.AssertStack(t, c, "6.6")

	c.Eval("2.2")
	zc.AssertStack(t, c, "6.6", "2.2")

	c.Eval("mul/d")
	zc.AssertStack(t, c, "14.52")
}

func TestOpDocs_BasicDec_NegD(t *testing.T) {
	c := calc.New()

	c.Eval("-6.6")
	zc.AssertStack(t, c, "-6.6")

	c.Eval("neg/d")
	zc.AssertStack(t, c, "6.6")

	c.Eval("neg/d")
	zc.AssertStack(t, c, "-6.6")
}
