package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_Conf_FloatPrecSet(t *testing.T) {
	c := calc.New()

	c.Eval("float.prec?")
	zc.AssertStack(t, c, "64 # precision")

	c.Eval("c 2 3 div/f")
	zc.AssertStack(t, c, "0.6666666666666666667")

	c.Eval("c 92 float.prec=")
	zc.AssertInfo(t, c, "precision set to 92")

	c.Eval("c 2 3 div/f")
	zc.AssertStack(t, c, "0.6666666666666666666666666667")
}
