package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocsFloatsAddFloat64(t *testing.T) {
	c := calc.New()

	c.Eval("1.1")
	zc.AssertStack(t, c, "1.1")

	c.Eval("2.2")
	zc.AssertStack(t, c, "1.1", "2.2")

	c.Eval("a")
	zc.AssertStack(t, c, "3.3000000000000000002")
}
