package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
	"testing"
)

func TestFloatsAdd(t *testing.T) {
	c := calc.New()

	c.Eval("1.1")
	zc.TestCalc(t, c, "1.1")

	c.Eval("2.2")
	zc.TestCalc(t, c, "1.1", "2.2")

	c.Eval("a")
	zc.TestCalc(t, c, "3.3001")
}
