package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_Format_Round(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("200000 3 div")
	ct.AssertStack("66666.66666666667")

	ct.Eval("3 round/d")
	ct.AssertStack("66666.667")

	ct.Eval("0 round/d")
	ct.AssertStack("66667")

	ct.Eval("-3 round/d")
	ct.AssertStack("67000")
}

func TestOpDocs_Format_ScientificNotation(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("123 sn")
	ct.AssertStack("1.23e2")
}
