package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocsIntsAddIntArch(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.AssertStack(t, c, "6")

	c.Eval("2")
	zc.AssertStack(t, c, "6", "2")

	c.Eval("a")
	zc.AssertStack(t, c, "8")
}

func TestOpDocsIntsInt8(t *testing.T) {
	c := calc.New()

	c.Eval("c 127 int8")
	zc.AssertStack(t, c, "127")

	c.Eval("c 128 int8")
	zc.AssertStack(t, c, "-128")
}
