package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
	"testing"
)

func TestIntsAddIntarch(t *testing.T) {
	c := calc.New()

	c.Eval("6")
	zc.TestCalc(t, c, "6")

	c.Eval("2")
	zc.TestCalc(t, c, "6", "2")

	c.Eval("a")
	zc.TestCalc(t, c, "8")
}
