package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_Stack_Clear(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1 2 3")
	ct.AssertStack("1", "2", "3")

	ct.Eval("c")
	ct.AssertStack()
}

func TestOpDocs_Stack_Down(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1 2 3")
	ct.AssertStack("1", "2", "3")

	ct.Eval("down")
	ct.AssertStack("3", "1", "2")
}

func TestOpDocs_Stack_Drop(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1 2 3")
	ct.AssertStack("1", "2", "3")

	ct.Eval("drop")
	ct.AssertStack("1", "2")
}

func TestOpDocs_Stack_Dup(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("10")
	ct.AssertStack("10")

	ct.Eval("dup")
	ct.AssertStack("10", "10")
}

func TestOpDocs_Stack_Up(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1 2 3")
	ct.AssertStack("1", "2", "3")

	ct.Eval("up")
	ct.AssertStack("2", "3", "1")
}
