package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_Stat_Fact(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("c 10 fact")
	ct.AssertStack("3628800")
}
