package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocsZcalcClear(t *testing.T) {
	c := calc.New()

	c.Eval("1 2 3")
	zc.AssertStack(t, c, "1", "2", "3")

	c.Eval("c")
	zc.AssertStack(t, c)
}

func TestOpDocsZcalcDown(t *testing.T) {
	c := calc.New()

	c.Eval("1 2 3")
	zc.AssertStack(t, c, "1", "2", "3")

	c.Eval("down")
	zc.AssertStack(t, c, "3", "1", "2")
}

func TestOpDocsZcalcDup(t *testing.T) {
	c := calc.New()

	c.Eval("10")
	zc.AssertStack(t, c, "10")

	c.Eval("dup")
	zc.AssertStack(t, c, "10", "10")
}
