package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
	"testing"
)

func TestZcalcDown(t *testing.T) {
	c := calc.New()

	c.Eval("1 2 3")
	zc.TestCalc(t, c, "1", "2", "3")

	c.Eval("down")
	zc.TestCalc(t, c, "3", "1", "2")
}

func TestZcalcDup(t *testing.T) {
	c := calc.New()

	c.Eval("10")
	zc.TestCalc(t, c, "10")

	c.Eval("dup")
	zc.TestCalc(t, c, "10", "10")
}
