//go:generate go run gen-about.go

package main

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"strings"
	"time"
)

const AboutGo = "../../about.go"

func main() {
	out, err := os.Create(AboutGo)
	if err != nil {
		log.Fatal(err)
	}

	o, err := exec.Command("git", "rev-parse", "--short", "HEAD").Output()
	if err != nil {
		log.Fatal(err)
	}
	hash := strings.TrimSpace(string(o))

	o, err = exec.Command("git", "describe", "--tag", "--abbrev=0").Output()
	if err != nil {
		log.Fatal(err)
	}
	version := strings.TrimSpace(string(o))
	buildDate := time.Now().Format("2 Jan 2006")

	fmt.Fprintf(out, "// Code generated by 'gen-about'; DO NOT EDIT.\n\n")
	fmt.Fprintf(out, "package zc\n\n")
	fmt.Fprintf(out, "const (\n")
	fmt.Fprintf(out, "\tProgName = \"zc\"\n")
	fmt.Fprintf(out, "\tVersion = \"%v\"\n", version)
	fmt.Fprintf(out, "\tBuildDate = \"%v\"\n", buildDate)
	fmt.Fprintf(out, "\tCommit = \"%v\"\n", hash)
	fmt.Fprintf(out, ")")
}
