package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/types"
)

var Basic = zc.Vol{
	Name: "basic",
	Types: []zc.Type{
		types.Int,
		types.Int32,
		types.Dec,
		types.Float,
		types.Text,
	},
	Ops: []zc.Op{},
	Macros: []zc.Macro{
		{Name: "a", Expr: "add"},
		{Name: "+", Expr: "add"},
	},
}
