package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/ops"
)

var BasicFloat = zc.Vol{
	Name: "basic/Float",
	Ops: []zc.Op{
		ops.AddBigFloat,
		ops.DivBigFloat,
	},
	Macros: []zc.Macro{},
}
