package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/types"
)

var Basic = zc.Vol{
	Name: "basic",
	Types: []zc.Type{
		types.Int,
		types.Int32,
		types.Dec,
		types.Float,
		types.Text,
	},
	Ops: []zc.Op{},
	Macros: []zc.Macro{
		{Name: "a", Expr: "add"},
		{Name: "+", Expr: "add"},
		{Name: "cube", Expr: "dup dup mul mul"},
		{Name: "cb", Expr: "cube"},
		{Name: "cbrt", Expr: "cube.root"},
		{Name: "d", Expr: "div"},
		{Name: "/", Expr: "div"},
		{Name: "square", Expr: "dup mul"},
		{Name: "sq", Expr: "square"},
		{Name: "sqrt", Expr: "square.root"},
	},
}
