package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/ops"
)

var BasicInt = zc.Vol{
	Name: "basic/Int",
	Ops: []zc.Op{
		ops.AddBigInt,
		ops.DivBigInt,
		ops.ModBigInt,
		ops.MulBigInt,
		ops.NegBigInt,
		ops.PowBigInt,
		ops.RemBigInt,
		ops.SignBigInt,
		ops.SqrtBigInt,
		ops.SubBigInt,
	},
	Macros: []zc.Macro{},
}
