package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/ops"
)

var FormatDec = zc.Vol{
	Name: "format/Dec",
	Ops: []zc.Op{
		ops.RoundDecimal,
		ops.ScientificNotationDecimal,
	},
	Macros: []zc.Macro{},
}
