package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_BasicDecSS_AddDSs(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("add/d/ss")
	ct.AssertStack("8.8")
}

func TestOpDocs_BasicDecSS_DivDSs(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2")
	ct.AssertStack("6.6", "2")

	ct.Eval("div/d/ss")
	ct.AssertStack("3.3")
}

func TestOpDocs_BasicDecSS_DivDSs_Thirds(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("2 3 div/d/ss")
	ct.AssertStack("0.6666666666666667")
}

func TestOpDocs_BasicDecSS_DivDSs_Zero(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6 0 div/d/ss")
	ct.AssertError("div/d/ss: division by zero")
}

func TestOpDocs_BasicDecSS_MulDSs(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("mul/d/ss")
	ct.AssertStack("14.52")
}

func TestOpDocs_BasicDecSS_NegDSs(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("-6.6")
	ct.AssertStack("-6.6")

	ct.Eval("neg/d/ss")
	ct.AssertStack("6.6")

	ct.Eval("neg/d/ss")
	ct.AssertStack("-6.6")
}

func TestOpDocs_BasicDecSS_SubDSs(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("sub/d/ss")
	ct.AssertStack("4.4")
}
