package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_Conf_FloatPrecSet(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("float.prec?")
	ct.AssertStack("64 # precision")

	ct.Eval("c 2 3 div/f")
	ct.AssertStack("0.6666666666666666667")

	ct.Eval("c 92 float.prec=")
	ct.AssertInfo("precision set to 92")

	ct.Eval("c 2 3 div/f")
	ct.AssertStack("0.6666666666666666666666666667")
}

func TestOpDocs_Conf_FloatPrecGet(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("float.prec?")
	ct.AssertStack("64 # precision")
}

func TestOpDocs_Conf_RoundingModeSet(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("rounding.mode?")
	ct.AssertStack("half.even")

	ct.Eval("c 5.55 1 round")
	ct.AssertStack("5.6")

	ct.Eval("/down rounding.mode=")
	ct.AssertInfo("rounding mode set to down")

	ct.Eval("c 5.55 1 round")
	ct.AssertStack("5.5")
}

func TestOpDocs_Conf_RoundingModeGet(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("rounding.mode?")
	ct.AssertStack("half.even")
}
