package intb

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	AddInt = zc.Op{
		Name:      "add.int",
		Overloads: "add",
		Aliases: []string{
			"addi",
		},
		Params:  []string{kinds.Int, kinds.Int},
		Returns: []string{kinds.Int},
		Prec:    kinds.PrecInt,
		Func:    add,
	}
	PowInt = zc.Op{
		Name:      "pow.int",
		Overloads: "pow",
		Aliases: []string{
			"powi",
		},
		Params:  []string{kinds.Int, kinds.Int},
		Returns: []string{kinds.Int},
		Prec:    kinds.PrecInt,
		Func:    pow,
	}
	SubInt = zc.Op{
		Name:      "sub.int",
		Overloads: "sub",
		Aliases: []string{
			"subi",
		},
		Params:  []string{kinds.Int, kinds.Int},
		Returns: []string{kinds.Int},
		Prec:    kinds.PrecInt,
		Func:    sub,
	}
)
