// Code generated by 'gen-ops'; DO NOT EDIT
package intb

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	Add = zc.Op{
		Name: "add",
		Aliases: []string{
			"add.int",
			"addi",
			"+",
		},
		Params:  []string{kinds.Int, kinds.Int},
		Returns: []string{kinds.Int},
		Prec:    kinds.PrecInt,
		Func:    add,
	}
	Sub = zc.Op{
		Name: "sub",
		Aliases: []string{
			"sub.int",
			"subi",
			"-",
		},
		Params:  []string{kinds.Int, kinds.Int},
		Returns: []string{kinds.Int},
		Func:    sub,
	}
)
