package intb

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Volume = zc.Vol{
	Name: "int",
	Kinds: []zc.Kind{
		IntKind,
	},
	Ops: []zc.Op{
		Add,
		Sub,
	},
}
