import assert

6 2 add
8 assert.eq

6 2 a
8 assert.eq

6 2 +
8 assert.eq

6.6 2.2 add
8.8 assert.eq

6 2 div
3 assert.eq

6 2 d
3 assert.eq

6 2 /
3 assert.eq

6.6 2.2 div
3 assert.eq

1 3 div
0.3333333333333333 assert.eq

6 2 mul
12 assert.eq

6 2 m
12 assert.eq

6 2 *
12 assert.eq

6.6 2.2 mul
14.52 assert.eq

2 3 div 2 round
0.67 assert.eq

6 2 sub
4 assert.eq

6 2 s
4 assert.eq

6 2 -
4 assert.eq

6.6 2.2 sub
4.4 assert.eq

6 inc
7 assert.eq

6 dec
5 assert.eq

