name: stack
title: Stack operations
category: calc

ops:
- name: clear
  aliases: [c]
  title: Clear
  funcs:
  - name: Clear
    params: [Any*]
  desc: |-
    Clears all items from the stack.
  example:
  - i: 1 2 3
    o: [1, 2, 3]
  - i: c
    o: []

- name: dup
  title: Duplicate
  funcs:
  - name: DupBigInt
    params: [x:Int]
    returns: [x:Int, x:Int]
  - name: DupDecimal
    params: [x:Dec]
    returns: [x:Dec, x:Dec]
  desc: Duplicates the top value on the stack
  example:
  - i: 10
    o: [10]
  - i: dup
    o: [10, 10]

- name: tuck
  title: Copy top and place below
  funcs:
  - name: TuckBigInt
    params: [x:Any, y:Int]
    returns: [y:Int, x:Any, y:Int]
  - name: TuckDecimal
    params: [x:Any, y:Dec]
    returns: [y:Dec, x:Any, y:Dec]
  desc: |-
    Duplicates the top item on the stack, *y*, and places it below *x*.

    This operation can be useful for a calculation when accumulating a value
    which would otherwise be consumed by another operation. The example
    below shows using `tuck` to calculate fibonacci numbers.
  example:
  - i: 1 2
    o: [1, 2]
  - i: tuck
    o: [2, 1, 2]
  - i: add
    o: [2, 3]
  - i: tuck add
    o: [3, 5]
  - i: tuck add
    o: [5, 8]
  tests:
  - name: Decimal
    test:
    - i: 1.1 2.2 tuck
      o: [2.2, 1.1, 2.2]