name: stack
title: Stack operations
category: calc

ops:
- name: clear
  aliases: [c]
  title: Clear
  funcs:
  - name: Clear
    params: [Any*]
  desc: |-
    Clears all items from the stack.
  example:
  - i: 1 2 3
    o: [1, 2, 3]
  - i: c
    o: []

- name: dup
  title: Duplicate
  funcs:
  - name: Dup
    params: [x:Any]
    returns: [x:Any, x:Any]
  desc: Duplicates the top value on the stack
  example:
  - i: 10
    o: [10]
  - i: dup
    o: [10, 10]
