package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_Basic_Add(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("c 6 2 a")
	ct.AssertStack("8")

	ct.Eval("c 1.1 2.2 a")
	ct.AssertStack("3.3")
}

func TestOpDocs_Basic_Mul(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("c 6 2 mul")
	ct.AssertStack("12")

	ct.Eval("c 6.6 2.2 mul")
	ct.AssertStack("14.52")
}
