package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc"
)

func TestOpDocs_BasicDec_AddD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("add/d")
	ct.AssertStack("8.8")
}

func TestOpDocs_BasicDec_CubeRootD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1.25 cube")
	ct.AssertStack("1.953125")

	ct.Eval("cbrt")
	ct.AssertStack("1.25")
}

func TestOpDocs_BasicDec_DivD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2")
	ct.AssertStack("6.6", "2")

	ct.Eval("div/d")
	ct.AssertStack("3.3")
}

func TestOpDocs_BasicDec_DivD_Thirds(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("2 3 div/d")
	ct.AssertStack("0.6666666666666667")
}

func TestOpDocs_BasicDec_DivD_Zero(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6 0 div/d")
	ct.AssertError("div/d: division by zero")
}

func TestOpDocs_BasicDec_MulD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("mul/d")
	ct.AssertStack("14.52")
}

func TestOpDocs_BasicDec_NegD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("-6.6")
	ct.AssertStack("-6.6")

	ct.Eval("neg/d")
	ct.AssertStack("6.6")

	ct.Eval("neg/d")
	ct.AssertStack("-6.6")
}

func TestOpDocs_BasicDec_PowD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("pow/d")
	ct.AssertStack("63.53260431279859")
}

func TestOpDocs_BasicDec_RemD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.75")
	ct.AssertStack("6.75")

	ct.Eval("0.5")
	ct.AssertStack("6.75", "0.5")

	ct.Eval("rem")
	ct.AssertStack("0.25")
}

func TestOpDocs_BasicDec_SquareRootD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("1.25 sq")
	ct.AssertStack("1.5625")

	ct.Eval("sqrt")
	ct.AssertStack("1.25")
}

func TestOpDocs_BasicDec_SubD(t *testing.T) {
	c := calc.New()
	ct := zc.NewCalcTester(c, t)

	ct.Eval("6.6")
	ct.AssertStack("6.6")

	ct.Eval("2.2")
	ct.AssertStack("6.6", "2.2")

	ct.Eval("sub/d")
	ct.AssertStack("4.4")
}
