package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/funcs"
	"github.com/blackchip-org/zc/v6/calc/types"
)

var (
	RoundDecimal = zc.Op{
		Name:      "round/d",
		Overloads: "round",
		Params:    []zc.Type{types.Dec, types.Int32},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.RoundDecimal,
	}
	ScientificNotationDecimal = zc.Op{
		Name:      "scientific.notation/d",
		Overloads: "scientific.notation",
		Params:    []zc.Type{types.Dec},
		Returns:   []zc.Type{types.Text},
		Func:      funcs.ScientificNotationDecimal,
	}
)
