//go:generate go run gen-entity.go

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

var ignore = map[string]struct{}{
	"&ApplyFunction;":         {},
	"&InvisibleComma;":        {},
	"&InvisibleTimes;":        {},
	"&NewLine;":               {},
	"&MediumSpace;":           {},
	"&NegativeMediumSpace;":   {},
	"&NegativeThickSpace;":    {},
	"&NegativeThinSpace;":     {},
	"&NegativeVeryThinSpace;": {},
	"&NoBreak;":               {},
	"&NonBreakingSpace;":      {},
	"&Tab;":                   {},
	"&ThickSpace;":            {},
	"&ThinSpace;":             {},
	"&VerticalLine;":          {},
	"&VeryThinSpace;":         {},
	"&ZeroWidthSpace;":        {},
	"&af;":                    {},
	"&emsp13;":                {},
	"&emsp14;":                {},
	"&emsp;":                  {},
	"&ensp;":                  {},
	"&hairsp;":                {},
	"&ic;":                    {},
	"&it;":                    {},
	"&lrm;":                   {},
	"&nbsp;":                  {},
	"&numsp;":                 {},
	"&puncsp;":                {},
	"&rlm;":                   {},
	"&shy;":                   {},
	"&thinsp;":                {},
	"&verbar;":                {},
	"&vert;":                  {},
	"&zwj;":                   {},
	"&zwnj;":                  {},
}

const (
	EntityYaml = "../../app/defs/entity.yaml"
)

type Entity struct {
	Codepoints []int  `json:"codepoints"`
	Characters string `json:"characters"`
}

func main() {
	var names []string
	entities := make(map[string]Entity)
	data, err := os.ReadFile("entities.json")
	if err != nil {
		panic(err)
	}
	json.Unmarshal(data, &entities)

	for name := range entities {
		if _, ok := ignore[name]; ok {
			continue
		}
		if !strings.HasSuffix(name, ";") {
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names)

	fent, err := os.Create(EntityYaml)
	if err != nil {
		panic(err)
	}
	defer fent.Close()

	fmt.Fprintf(fent, "# File generated by 'gen-entity'; DO NOT EDIT.\n\n")
	fmt.Fprintf(fent, "name: entity\n")
	fmt.Fprintf(fent, "title: HTML entity characters\n")
	fmt.Fprintf(fent, "category: tab\n")
	fmt.Fprintf(fent, "no-index: true\n\n")
	fmt.Fprintf(fent, "table:\n")

	for _, name := range names {
		entity := entities[name]
		if entity.Characters == `"` {
			entity.Characters = `\\\"`
		}
		if entity.Characters == `\` {
			entity.Characters = `\\\\`
		}
		fmt.Fprintf(fent, "- [\"%v\", \"/%v\"]\n", name, entity.Characters)
	}
}
