package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Angle_DecAngle(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10d7m24.24s dec")
	c.AssertStack("10.1234")
}

func TestOpDocs_Angle_DegRad(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("90 deg-rad 7 round")
	c.AssertStack("1.5707963")
}

func TestOpDocs_Angle_DegMin(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10.1234 dm")
	c.AssertStack("10° 7.404′")
}

func TestOpDocs_Angle_DegMinRound(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("12.57611 3 dmr")
	c.AssertStack("12° 34.567′")
}

func TestOpDocs_Angle_DegMinSec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-76.856944 dms")
	c.AssertStack("-76° 51′ 24.9984″")
}

func TestOpDocs_Angle_DegMinSecRound(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-76.856944 0 dmsr")
	c.AssertStack("-76° 51′ 25″")
}

func TestOpDocs_Angle_DmsGet(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c [10° 30′ 45″] dms?")
	c.AssertStack("true")

	c.Eval("c [10  30  45 ] dms?")
	c.AssertStack("false")
}

func TestOpDocs_Angle_MinutesDMS(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10d30m minutes")
	c.AssertStack("630")
}

func TestOpDocs_Angle_RadDeg(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.570796327 rad-deg 7 round")
	c.AssertStack("90")
}

func TestOpDocs_Angle_SecondsDMS(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10d30m seconds")
	c.AssertStack("37800")
}
