package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Bool_AndBool(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c true true and")
	c.AssertStack("true")

	c.Eval("c true false and")
	c.AssertStack("false")

	c.Eval("c false false and")
	c.AssertStack("false")
}

func TestOpDocs_Bool_False(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("false")
	c.AssertStack("false")
}

func TestOpDocs_Bool_NotBool(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("true not")
	c.AssertStack("false")

	c.Eval("not")
	c.AssertStack("true")
}

func TestOpDocs_Bool_OrBool(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c true true or")
	c.AssertStack("true")

	c.Eval("c true false or")
	c.AssertStack("true")

	c.Eval("c false false or")
	c.AssertStack("false")
}

func TestOpDocs_Bool_True(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("true")
	c.AssertStack("true")
}
