package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Cmp_Eq(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 5 5 eq")
	c.AssertStack("true")

	c.Eval("c 4 5 eq")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Eq_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 5.5 5.5 eq")
	c.AssertStack("true")

	c.Eval("c 4.4 5.5 eq")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Eq_Rat(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 1/2 1/2 eq")
	c.AssertStack("true")

	c.Eval("c 1/3 1/2 eq")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Eq_Complex(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 5+5i 5+5i eq")
	c.AssertStack("true")

	c.Eval("c 4+4i 5+5i eq")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Eq_String(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c /e /e eq")
	c.AssertStack("true")

	c.Eval("c /d /e eq")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 5 gt")
	c.AssertStack("true")

	c.Eval("c 5 5 gt")
	c.AssertStack("false")

	c.Eval("c 4 5 gt")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gt_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6.5 5.5 gt")
	c.AssertStack("true")

	c.Eval("c 5.5 5.5 gt")
	c.AssertStack("false")

	c.Eval("c 4.4 5.5 gt")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gt_Rat(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2/3 1/2 gt")
	c.AssertStack("true")

	c.Eval("c 1/2 1/2 gt")
	c.AssertStack("false")

	c.Eval("c 1/3 1/2 gt")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gt_String(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c /f /e gt")
	c.AssertStack("true")

	c.Eval("c /e /e gt")
	c.AssertStack("false")

	c.Eval("c /d /e gt")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gte(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 5 gte")
	c.AssertStack("true")

	c.Eval("c 5 5 gte")
	c.AssertStack("true")

	c.Eval("c 4 5 gte")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gte_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6.5 5.5 gte")
	c.AssertStack("true")

	c.Eval("c 5.5 5.5 gte")
	c.AssertStack("true")

	c.Eval("c 4.4 5.5 gte")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gte_Rat(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2/3 1/2 gte")
	c.AssertStack("true")

	c.Eval("c 1/2 1/2 gte")
	c.AssertStack("true")

	c.Eval("c 1/3 1/2 gte")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Gte_String(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c /f /e gte")
	c.AssertStack("true")

	c.Eval("c /e /e gte")
	c.AssertStack("true")

	c.Eval("c /d /e gte")
	c.AssertStack("false")
}

func TestOpDocs_Cmp_Lt(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 5 lt")
	c.AssertStack("false")

	c.Eval("c 5 5 lt")
	c.AssertStack("false")

	c.Eval("c 4 5 lt")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lt_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6.5 5.5 lt")
	c.AssertStack("false")

	c.Eval("c 5.5 5.5 lt")
	c.AssertStack("false")

	c.Eval("c 4.4 5.5 lt")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lt_Rat(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2/3 1/2 lt")
	c.AssertStack("false")

	c.Eval("c 1/2 1/2 lt")
	c.AssertStack("false")

	c.Eval("c 1/3 1/2 lt")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lt_String(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c /f /e lt")
	c.AssertStack("false")

	c.Eval("c /e /e lt")
	c.AssertStack("false")

	c.Eval("c /d /e lt")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lte(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6 5 lte")
	c.AssertStack("false")

	c.Eval("c 5 5 lte")
	c.AssertStack("true")

	c.Eval("c 4 5 lte")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lte_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 6.5 5.5 lte")
	c.AssertStack("false")

	c.Eval("c 5.5 5.5 lte")
	c.AssertStack("true")

	c.Eval("c 4.4 5.5 lte")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lte_Rat(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 2/3 1/2 lte")
	c.AssertStack("false")

	c.Eval("c 1/2 1/2 lte")
	c.AssertStack("true")

	c.Eval("c 1/3 1/2 lte")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Lte_String(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c /f /e lte")
	c.AssertStack("false")

	c.Eval("c /e /e lte")
	c.AssertStack("true")

	c.Eval("c /d /e lte")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Neq(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 5 5 neq")
	c.AssertStack("false")

	c.Eval("c 4 5 neq")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Neq_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 5.5 5.5 neq")
	c.AssertStack("false")

	c.Eval("c 4.4 5.5 neq")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Neq_Rat(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 1/2 1/2 neq")
	c.AssertStack("false")

	c.Eval("c 1/3 1/2 neq")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Neq_Complex(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 5+5i 5+5i neq")
	c.AssertStack("false")

	c.Eval("c 4+4i 5+5i neq")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Neq_String(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c /e /e neq")
	c.AssertStack("false")

	c.Eval("c /d /e neq")
	c.AssertStack("true")
}

func TestOpDocs_Cmp_Sort(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 4 2.5 1.75 sort")
	c.AssertStack("1.75", "2.5", "4")

	c.Eval("c 4 5/2 1.75 sort")
	c.AssertStack("1 3/4", "2 1/2", "4")

	c.Eval("c 4 5/2 'one and three quarters' sort")
	c.AssertStack("4", "5/2", "one and three quarters")
}

func TestOpDocs_Cmp_SortT(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("01.1 2 003 sort/t")
	c.AssertStack("003", "01.1", "2")
}
