package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Complex_SquareRootC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-16 sqrt/c")
	c.AssertStack("0+4i")
}
