package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Const_E(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("e")
	c.AssertStack("2.71828182845904523536028747135266249775724709369995957496696763")
}

func TestOpDocs_Const_Pi(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("pi")
	c.AssertStack("3.14159265358979323846264338327950288419716939937510582097494459")
}
