package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Crypto_Md5(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' md5")
	c.AssertStack("data: bbce0fb98a6a1b308e589d1408968ac2")
}

func TestOpDocs_Crypto_Rotate13(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' rot13")
	c.AssertStack("Oruvaq gur gerr!")

	c.Eval("rot13")
	c.AssertStack("Behind the tree!")
}

func TestOpDocs_Crypto_Sha1(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' sha1")
	c.AssertStack("data: da6e7f530a9b42a679944f0c9fc0f86ae5534450")
}

func TestOpDocs_Crypto_Sha1Hmac(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' /swordfish")
	c.AssertStack("Behind the tree!", "swordfish")

	c.Eval("sha1.hmac")
	c.AssertStack("data: 75859001097e8ad6907a879d340170ef571c8e5c")
}

func TestOpDocs_Crypto_Sha224(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' sha224")
	c.AssertStack("data: 15eac2f886e0e09a44ce08da58f3386b707885150d6142d1a6e7c608")
}

func TestOpDocs_Crypto_Sha224Hmac(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' /swordfish")
	c.AssertStack("Behind the tree!", "swordfish")

	c.Eval("sha224.hmac")
	c.AssertStack("data: 30ecbacd9aedf890b796eb79032105382ce323f18835f9bbb3867c4a")
}

func TestOpDocs_Crypto_Sha256(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' sha256")
	c.AssertStack("data: 5e19fc5f8ec2aabccef7970385bb9151a421f398d048ced2b2c86757aafebfc3")
}

func TestOpDocs_Crypto_Sha256Hmac(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' /swordfish")
	c.AssertStack("Behind the tree!", "swordfish")

	c.Eval("sha256.hmac")
	c.AssertStack("data: 0155d56d7485e9db843792ff48b97a1a96ae0655a92ad7c2324d71ed0410b907")
}

func TestOpDocs_Crypto_Sha384(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' sha384")
	c.AssertStack("data: 54489c547782d201bb0c8c2c81e77e034695067c98087bd949d13de752dd3843323c7244c1d15776ad52093598420dca")
}

func TestOpDocs_Crypto_Sha384Hmac(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' /swordfish")
	c.AssertStack("Behind the tree!", "swordfish")

	c.Eval("sha384.hmac")
	c.AssertStack("data: 401d0de7dd5cdf1ed82002cc1a696ec8d3d636b0388b89cc6f33ec4b237382a16b976f4773c3b0a3979392289a0ceaf9")
}

func TestOpDocs_Crypto_Sha512(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' sha512")
	c.AssertStack("data: 431777a80ed22c45b4fe0dc8c7e3a07d8d20df3b796a39068f2fc6f57cd69b6c60f4a6e3151189b97a1ad2fe5888c255e93f28c1e6c9b6f0241b10c34f8f9e86")
}

func TestOpDocs_Crypto_Sha512Hmac(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("'Behind the tree!' /swordfish")
	c.AssertStack("Behind the tree!", "swordfish")

	c.Eval("sha512.hmac")
	c.AssertStack("data: 8e4074cf371bc7e83cd508e9a3d4c0ecd9e014aa808f3234b05de26ddad9895ad6d375651b3ac8231806ccd0b9cd477f3df024c1ecd75032a0e827e7f2f98fcf")
}
