package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Epsg_EpsgUtm(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("17n epsg.utm")
	c.AssertStack("EPSG:32617")
}
