package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Float_AddF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1 2.2 add/f")
	c.AssertStack("3.3000000000000003")
}

func TestOpDocs_Float_AddQ(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1 2.2 add/q")
	c.AssertStack("3.3000000000000000000000000000000002")
}

func TestOpDocs_Float_AddSf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1 2.2 add/sf")
	c.AssertStack("3.3000002")
}

func TestOpDocs_Float_CbrtF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("76332.940488")
	c.AssertStack("76332.940488")

	c.Eval("cbrt/f 2 round")
	c.AssertStack("42.42")
}

func TestOpDocs_Float_CbrtF_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 cbrt/f")
	c.AssertError("cbrt/f: invalid argument, -1 < 0")
}

func TestOpDocs_Float_DivF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 3 div/f")
	c.AssertStack("0.6666666666666666")
}

func TestOpDocs_Float_DivF_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 0 div/f")
	c.AssertError("div/f: division by zero")
}

func TestOpDocs_Float_DivQ(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 3 div/q")
	c.AssertStack("0.6666666666666666666666666666666666")
}

func TestOpDocs_Float_DivQ_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 0 div/q")
	c.AssertError("div/q: division by zero")
}

func TestOpDocs_Float_DivSf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 3 div/sf")
	c.AssertStack("0.6666667")
}

func TestOpDocs_Float_DivSf_Zero(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("6.6 0 div/sf")
	c.AssertError("div/sf: division by zero")
}

func TestOpDocs_Float_ExpF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 exp/f 5 round")
	c.AssertStack("7.38906")
}

func TestOpDocs_Float_LogF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("8 log/f 5 round")
	c.AssertStack("2.07944")
}

func TestOpDocs_Float_Log10F(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("50 log10/f 5 round")
	c.AssertStack("1.69897")
}

func TestOpDocs_Float_MulF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1 2.2 mul/f")
	c.AssertStack("2.4200000000000004")
}

func TestOpDocs_Float_MulQ(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1 2.2 mul/q")
	c.AssertStack("2.4200000000000000000000000000000003")
}

func TestOpDocs_Float_MulSf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.1 2.2 mul/sf")
	c.AssertStack("2.42")
}

func TestOpDocs_Float_NegF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6")
	c.AssertStack("-6")

	c.Eval("neg/f")
	c.AssertStack("6")

	c.Eval("neg/f")
	c.AssertStack("-6")
}

func TestOpDocs_Float_NegQ(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-6")
	c.AssertStack("-6")

	c.Eval("neg/q")
	c.AssertStack("6")

	c.Eval("neg/q")
	c.AssertStack("-6")
}

func TestOpDocs_Float_SignF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c -6 sign/f")
	c.AssertStack("-1")

	c.Eval("c 6 sign/f")
	c.AssertStack("1")

	c.Eval("c 0 sign/f")
	c.AssertStack("0")
}

func TestOpDocs_Float_SqrtF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.5625 sqrt/f")
	c.AssertStack("1.25")
}

func TestOpDocs_Float_SqrtF_Negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 sqrt/f")
	c.AssertError("sqrt/f: invalid argument, -1 < 0")
}

func TestOpDocs_Float_SqrtQ(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1.5625 sqrt/q")
	c.AssertStack("1.25")
}

func TestOpDocs_Float_SqrtQ_Negative(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("-1 sqrt/q")
	c.AssertError("sqrt/q: invalid argument, -1 < 0")
}

func TestOpDocs_Float_SubF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("3.3 2.2 sub/f")
	c.AssertStack("1.0999999999999996")
}

func TestOpDocs_Float_SubQ(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("3.3 2.2 sub/q")
	c.AssertStack("1.0999999999999999999999999999999997")
}

func TestOpDocs_Float_SubSf(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("3.3 2.2 sub/sf")
	c.AssertStack("1.0999999")
}
