package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Geo_Haversine(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("38°54′17″N 77°00′59″W")
	c.AssertStack("38°54′17″N", "77°00′59″W")

	c.Eval("40°42′46″N 74°00′22″W")
	c.AssertStack("38°54′17″N", "77°00′59″W", "40°42′46″N", "74°00′22″W")

	c.Eval("haversine 2 round")
	c.AssertStack("326364.76 m")

	c.Eval("m-km 2 round")
	c.AssertStack("326.36 km")

	c.Eval("km-mi 2 round")
	c.AssertStack("202.79 mi")
}

func TestOpDocs_Geo_Proj(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("39.203611 -76.856944")
	c.AssertStack("39.203611", "-76.856944")

	c.Eval("epsg.wgs-84 18n epsg.utm")
	c.AssertStack("39.203611", "-76.856944", "EPSG:4326", "EPSG:32618")

	c.Eval("proj")
	c.AssertStack("339660.12559342897", "4.341014551927999e6")
}
