package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Int_IntData(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0x1234 int-data")
	c.AssertStack("data: 1234")
}
