package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Rand_Rand(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 rand.seed")
	c.AssertNotice("seed set to 1")

	c.Eval("rand")
	c.AssertStack("0.23842319087387442")
}

func TestOpDocs_Rand_RandSeed(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 1 rand.seed")
	c.AssertNotice("seed set to 1")

	c.Eval("10 rand/i")
	c.AssertStack("6")

	c.Eval("c 2 rand.seed 10 rand/i")
	c.AssertStack("7")

	c.Eval("c 1 rand.seed 10 rand/i")
	c.AssertStack("6")
}

func TestOpDocs_Rand_RandSeedGet(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 42 rand.seed")
	c.AssertNotice("seed set to 42")

	c.Eval("rand.seed?")
	c.AssertStack("42")
}

func TestOpDocs_Rand_RandTake(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 rand.seed")
	c.AssertNotice("seed set to 1")

	c.Eval("1 2 3 4 5 6")
	c.AssertStack("1", "2", "3", "4", "5", "6")

	c.Eval("rand.take")
	c.AssertStack("4")
}

func TestOpDocs_Rand_RandI(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 rand.seed")
	c.AssertNotice("seed set to 1")

	c.Eval("10 rand/i")
	c.AssertStack("6")
}

func TestOpDocs_Rand_Roll(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 rand.seed")
	c.AssertNotice("seed set to 1")

	c.Eval("3d6 roll")
	c.AssertStack("4", "1", "5")

	c.Eval("sum")
	c.AssertStack("10")
}
