package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Real_Dec(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 0xff dec")
	c.AssertStack("255")

	c.Eval("c 1/2 dec")
	c.AssertStack("0.5")
}

func TestOpDocs_Real_RoundingMode(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("rounding.mode?")
	c.AssertStack("half.even")

	c.Eval("c 5.55 1 round")
	c.AssertStack("5.6")

	c.Eval("/down rounding.mode")
	c.AssertNotice("rounding mode set to down")

	c.Eval("c 5.55 1 round")
	c.AssertStack("5.5")
}

func TestOpDocs_Real_RoundingModeGet(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("rounding.mode?")
	c.AssertStack("half.even")
}

func TestOpDocs_Real_Trunc(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 3.9 trunc")
	c.AssertStack("3")

	c.Eval("c -3.9 trunc")
	c.AssertStack("-3")
}
