package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Seq_Fibonacci(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 5 seq /fib map")
	c.AssertStack("1", "1", "2", "3", "5")
}

func TestOpDocs_Seq_Sequence(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 4 8 seq")
	c.AssertStack("4", "5", "6", "7", "8")

	c.Eval("c 8 4 seq")
	c.AssertStack("8", "7", "6", "5", "4")
}
