package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Stack_Clear(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2 3")
	c.AssertStack("1", "2", "3")

	c.Eval("c")
	c.AssertStack()
}

func TestOpDocs_Stack_Drop(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2 3")
	c.AssertStack("1", "2", "3")

	c.Eval("drop")
	c.AssertStack("1", "2")
}

func TestOpDocs_Stack_Dup(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("10")
	c.AssertStack("10")

	c.Eval("dup")
	c.AssertStack("10", "10")
}

func TestOpDocs_Stack_N(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("/a /b /c /d")
	c.AssertStack("a", "b", "c", "d")

	c.Eval("n")
	c.AssertStack("a", "b", "c", "d", "4")
}

func TestOpDocs_Stack_Swap(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2")
	c.AssertStack("1", "2")

	c.Eval("swap")
	c.AssertStack("2", "1")
}

func TestOpDocs_Stack_Tuck(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2")
	c.AssertStack("1", "2")

	c.Eval("tuck")
	c.AssertStack("2", "1", "2")

	c.Eval("add")
	c.AssertStack("2", "3")

	c.Eval("tuck add")
	c.AssertStack("3", "5")

	c.Eval("tuck add")
	c.AssertStack("5", "8")
}
