package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Stat_Average(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("0 100 25 75 average")
	c.AssertStack("50")
}

func TestOpDocs_Stat_Average_Empty(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("average")
	c.AssertError("div: division undefined")
}

func TestOpDocs_Stat_Factorial(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 3 fact")
	c.AssertStack("6")

	c.Eval("c 10 fact")
	c.AssertStack("3628800")
}

func TestOpDocs_Stat_StandardDevPop(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("stdev.p")
	c.AssertStack("2")
}

func TestOpDocs_Stat_StandardDevSamp(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("stdev.s 2 round")
	c.AssertStack("2.14")
}

func TestOpDocs_Stat_Sum(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("1 2 3 4 5")
	c.AssertStack("1", "2", "3", "4", "5")

	c.Eval("sum")
	c.AssertStack("15")
}

func TestOpDocs_Stat_VariancePop(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("var.p")
	c.AssertStack("4")
}

func TestOpDocs_Stat_VarianceSamp(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("var.s 2 round")
	c.AssertStack("4.57")
}
