package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Temp_CF(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("20 c-f")
	c.AssertStack("68 °F")
}

func TestOpDocs_Temp_CK(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("100 c-k")
	c.AssertStack("373.15 K")
}

func TestOpDocs_Temp_FC(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("68 f-c 2 round")
	c.AssertStack("20 °C")
}
