package doc_tests

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app"
)

func TestOpDocs_Text_Len(t *testing.T) {
	c := app.NewCalcTester(t)

	c.Eval("c 'abcd' len")
	c.AssertStack("4")

	c.Eval("c '🥇🥈🥉👏' len")
	c.AssertStack("4")
}
