package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var Anno = zc.Vol{
	Name: "anno",
	Ops: []zc.Op{
		ops.Label,
		ops.Unit,
	},
	Macros: []zc.Macro{},
}
