package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciFloat64 = zc.Vol{
	Name: "sci/Float/64",
	Ops: []zc.Op{
		ops.CbrtFloat64,
		ops.ExpFloat64,
		ops.Log10Float64,
	},
	Macros: []zc.Macro{},
}
