package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var SciComplex = zc.Vol{
	Name: "sci/Complex",
	Ops: []zc.Op{
		ops.AbsComplex,
		ops.AcosComplex,
		ops.AcoshComplex,
		ops.AsinComplex,
		ops.AsinhComplex,
		ops.AtanComplex,
		ops.AtanhComplex,
		ops.CosComplex,
		ops.CoshComplex,
		ops.CotComplex,
		ops.ExpComplex,
		ops.LogComplex,
		ops.Log10Complex,
		ops.SinComplex,
		ops.SinhComplex,
		ops.TanComplex,
		ops.TanhComplex,
	},
	Macros: []zc.Macro{},
}
