package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var TypesIntU32 = zc.Vol{
	Name: "types/Int/u32",
	Ops:  []zc.Op{},
	Macros: []zc.Macro{
		{Name: "max.u32", Expr: "4294967295"},
	},
}
