package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/ops"
)

var TypesIntU = zc.Vol{
	Name: "types/Int/u",
	Ops: []zc.Op{
		ops.MaxUint,
	},
	Macros: []zc.Macro{},
}
