package kinds

// Code generated by 'gen-ops'; DO NOT EDIT.

var (
	Bool     = "Bool"
	Float    = "Float"
	Float64  = "Float64"
	Int      = "Int"
	Int16    = "Int16"
	Int16U   = "Int16U"
	Int32    = "Int32"
	Int32U   = "Int32U"
	Int64    = "Int64"
	Int64U   = "Int64U"
	Int8     = "Int8"
	Int8U    = "Int8U"
	IntArch  = "IntArch"
	IntArchU = "IntArchU"
	Text     = "Text"
	Val      = "Val"
)
