//go:generate go run gen-tz.go

package main

import (
	"fmt"
	"log"
	"os"
	"path"
	"sort"
	"strings"
	"unicode"
)

const (
	TzYaml = "../../app/defs/tz.yaml"
)

var (
	aliases = map[string]string{
		"atlantic.canada":             "canada.atlantic",
		"center.north-dakota.america": "north-dakota.center.america",
		"east.brazil":                 "brazil.east",
		"eastern.canada":              "canada.eastern",
		"eastern.us":                  "us.eastern",
		"general.mexico":              "mexico.general",
		"north.australia":             "australia.north",
		"pacific.canada":              "canada.pacific",
		"pacific.us":                  "us.pacific",
		"west.australia":              "australia.west",
		"west.brazil":                 "brazil.west",
	}
	ignores = map[string]struct{}{
		"factory": {},
	}
)

func main() {
	log.SetFlags(0)

	zoneMap := make(map[string]string)
	processDir(zoneMap, []string{}, "/usr/share/zoneinfo")

	var names []string
	for name := range zoneMap {
		names = append(names, name)
	}
	sort.Strings(names)

	ftz, err := os.Create(TzYaml)
	if err != nil {
		log.Panic(err)
	}
	defer ftz.Close()

	fmt.Fprintf(ftz, "# File generated by 'gen-tz'; DO NOT EDIT.\n\n")
	fmt.Fprintf(ftz, "name: tz\n")
	fmt.Fprintf(ftz, "title: Time zone database\n")
	fmt.Fprintf(ftz, "category: tab\n")
	fmt.Fprintf(ftz, "no-index: true\n\n")
	fmt.Fprintf(ftz, "table:\n")

	for _, name := range names {
		fmt.Fprintf(ftz, "- [\"tz.%v\", \"'%v'\"]\n", name, zoneMap[name])
	}
}

func processDir(zones map[string]string, parent []string, dir string) {
	if strings.HasSuffix(dir, "/posix") || strings.HasSuffix(dir, "/right") {
		return
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Panic(err)
	}
	for _, entry := range entries {
		here := append(parent, entry.Name())
		if entry.IsDir() {
			childDir := path.Join(dir, entry.Name())
			processDir(zones, here, childDir)
			continue
		}
		first := entry.Name()[0]
		if first == '+' || unicode.IsLower(rune(first)) {
			continue
		}
		zone := strings.Join(here, "/")

		var parts []string
		for i := len(here) - 1; i >= 0; i-- {
			part := strings.ToLower(here[i])
			part = strings.ReplaceAll(part, "_", "-")
			parts = append(parts, part)
		}
		word := strings.Join(parts, ".")
		if _, ok := ignores[word]; ok {
			continue
		}
		if strings.HasSuffix(word, ".etc") {
			if strings.HasPrefix(word, "gmt") {
				word = strings.Replace(word, ".etc", "", 1)
			} else {
				continue
			}
		}
		zones[word] = zone
		alias, ok := aliases[word]
		if ok {
			zones[alias] = zone
		}
	}
}
