package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/ops"
)

var Stack = zc.Vol{
	Name: "stack",
	Ops: []zc.Op{
		ops.Clear,
		ops.Down,
		ops.Drop,
		ops.Dup,
		ops.Up,
	},
	Macros: []zc.Macro{
		{Name: "c", Expr: "clear"},
		{Name: "dn", Expr: "down"},
	},
}
