package ints

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	AddInt16 = zc.Op{
		Name: "add.int16",
		Aliases: []string{
			"addi16",
		},
		Params:  []string{kinds.Int16, kinds.Int16},
		Returns: []string{kinds.Int16},
		Prec:    kinds.PrecIntSized,
		Func:    addInt16,
	}
	AddInt32 = zc.Op{
		Name: "add.int32",
		Aliases: []string{
			"addi32",
		},
		Params:  []string{kinds.Int32, kinds.Int32},
		Returns: []string{kinds.Int32},
		Prec:    kinds.PrecIntSized,
		Func:    addInt32,
	}
	AddInt64 = zc.Op{
		Name: "add.int64",
		Aliases: []string{
			"addi64",
		},
		Params:  []string{kinds.Int64, kinds.Int64},
		Returns: []string{kinds.Int64},
		Prec:    kinds.PrecIntSized,
		Func:    addInt64,
	}
	AddInt8 = zc.Op{
		Name: "add.int8",
		Aliases: []string{
			"addi8",
		},
		Params:  []string{kinds.Int8, kinds.Int8},
		Returns: []string{kinds.Int8},
		Prec:    kinds.PrecIntSized,
		Func:    addInt8,
	}
	AddIntArch = zc.Op{
		Name:      "add.intarch",
		Overloads: "add",
		Aliases: []string{
			"addia",
		},
		Params:  []string{kinds.IntArch, kinds.IntArch},
		Returns: []string{kinds.IntArch},
		Prec:    kinds.PrecIntArch,
		Func:    addIntArch,
	}
	Int64ToInt8 = zc.Op{
		Name:    "int8",
		Aliases: []string{},
		Params:  []string{kinds.Int64},
		Returns: []string{kinds.Int8},
		Func:    int64ToInt8,
	}
	Uint64ToInt8 = zc.Op{
		Name:    "int8",
		Aliases: []string{},
		Params:  []string{kinds.Int64U},
		Returns: []string{kinds.Int8},
		Prec:    1,
		Func:    uint64ToInt8,
	}
	IsInt8 = zc.Op{
		Name:    "int8?",
		Aliases: []string{},
		Params:  []string{kinds.Text},
		Returns: []string{kinds.Bool},
		Func:    isInt8,
	}
)
