package ints

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var Volume = zc.Vol{
	Name: "ints",
	Kinds: []zc.Kind{
		IntArchKind,
		Int8Kind,
		Int16Kind,
		Int32Kind,
		Int64Kind,
		IntArchUKind,
		Int8UKind,
		Int16UKind,
		Int32UKind,
		Int64UKind,
	},
	Ops: []zc.Op{
		AddInt16,
		AddInt32,
		AddInt64,
		AddInt8,
		AddIntArch,
		Int64ToInt8,
		Uint64ToInt8,
		IsInt8,
	},
}
