package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestParseDMS(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("c 10.5125 dec")
	c.AssertStack("10.5125")

	c.Eval("c 10.5125d dec")
	c.AssertStack("10.5125")

	c.Eval("c 10.5125° dec")
	c.AssertStack("10.5125")

	c.Eval("c 10d30.75m dec")
	c.AssertStack("10.5125")

	c.Eval("c 10d30.75' dec")
	c.AssertStack("10.5125")

	c.Eval("c [10° 30′ 45″] dec")
	c.AssertStack("10.5125")
}
