package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestTypesBool(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("true true and")
	c.AssertStack("true")

	c.Eval("'FALSE' and")
	c.AssertStack("false")
}
