package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestTypesComplex(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("-16 sqrt/c")
	c.AssertStack("0+4i")

	c.Eval("2+2i add")
	c.AssertStack("2+6i")
}
