package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestDecParse(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("c 12,345.67 dec")
	c.AssertStack("12345.67")

	c.Eval("c 12_345.67 dec")
	c.AssertStack("12345.67")

	c.Eval("c '12_345.67' dec")
	c.AssertStack("12345.67")

	c.Eval("c $12,345.67 dec")
	c.AssertStack("12345.67")

	c.Eval("c 12,345$.67 dec")
	c.AssertStack("12345.67")
}
