package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestIntParse(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("c 12,345 dec")
	c.AssertStack("12345")

	c.Eval("c 12_345 dec")
	c.AssertStack("12345")

	c.Eval("c '12_345' dec")
	c.AssertStack("12345")

	c.Eval("c $12,345 dec")
	c.AssertStack("12345")

	c.Eval("c 12,345$ dec")
	c.AssertStack("12345")
}

func TestIntRadix(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("c 0b11111111 dec")
	c.AssertStack("255")

	c.Eval("c 0o377 dec")
	c.AssertStack("255")

	c.Eval("c 0xff dec")
	c.AssertStack("255")
}
