package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestTypesRational(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("c 1/2 1/4 add")
	c.AssertStack("3/4")

	c.Eval("c 2_1/2 3_1/4 add")
	c.AssertStack("5 3/4")

	c.Eval("c [2 1/2] [3 1/4] add")
	c.AssertStack("5 3/4")

	c.Eval("c 2-1/2 3-1/4 add")
	c.AssertStack("5 3/4")
}
