package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestSimpleAddition(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 3 a")
	c.AssertStack("5")
}

func TestSimpleAddition2(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2")
	c.AssertStack("2")

	c.Eval("3")
	c.AssertStack("2", "3")

	c.Eval("a")
	c.AssertStack("5")
}

func TestNotice(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("0 rand.seed")
	c.AssertNotice("seed set to 0")
}

func TestDistance(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("5 2 sub")
	c.AssertStack("3")

	c.Eval("2 pow")
	c.AssertStack("9")

	c.Eval("7 3 sub")
	c.AssertStack("9", "4")

	c.Eval("2 pow")
	c.AssertStack("9", "16")

	c.Eval("add")
	c.AssertStack("25")

	c.Eval("sqrt")
	c.AssertStack("5")
}

func TestThousandsIgnored(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("65,536 sqrt")
	c.AssertStack("256")
}

func TestCurrency(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("$1234 2 mul")
	c.AssertStack("2468")
}

func TestBigInt(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 128 pow")
	c.AssertStack("340282366920938463463374607431768211456")
}

func TestDecimal(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1.1 2.2 a")
	c.AssertStack("3.3")
}

func TestFloat(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1.1 2.2 add/f")
	c.AssertStack("3.3000000000000000000000000000000002")
}

func TestRound(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1.1 2.2 add/f")
	c.AssertStack("3.3000000000000000000000000000000002")

	c.Eval("2 round")
	c.AssertStack("3.3")
}

func TestFraction(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1/2 1/4")
	c.AssertStack("1/2", "1/4")

	c.Eval("add")
	c.AssertStack("3/4")
}

func TestWholeFraction(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2-1/2 3-1/4")
	c.AssertStack("2-1/2", "3-1/4")

	c.Eval("add")
	c.AssertStack("5 3/4")
}

func TestComplex(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1+2i 2+3i")
	c.AssertStack("1+2i", "2+3i")

	c.Eval("add")
	c.AssertStack("3+5i")
}

func TestTextSlash(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2")
	c.AssertStack("1", "2")

	c.Eval("/add")
	c.AssertStack("1", "2", "add")
}

func TestTextQuote(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("'one thousand")
	c.AssertStack("one thousand")

	c.Eval("len")
	c.AssertStack("12")
}

func TestTextBracket(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2 [[[add]]]")
	c.AssertStack("1", "2", "[[add]]")

	c.Eval("eval")
	c.AssertStack("1", "2", "[add]")

	c.Eval("eval")
	c.AssertStack("1", "2", "add")

	c.Eval("eval")
	c.AssertStack("3")
}

func TestQuote(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2 add")
	c.AssertStack("3")

	c.Eval("quote EOF")
	c.AssertStack("3")

	c.Eval("2 3 add")
	c.AssertStack("3", "2 3 add")

	c.Eval("EOF")
	c.AssertStack("3", "2 3 add")
}
