package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestSimpleAddition(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 3 a")
	c.AssertStack("5")
}

func TestSimpleAddition2(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2")
	c.AssertStack("2")

	c.Eval("3")
	c.AssertStack("2", "3")

	c.Eval("a")
	c.AssertStack("5")
}

func TestNotice(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("0 rand.seed")
	c.AssertNotice("seed set to 0")
}

func TestDistance(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("5 2 sub")
	c.AssertStack("3")

	c.Eval("2 pow")
	c.AssertStack("9")

	c.Eval("7 3 sub")
	c.AssertStack("9", "4")

	c.Eval("2 pow")
	c.AssertStack("9", "16")

	c.Eval("add")
	c.AssertStack("25")

	c.Eval("sqrt")
	c.AssertStack("5")
}

func TestThousandsIgnored(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("65,536 sqrt")
	c.AssertStack("256")
}

func TestCurrency(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("$1234 2 mul")
	c.AssertStack("2468")
}

func TestBigInt(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 128 pow")
	c.AssertStack("340282366920938463463374607431768211456")
}

func TestDecimal(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1.1 2.2 a")
	c.AssertStack("3.3")
}

func TestFloat(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1.1 2.2 add/f")
	c.AssertStack("3.3000000000000003")
}

func TestRound(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1.1 2.2 add/f")
	c.AssertStack("3.3000000000000003")

	c.Eval("2 round")
	c.AssertStack("3.3")
}

func TestFraction(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1/2 1/4")
	c.AssertStack("1/2", "1/4")

	c.Eval("add")
	c.AssertStack("3/4")
}

func TestWholeFraction(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2-1/2 3-1/4")
	c.AssertStack("2-1/2", "3-1/4")

	c.Eval("add")
	c.AssertStack("5 3/4")
}

func TestComplex(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1+2i 2+3i")
	c.AssertStack("1+2i", "2+3i")

	c.Eval("add")
	c.AssertStack("3+5i")
}

func TestTextSlash(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2")
	c.AssertStack("1", "2")

	c.Eval("/add")
	c.AssertStack("1", "2", "add")
}

func TestTextQuote(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("'one thousand")
	c.AssertStack("one thousand")

	c.Eval("len")
	c.AssertStack("12")
}

func TestTextBracket(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2 [[[add]]]")
	c.AssertStack("1", "2", "[[add]]")

	c.Eval("eval")
	c.AssertStack("1", "2", "[add]")

	c.Eval("eval")
	c.AssertStack("1", "2", "add")

	c.Eval("eval")
	c.AssertStack("3")
}

func TestQuote(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2 add")
	c.AssertStack("3")

	c.Eval("quote EOF")
	c.AssertStack("3")

	c.Eval("2 3 add")
	c.AssertStack("3", "2 3 add")

	c.Eval("EOF")
	c.AssertStack("3", "2 3 add")
}

func TestAnnoHaversine(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 1 2 2")
	c.AssertStack("1", "1", "2", "2")

	c.Eval("haversine")
	c.AssertStack("157225.4320380729 m")

	c.Eval("m-km 2 round")
	c.AssertStack("157.23 km")
}

func TestAnnoUnit(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("123")
	c.AssertStack("123")

	c.Eval("/m unit")
	c.AssertStack("123 m")
}

func TestAnnoLabel(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("42")
	c.AssertStack("42")

	c.Eval("[the answer] label")
	c.AssertStack("the answer: 42")
}

func TestAnnoDiscard(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("123 /m unit")
	c.AssertStack("123 m")

	c.Eval("20 sub")
	c.AssertStack("103")
}

func TestTax(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("$123")
	c.AssertStack("$123")

	c.Eval("dup")
	c.AssertStack("$123", "$123")

	c.Eval("0.05")
	c.AssertStack("$123", "$123", "0.05")

	c.Eval("mul")
	c.AssertStack("$123", "6.15")

	c.Eval("add")
	c.AssertStack("129.15")
}

func TestTaxMacro(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("def tax dup 0.05 mul")
	c.AssertNotice("macro 'tax' defined")

	c.Eval("$123")
	c.AssertStack("$123")

	c.Eval("tax add")
	c.AssertStack("129.15")
}

func TestBulk(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("def = top f-c 2 round")
	c.AssertNotice("macro '=' defined")

	c.Eval("32 =")
	c.AssertStack("0 °C")

	c.Eval("68 =")
	c.AssertStack("20 °C")

	c.Eval("100 =")
	c.AssertStack("37.78 °C")
}

func TestRPS(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 rand.seed")
	c.AssertNotice("seed set to 1")

	c.Eval("def .rps c 'rock' 'paper' 'scissors' rand.take")
	c.AssertNotice("macro '.rps' defined")

	c.Eval(".rps")
	c.AssertStack("paper")

	c.Eval(".rps")
	c.AssertStack("rock")
}

func TestOverride(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("def pi 'Yum")
	c.AssertNotice("macro 'pi' overrides")

	c.Eval("pi")
	c.AssertStack("Yum")

	c.Eval("def pi")
	c.AssertNotice("macro 'pi' undefined")

	c.Eval("pi 5 r")
	c.AssertStack("Yum", "3.14159")
}

func TestMap(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2 3 4 5")
	c.AssertStack("1", "2", "3", "4", "5")

	c.Eval("[2 mul")
	c.AssertStack("1", "2", "3", "4", "5", "2 mul")

	c.Eval("map")
	c.AssertStack("2", "4", "6", "8", "10")
}

func TestFold(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("1 2 3 4 5")
	c.AssertStack("1", "2", "3", "4", "5")

	c.Eval("[add")
	c.AssertStack("1", "2", "3", "4", "5", "add")

	c.Eval("fold")
	c.AssertStack("15")
}

func TestAverage(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("n")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9", "8")

	c.Eval("push")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("sum")
	c.AssertStack("40")

	c.Eval("pop")
	c.AssertStack("40", "8")

	c.Eval("div")
	c.AssertStack("5")
}

func TestStddev(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("/data st")
	c.AssertNotice("stored")

	c.Eval("avg")
	c.AssertStack("5")

	c.Eval("/av st")
	c.AssertNotice("stored")

	c.Eval("c /data ld")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("[/av ld sub sq] map")
	c.AssertStack("9", "1", "1", "1", "0", "0", "4", "16")

	c.Eval("avg sqrt")
	c.AssertStack("2")
}

func TestStddevTemp(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("2 4 4 4 5 5 7 9")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("copy")
	c.AssertNotice("copied")

	c.Eval("avg")
	c.AssertStack("5")

	c.Eval("popa")
	c.AssertStack("5", "2", "4", "4", "4", "5", "5", "7", "9")

	c.Eval("up")
	c.AssertStack("2", "4", "4", "4", "5", "5", "7", "9", "5")

	c.Eval("[sub sq] /map 2 apply")
	c.AssertStack("9", "1", "1", "1", "0", "0", "4", "16")

	c.Eval("avg sqrt")
	c.AssertStack("2")
}
