package docs

// Code generated by 'gen-doc-tests; DO NOT EDIT.

import (
	"testing"

	"github.com/blackchip-org/zc/v6/app/repl"
)

func TestTypesDate(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("'Jan 2 2006 15:04:05 -0700 MST' now=")
	c.Eval("'MST' local.zone")

	c.Eval("c 2006-01 dt")
	c.AssertStack("Sun Jan 1 2006 12:00:00am -0700 MST")

	c.Eval("c 2006-01-02 dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 2006-032 dt")
	c.AssertStack("Wed Feb 1 2006 12:00:00am -0700 MST")

	c.Eval("c 1/2 dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 1/2/2006 dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 1/2/06 dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 'Jan 2 2006' dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 'Jan 2 06' dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 'Fri Jan 2 2006' dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 'Friday Jan 2 2006' dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 'Jan 2' dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 'Fri, Jan 2' dt")
	c.AssertStack("Mon Jan 2 2006 12:00:00am -0700 MST")

	c.Eval("c 15:04:05 dt")
	c.AssertStack("Mon Jan 2 2006 3:04:05pm -0700 MST")

	c.Eval("c '15:04:05 PDT' dt")
	c.AssertStack("Mon Jan 2 2006 3:04:05pm -0700 PDT")

	c.Eval("c 15:04 dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00pm -0700 MST")

	c.Eval("c 3:04PM dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00pm -0700 MST")

	c.Eval("c '3:04 PM' dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00pm -0700 MST")

	c.Eval("c 3:04a dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00am -0700 MST")

	c.Eval("c '3:04a EST' dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00am -0500 EST")

	c.Eval("c '3:04a -0500' dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00am -0500")

	c.Eval("c '3:04a EST -0500' dt")
	c.AssertStack("Mon Jan 2 2006 3:04:00am -0500 EST")
}

func TestTypesDuration(t *testing.T) {
	c := repl.NewReplTester(t)

	c.Eval("'Jan 2 2006 15:04:05 -0700 MST' now=")
	c.Eval("'MST' local.zone")

	c.Eval("4h15m30s 10m20s add")
	c.AssertStack("4h 25m 50s")

	c.Eval("10s add")
	c.AssertStack("4h 26m")

	c.Eval("34m add")
	c.AssertStack("5h")
}
