// Code generated by "gen-ops"; DO NOT EDIT
package calc

import (
	"github.com/blackchip-org/zc/pkg/ops"
	"github.com/blackchip-org/zc/pkg/zc"
)

var opsList2 = []zc.OpDecl{
	zc.Op("and", ops.AndBool, zc.Bool, zc.Bool),
	zc.Op("not", ops.NotBool, zc.Bool),
	zc.Op("or", ops.OrBool, zc.Bool, zc.Bool),
}