//go:generate go run gen-emoji.go

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

const (
	EmojiYaml = "../../app/defs/emoji.yaml"
)

type Emoji struct {
	Name                          string `json:"name"`
	Slug                          string `json:"slug"`
	Group                         string `json:"group"`
	EmojiVersion                  string `json:"emoji_version"`
	UnicodeVersion                string `json:"unicode_version"`
	SkinToneSupport               bool   `json:"skin_tone_support"`
	SkinToneSupportUnicodeVersion string `json:"skin_tone_support_unicode_version"`
}

func main() {
	var names []string
	nameToCh := make(map[string]string)

	emojii := make(map[string]Emoji)
	data, err := os.ReadFile("data-by-emoji.json")
	if err != nil {
		panic(err)
	}
	json.Unmarshal(data, &emojii)

	var keys []string
	for k := range emojii {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fent, err := os.Create(EmojiYaml)
	if err != nil {
		panic(err)
	}
	defer fent.Close()

	fmt.Fprintf(fent, "# File generated by 'gen-emoji'; DO NOT EDIT.\n\n")
	fmt.Fprintf(fent, "name: emoji\n")
	fmt.Fprintf(fent, "title: Unicode emoji characters\n")
	fmt.Fprintf(fent, "category: tab\n")
	fmt.Fprintf(fent, "no-index: true\n")
	fmt.Fprintf(fent, "remove-slash: true\n\n")
	fmt.Fprintf(fent, "table:\n")

	for _, ch := range keys {
		emoji := emojii[ch]
		name := slugToName(emoji.Slug)
		names = append(names, name)
		nameToCh[name] = ch
	}
	sort.Strings(names)
	for _, name := range names {
		ch := nameToCh[name]
		fmt.Fprintf(fent, "- [\":%v:\", \"/%v\"]\n", name, ch)
	}

}

func slugToName(slug string) string {
	return fmt.Sprintf("%v", strings.ReplaceAll(slug, "_", "-"))
}
