package floats

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	AddFloat64 = zc.Op{
		Name: "add.float64",
		Aliases: []string{
			"addf64",
		},
		Params:  []string{kinds.Float64, kinds.Float64},
		Returns: []string{kinds.Float64},
		Func:    addFloat64,
	}
)
