package floats

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	Add = zc.Op{
		Name: "add",
		Aliases: []string{
			"add.float64",
			"addf64",
		},
		Params:  []string{kinds.Float64, kinds.Float64},
		Returns: []string{kinds.Float64},
		Prec:    kinds.PrecFloat,
		Func:    add,
	}
)
