// Code generated by 'gen-ops'; DO NOT EDIT
package floats

import (
	"github.com/blackchip-org/zc/v6"
)

var Volume = zc.Vol{
	Name: "floats",
	Kinds: []zc.Kind{
		Float64Kind,
	},
	Ops: []zc.Op{
		Add,
	},
}
