//go:generate go run gen-ops.go

package main

import (
	"fmt"
	"log"
	"os"
	"path"
	"slices"
	"sort"
	"strings"
	"unicode"

	"github.com/blackchip-org/scan"
	"github.com/blackchip-org/zc/v6"
	"golang.org/x/exp/maps"
)

type ValDoc struct {
	Label string
	Kind  string
	Var   bool
}

var (
	RootDir  = path.Join("..", "..")
	DocDir   = path.Join(RootDir, "doc", "ops")
	KindsDir = path.Join(RootDir, "kinds")
	OpsDir   = path.Join(RootDir, "ops")
	TestDir  = path.Join(RootDir, "test", "docs")
	VolDir   = path.Join(RootDir, "volumes")
)

func main() {
	docs, err := zc.LoadDocs()
	if err != nil {
		log.Panic(err)
	}
	genOpsConst(docs)
	genKinds(docs)
	genOps(docs)
	genVols(docs)
	genTests(docs)
}

func genOpsConst(docs []zc.VolDoc) {
	nameSet := make(map[string]struct{})
	for _, vol := range docs {
		for _, op := range vol.Ops {
			nameSet[op.Name] = struct{}{}
			for _, a := range op.Aliases {
				nameSet[a] = struct{}{}
			}
		}
	}
	names := maps.Keys(nameSet)
	sort.Strings(names)

	os.Mkdir(OpsDir, 0755)
	f, err := os.Create(path.Join(OpsDir, "ops.go"))
	if err != nil {
		log.Panic(err)
	}
	defer f.Close()

	fmt.Fprintf(f, "package ops\n\n")
	fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
	fmt.Fprintf(f, "var (\n")

	for _, name := range names {
		var s scan.Scanner
		s.InitFromString("", name)

		// Skip any names that are only symbols
		if !scan.IsLetter(s.This) {
			continue
		}
		s.Val.WriteRune(unicode.ToUpper(s.This))
		s.Skip()

		for s.HasMore() {
			if s.Next == '.' || s.Next == '-' {
				s.Keep()
				s.Skip()
				s.Val.WriteRune(unicode.ToUpper(s.This))
				s.Skip()
			} else {
				s.Keep()
			}
		}
		fmt.Fprintf(f, "\t%v = \"%v\"\n", s.Emit().Val, name)
	}
	fmt.Fprintf(f, ")\n")
}

func genOps(vols []zc.VolDoc) {
	for _, vol := range vols {
		if len(vol.Ops) == 0 {
			continue
		}
		f, err := os.Create(path.Join(VolDir, vol.Package, "ops.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package %v\n\n", vol.Package)
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/kinds\"\n")
		fmt.Fprintf(f, ")\n")

		fmt.Fprintf(f, "var (\n")
		for _, op := range vol.Ops {
			opIdent, ok := opIdent(op.Name)
			if !ok {
				log.Panicf("cannot create identifier for %v", op.Name)
			}
			fmt.Fprintf(f, "%v = zc.Op{\n", opIdent)
			fmt.Fprintf(f, "Name: \"%v\",\n", op.Name)
			fmt.Fprintf(f, "Aliases: []string{\n")
			for _, a := range op.Aliases {
				fmt.Fprintf(f, "\"%v\",\n", a)
			}
			fmt.Fprintf(f, "},\n")
			genValList(f, "Params", "VarParams", op.Params)
			genValList(f, "Returns", "VarReturns", op.Returns)
			if op.Prec != "" {
				fmt.Fprintf(f, "Prec: kinds.Prec%v,\n", op.Prec)
			}
			fmt.Fprintf(f, "Func: %v,\n", op.Func)
			fmt.Fprintf(f, "}\n")
		}
		fmt.Fprintf(f, ")\n")
	}
}

func genVols(vols []zc.VolDoc) {
	for _, vol := range vols {
		f, err := os.Create(path.Join(VolDir, vol.Package, "volume.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package %v\n\n", vol.Package)
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, ")\n")

		fmt.Fprintf(f, "var Volume = zc.Vol{\n")
		fmt.Fprintf(f, "Name: \"%v\",\n", vol.Name)
		fmt.Fprintf(f, "Kinds: []zc.Kind{\n")
		for _, k := range vol.Kinds {
			fmt.Fprintf(f, "%vKind,\n", k)
		}
		fmt.Fprintf(f, "},\n")
		fmt.Fprintf(f, "Ops: []zc.Op{\n")
		for _, o := range vol.Ops {
			name, ok := opIdent(o.Name)
			if !ok {
				log.Panicf("cannot create identifier for %v", o.Name)
			}
			fmt.Fprintf(f, "%v,\n", name)
		}
		fmt.Fprintf(f, "},\n")
		fmt.Fprintf(f, "}\n")
	}
}

func genKinds(vols []zc.VolDoc) {
	kinds := []string{"Val"}
	for _, vol := range vols {
		kinds = append(kinds, vol.Kinds...)
	}
	slices.Sort(kinds)

	f, err := os.Create(path.Join(KindsDir, "kinds.go"))
	if err != nil {
		log.Panic(err)
	}
	defer f.Close()

	fmt.Fprintf(f, "package kinds\n\n")
	fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
	fmt.Fprintf(f, "var (\n")
	for _, k := range kinds {
		fmt.Fprintf(f, "%v = \"%v\"\n", k, k)
	}
	fmt.Fprintf(f, ")\n")
}

func genTests(vols []zc.VolDoc) {
	for _, vol := range vols {
		if len(vol.Ops) == 0 {
			continue
		}
		f, err := os.Create(path.Join(TestDir, vol.Package+"_test.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package doc_tests\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"testing\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/calc\"\n")
		fmt.Fprintf(f, ")\n")

		for _, op := range vol.Ops {
			volIdent, _ := opIdent(vol.Name)
			opIdent, _ := opIdent(op.Name)

			fmt.Fprintf(f, "func Test%v%v(t *testing.T) {\n", volIdent, opIdent)
			fmt.Fprintf(f, "c := calc.New()\n")
			//fmt.Fprintf(f, "var have, want []string\n")
			for _, e := range op.Example {
				fmt.Fprintf(f, "\nc.Eval(\"%v\")\n", e.Input)
				//fmt.Fprintf(f, "have = c.StackStrings()\n")
				//fmt.Fprintf(f, "want = []string{")
				fmt.Fprintf(f, "zc.TestCalc(t, c")
				for _, out := range e.Output {
					fmt.Fprintf(f, ", \"%v\"", out)
				}
				fmt.Fprintf(f, ")\n")
				//fmt.Fprintf(f, "if reflect.DeepEqual(have, want) {\n")
				//fmt.Fprintf(f, "t.Fatalf(\"\\n have: %%v \\n want: %%v\", zc.FormatStackValues(have), zc.FormatStackValues(want))\n")
				//fmt.Fprintf(f, "}\n")
			}
			fmt.Fprintf(f, "}\n\n")
		}
	}
}

// func genVolDocs(vols []volumes.Doc) {
// 	os.Mkdir(OpsDir, 0755)
// 	for _, vol := range vols {
// 		f, err := os.Create(path.Join(DocDir, ".md"))
// 		if err != nil {
// 			log.Panic(err)
// 		}

// 		fmt.Fprintf(f, "<!-- Document generated by \"gen-doc\"; DO NOT EDIT -->\n")
// 		fmt.Fprintf(f, "\n")
// 		fmt.Fprintf(f, "# %v\n\n", vol.Name)
// 		fmt.Fprintf(f, "%v\n\n", vol.Title)
// 		if vol.Overview != "" {
// 			fmt.Fprintf(f, "## Overview\n\n")
// 			fmt.Fprintf(f, vol.Overview)
// 			fmt.Fprintf(f, "\n")
// 		}
// 		fmt.Fprintf(f, "## Index\n\n")

// 		tab := pretty.NewMarkdownTable(2)
// 		tab.Heading("Operation", "Description")

// 		for _, op := range vol.Ops {
// 			allNames := op.Name
// 			if len(op.Aliases) > 0 {
// 				allNames += ", " + strings.Join(op.Aliases, ", ")
// 			}
// 			anchor := strings.ReplaceAll(op.Name, "?", "")
// 			entry := fmt.Sprintf("[`%v`](#%v)", strings.Join(op.AllNames(), ", "), anchor)
// 			tab.Row(entry, op.Title)
// 		}
// 		fmt.Fprint(f, tab.Format())
// 		fmt.Fprintf(f, "\n## Operations\n")

// 		for _, op := range vol.Ops {
// 			writeOp(f, op)
// 		}
// 	}
// }

// func writeOp(f *os.File, op volumes.OpDoc) {
// 	fmt.Fprintf(f, "\n### %v\n\n", op.Name)
// 	fmt.Fprintf(f, "%v\n\n", op.Desc)
// 	if len(op.Aliases) > 0 {
// 		if len(op.Aliases) == 1 {
// 			fmt.Fprintf(f, "Alias: ")
// 		} else {
// 			fmt.Fprintf(f, "Aliases: ")
// 		}
// 		var fmtAliases []string
// 		for _, a := range op.Aliases {
// 			fmtAliases = append(fmtAliases, fmt.Sprintf("`%v`", a))
// 		}
// 		fmt.Fprintf(f, "%v\n\n", strings.Join(fmtAliases, ", "))
// 	}

// 	if len(op.Funcs) > 0 {
// 		fmt.Fprintf(out, "```\n")
// 		for _, fn := range op.Funcs {
// 			fmt.Fprintf(out, "( ")
// 			fmt.Fprintf(out, "%v -- ", fn.Params())
// 			fmt.Fprintf(out, "%v )\n", fn.Returns())
// 		}
// 		fmt.Fprintf(out, "```\n")
// 		fmt.Fprintln(out, "")
// 	}
// 	if op.Macro != "" {
// 		fmt.Fprintf(out, "```\n")
// 		fmt.Fprintf(out, "def %v %v\n", op.Name, op.Macro)
// 		fmt.Fprintf(out, "```\n")
// 		fmt.Fprintln(out, "")
// 	}

// 	if len(op.Example) > 0 {
// 		fmt.Fprintf(out, "Example:\n\n<!-- test: %v -->\n\n", op.Name)
// 		writeExample(out, op.Example)
// 	}
// }

// func writeExample(out *strings.Builder, expected []doc.Expect) {
// 	tab := pretty.NewMarkdownTable(2)
// 	tab.Heading("Input", "Stack")
// 	for _, ex := range expected {
// 		o := strings.Join(ex.O, " \\| ")
// 		quotes := "`"
// 		if strings.HasPrefix(o, "*") || o == "" {
// 			quotes = ""
// 		}
// 		tab.Row(ex.I, quotes+o+quotes)
// 	}
// 	fmt.Fprint(out, tab.Format())
// }

func parseValDoc(v string) ValDoc {
	s := scan.NewScannerFromString("", v)
	var val ValDoc
	for s.HasMore() {
		if s.This == ':' {
			s.Skip()
			val.Label = s.Emit().Val
		} else if s.This == '*' && s.Next == scan.EndOfText {
			s.Skip()
			val.Var = true
		} else {
			s.Keep()
		}
	}
	val.Kind = s.Emit().Val
	return val
}

func genValList(f *os.File, name string, varName string, vals []string) {
	fmt.Fprintf(f, "%v: []string{", name)

	var variable bool
	var list []string
	for _, v := range vals {
		valDoc := parseValDoc(v)
		list = append(list, fmt.Sprintf("kinds.%v", valDoc.Kind))
		if valDoc.Var {
			variable = true
		}
	}
	fmt.Fprintf(f, "%v},\n", strings.Join(list, ", "))
	if variable {
		fmt.Fprintf(f, "%v: true,\n", varName)
	}
}

func opIdent(name string) (string, bool) {
	var s scan.Scanner
	s.InitFromString("", name)

	// Skip any names that are only symbols
	if !scan.IsLetter(s.This) {
		return "", false
	}
	s.Val.WriteRune(unicode.ToUpper(s.This))
	s.Skip()

	for s.HasMore() {
		if s.Next == '.' || s.Next == '-' {
			s.Keep()
			s.Skip()
			s.Val.WriteRune(unicode.ToUpper(s.This))
			s.Skip()
		} else {
			s.Keep()
		}
	}
	return s.Emit().Val, true
}
