//go:generate go run gen-ops.go

package main

import (
	"cmp"
	"fmt"
	"log"
	"os"
	"path"
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/blackchip-org/scan"
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/pkg/pretty"
)

type ValDef struct {
	Label string
	Type  string
	Var   bool
}

var (
	RootDir = path.Join("..", "..")
	DocDir  = path.Join(RootDir, "doc")
	OpsDir  = path.Join(RootDir, "ops")
	TestDir = path.Join(RootDir, "test", "docs")
	VolDir  = path.Join(RootDir, "vols")
)

func main() {
	defs, err := zc.LoadDefs()
	if err != nil {
		log.Panic(err)
	}
	genOps(defs)
	genVols(defs)
	genTests(defs)
	genOpDocs(defs)
	genIndex(defs)
}

func genOps(vols []zc.VolDef) {
	for _, vol := range vols {
		// Skip if there are no ops defined
		if len(vol.Ops) == 0 {
			continue
		}

		f, err := os.Create(path.Join(OpsDir, fileNameFor(vol.Name)+"_ops.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package ops\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/funcs\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/types\"\n")
		fmt.Fprintf(f, ")\n")

		fmt.Fprintf(f, "var (\n")
		for _, op := range vol.Ops {
			if op.Virtual {
				if hasFuncImpl(op) {
					panic(fmt.Errorf("operation is virtual but has functions: %v", op.Name))
				}
				fmt.Fprintf(f, "%v = zc.Op{Name: \"%v\", Virtual: true}\n", op.Ident, op.Name)
				continue
			}
			for i, fn := range op.Funcs {
				if !hasFuncImpl(op) {
					panic(fmt.Errorf("operation must be virtual if it has no functions: %v", op.Name))
				}
				if fn.Name == "" && i > 0 {
					continue
				}
				fmt.Fprintf(f, "%v = zc.Op{\n", fn.Ident)
				fmt.Fprintf(f, "Name: \"%v\",\n", op.Name)
				if op.Overloads != "" {
					fmt.Fprintf(f, "Overloads: \"%v\",\n", op.Overloads)
				}
				if fn.Name != "" {
					genValList(f, "Params", "VarParam", fn.Params)
					genValList(f, "Returns", "VarReturn", fn.Returns)
					fmt.Fprintf(f, "Func: funcs.%v,\n", fn.Name)
				}
				fmt.Fprintf(f, "}\n")
			}
		}
		fmt.Fprintf(f, ")\n")
	}
}

func genVols(vols []zc.VolDef) {
	for _, vol := range vols {
		f, err := os.Create(path.Join(VolDir, fileNameFor(vol.Name)+"_vol.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package vols\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/ops\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/types\"\n")
		fmt.Fprintf(f, ")\n")

		fmt.Fprintf(f, "var %v = zc.Vol{\n", vol.Ident)
		fmt.Fprintf(f, "Name: \"%v\",\n", vol.Name)
		if len(vol.Types) > 0 {
			fmt.Fprintf(f, "Types: []zc.Type{\n")
			for _, t := range vol.Types {
				fmt.Fprintf(f, "types.%v,\n", typeNameFor(t))
			}
			fmt.Fprintf(f, "},\n")
		}
		if len(vol.Ops) > 0 {
			fmt.Fprintf(f, "Ops: []zc.Op{\n")
			for _, o := range vol.Ops {
				if !hasFuncImpl(o) {
					continue
				}
				if o.Macro != "" {
					continue
				}
				for i, fn := range o.Funcs {
					if i > 0 && fn.Name == "" {
						continue
					}
					if fn.Ident != "" {
						fmt.Fprintf(f, "ops.%v,\n", fn.Ident)
					}
				}
			}
			fmt.Fprintf(f, "},\n")
			fmt.Fprintf(f, "Macros: []zc.Macro{\n")
			for _, o := range vol.Ops {
				if o.Macro != "" {
					fmt.Fprintf(f, "{Name: \"%v\", Expr: \"%v\"},\n", o.Name, o.Macro)
				}
				for _, a := range o.Aliases {
					fmt.Fprintf(f, "{Name: \"%v\", Expr: \"%v\"},\n", a, o.Name)
				}
			}
			fmt.Fprintf(f, "},\n")
		}
		fmt.Fprintf(f, "}\n")
	}
}

func genTests(vols []zc.VolDef) {
	for _, vol := range vols {
		if len(vol.Ops) == 0 {
			continue
		}
		f, err := os.Create(path.Join(TestDir, fileNameFor(vol.Name)+"_test.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package doc_tests\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"testing\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/calc\"\n")
		fmt.Fprintf(f, ")\n")

		for _, op := range vol.Ops {
			if len(op.Example) > 0 {
				genTest(f, vol.Ident+"_"+op.Ident, op.Example)
			}
			for _, test := range op.Tests {
				genTest(f, vol.Ident+"_"+op.Ident+"_"+test.Name, test.Test)
			}
		}
	}
}

func genTest(f *os.File, name string, test []zc.Expect) {
	fmt.Fprintf(f, "func TestOpDocs_%v(t *testing.T) {\n", name)
	fmt.Fprintf(f, "c := calc.New()\n")
	fmt.Fprintf(f, "ct := zc.NewCalcTester(c, t)\n")
	for _, e := range test {
		fmt.Fprintf(f, "\nct.Eval(\"%v\")\n", e.Input)
		if e.Error != "" {
			fmt.Fprintf(f, "ct.AssertError(\"%v\")\n", e.Error)
		} else if e.Info != "" {
			fmt.Fprintf(f, "ct.AssertInfo(\"%v\")\n", e.Info)
		} else {
			fmt.Fprintf(f, "ct.AssertStack(")
			for i, out := range e.Output {
				fmt.Fprintf(f, "\"%v\"", out)
				if i < len(e.Output)-1 {
					fmt.Fprintf(f, ", ")
				}
			}
			fmt.Fprintf(f, ")\n")
		}
	}
	fmt.Fprintf(f, "}\n\n")
}

func genOpDocs(vols []zc.VolDef) {
	for _, vol := range vols {
		name := strings.ReplaceAll(vol.Name, "/", "_") + ".md"
		f, err := os.Create(path.Join(DocDir, "ops", name))
		if err != nil {
			log.Panic(err)
		}

		fmt.Fprintf(f, "<!-- Document generated by \"gen-ops\"; DO NOT EDIT. -->\n")
		fmt.Fprintf(f, "\n")
		fmt.Fprintf(f, "# %v\n\n", vol.Name)
		fmt.Fprintf(f, "%v\n\n", vol.Title)
		if vol.Overview != "" {
			fmt.Fprintf(f, "## Overview\n\n")
			fmt.Fprintf(f, vol.Overview)
			fmt.Fprintf(f, "\n")
		}
		fmt.Fprintf(f, "## Index\n\n")

		tab := pretty.NewMarkdownTable(2)
		tab.Heading("Operation", "Description")

		for _, op := range vol.Ops {
			names := strings.Join(append([]string{op.Name}, op.Aliases...), ", ")
			anchor := strings.ReplaceAll(op.Name, "?", "")
			entry := fmt.Sprintf("[`%v`](#%v)", names, anchor)
			tab.Row(entry, op.Title)
		}
		fmt.Fprint(f, tab.Format())
		fmt.Fprintf(f, "\n## Operations\n")

		for _, op := range vol.Ops {
			genOpDoc(f, op)
		}
	}
}

func genOpDoc(f *os.File, op zc.OpDef) {
	fmt.Fprintf(f, "\n### %v\n\n", op.Name)
	fmt.Fprintf(f, "%v\n\n", op.Desc)
	if len(op.Aliases) > 0 {
		if len(op.Aliases) == 1 {
			fmt.Fprintf(f, "Alias: ")
		} else {
			fmt.Fprintf(f, "Aliases: ")
		}
		var fmtAliases []string
		for _, a := range op.Aliases[1:] {
			fmtAliases = append(fmtAliases, fmt.Sprintf("`%v`", a))
		}
		fmt.Fprintf(f, "%v\n\n", strings.Join(fmtAliases, ", "))
	}

	if len(op.Funcs) > 0 {
		fmt.Fprintf(f, "```\n")
		for _, fn := range op.Funcs {
			fmt.Fprintf(f, "( ")
			fmt.Fprintf(f, "%v -- ", strings.Join(fn.Params, " "))
			fmt.Fprintf(f, "%v )\n", strings.Join(fn.Returns, " "))
		}
		fmt.Fprintf(f, "```\n")
		fmt.Fprintln(f, "")
	}
	if op.Macro != "" {
		fmt.Fprintf(f, "```\n")
		fmt.Fprintf(f, "def %v %v\n", op.Name, op.Macro)
		fmt.Fprintf(f, "```\n")
		fmt.Fprintln(f, "")
	}

	if len(op.Example) > 0 {
		fmt.Fprintf(f, "Example:\n\n")
		genOpExample(f, op.Example)
	}
}

func genOpExample(f *os.File, expected []zc.Expect) {
	tab := pretty.NewMarkdownTable(2)
	tab.Heading("Input", "Stack")
	for _, ex := range expected {
		o := strings.Join(ex.Output, " \\| ")
		quotes := "`"
		if strings.HasPrefix(o, "*") || o == "" {
			quotes = ""
		}
		tab.Row("`"+ex.Input+"`", quotes+o+quotes)
	}
	fmt.Fprint(f, tab.Format())
}

type entry struct {
	name   string
	anchor string
	title  string
}

var entrySort = func(a, b entry) int {
	return cmp.Compare(a.name, b.name)
}

func genIndex(vols []zc.VolDef) {
	f, err := os.Create(path.Join(DocDir, "index.md"))
	if err != nil {
		log.Panic(err)
	}
	defer f.Close()

	var entries []entry
	subs := make(map[string][]entry)

	for _, vol := range vols {
		for _, op := range vol.Ops {
			slash := strings.Index(op.Name, "/")
			if slash != -1 {
				prefix := op.Name[:slash]
				e := entry{
					name:   op.Name,
					anchor: anchor(vol, op),
				}
				entries := subs[prefix]
				entries = append(entries, e)
				subs[prefix] = entries
				continue
			}
			e := entry{
				name:   op.Name,
				anchor: anchor(vol, op),
				title:  op.Title,
			}
			entries = append(entries, e)
			for _, a := range op.Aliases {
				e2 := entry{
					name:   a,
					anchor: anchor(vol, op),
					title:  fmt.Sprintf("Alias for [%v](%v)", e.name, e.anchor),
				}
				entries = append(entries, e2)
			}
		}
	}

	slices.SortStableFunc(entries, entrySort)

	fmt.Fprintf(f, "<!-- Document generated by \"gen-ops\"; DO NOT EDIT. -->\n")
	fmt.Fprintf(f, "\n")
	fmt.Fprintf(f, "# index\n\n")

	section := rune(0)
	for _, e := range entries {
		ch, _ := utf8.DecodeRuneInString(e.name)
		if ch != section && unicode.IsLetter(ch) {
			section = ch
			fmt.Fprintf(f, "\n## %c\n", ch)
		}
		fmt.Fprintf(f, "- [%v](%v): %v\n", e.name, e.anchor, e.title)
		entries, ok := subs[e.name]
		if ok {
			slices.SortStableFunc(entries, entrySort)
			for _, e := range entries {
				fmt.Fprintf(f, "  - [%v](%v)\n", e.name, e.anchor)
			}
		}
	}
}

func parseValDoc(v string) ValDef {
	s := scan.NewScannerFromString("", v)
	var val ValDef
	for s.HasMore() {
		if s.This == ':' {
			s.Skip()
			val.Label = s.Emit().Val
		} else if s.This == '*' && s.Next == scan.EndOfText {
			s.Skip()
			val.Var = true
		} else {
			s.Keep()
		}
	}
	val.Type = s.Emit().Val
	return val
}

func genValList(f *os.File, name string, varName string, vals []string) {
	fmt.Fprintf(f, "%v: []zc.Type{", name)

	var var_ string
	var list []string
	for _, v := range vals {
		valDoc := parseValDoc(v)
		if valDoc.Var {
			var_ = typeNameFor(valDoc.Type)
		} else {
			list = append(list, fmt.Sprintf("types.%v", typeNameFor(valDoc.Type)))
		}
	}
	fmt.Fprintf(f, "%v},\n", strings.Join(list, ", "))
	if var_ != "" {
		fmt.Fprintf(f, "%v: types.%v,\n", varName, var_)
	}
}

func hasFuncImpl(op zc.OpDef) bool {
	found := false
	for _, fn := range op.Funcs {
		if fn.Name != "" {
			found = true
			break
		}
	}
	return found
}

func fileNameFor(p string) string {
	return strings.ReplaceAll(p, "/", "_")
}

func typeNameFor(p string) string {
	parts := strings.Split(p, "/")
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.ToUpper(parts[i])
	}
	return strings.Join(parts, "")
}

func anchor(vol zc.VolDef, op zc.OpDef) string {
	return fmt.Sprintf("ops/%v.md#%v", fileNameFor(vol.Name), op.Name)
}
