//go:generate go run gen-ops.go

package main

import (
	"cmp"
	"fmt"
	"log"
	"os"
	"path"
	"slices"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/blackchip-org/scan"
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/pkg/pretty"
)

var typeMap map[string]string

func init() {
	typeMap = make(map[string]string)
	for _, t := range zc.Types {
		typeMap[t.AppName()] = t.Name()
	}
}

type ValDef struct {
	Label string
	Type  string
	Var   bool
}

var (
	RootDir   = path.Join("..", "..")
	DocDir    = path.Join(RootDir, "doc")
	DocOpsDir = path.Join(DocDir, "ops")
	OpsDir    = path.Join(RootDir, "app", "ops")
	TestDir   = path.Join(RootDir, "app", "test", "ops")
	VolDir    = path.Join(RootDir, "app", "vols")
)

func main() {
	defs, err := zc.LoadDefs()
	if err != nil {
		log.Panic(err)
	}
	genOps(defs)
	genVols(defs)
	genTests(defs)
	genOpDocs(defs)
	genOpRef(defs)
	genIndex(defs)
}

func genOps(vols []zc.VolDef) {
	if err := os.MkdirAll(OpsDir, 0755); err != nil {
		log.Fatalf("unable to make directory: %v: %v", OpsDir, err)
	}

	for _, vol := range vols {
		// Skip if there are no ops defined
		if len(vol.Ops) == 0 {
			continue
		}

		f, err := os.Create(path.Join(OpsDir, fileNameFor(vol.Name)+"_ops.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package ops\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/app/funcs\"\n")
		fmt.Fprintf(f, ")\n")

		fmt.Fprintf(f, "var (\n")
		for _, op := range vol.Ops {
			if op.Stub {
				continue
			}
			fmt.Fprintf(f, "%v = zc.Op{\n", op.Ident)
			fmt.Fprintf(f, "Name: \"%v\",\n", op.Name)
			fmt.Fprintf(f, "Funcs: []zc.Func{\n")
			for _, fn := range op.Funcs {
				if fn.Name == "" {
					log.Panicf("func without name in op: %v", op.Name)
				}
				fmt.Fprintf(f, "{\n")
				genValList(f, "Params", "VarParam", fn.Params)
				genValList(f, "Returns", "VarReturn", fn.Returns)
				fmt.Fprintf(f, "Eval: funcs.%v,\n", fn.Name)
				fmt.Fprintf(f, "},\n") // End Func
			}
			fmt.Fprintf(f, "},\n") // End Funcs
			fmt.Fprintf(f, "}\n")  // End Op
		}
		fmt.Fprintf(f, ")\n")
	}
}

func genVols(vols []zc.VolDef) {
	if err := os.MkdirAll(VolDir, 0755); err != nil {
		log.Fatalf("unable to make directory: %v: %v", VolDir, err)
	}
	for _, vol := range vols {
		f, err := os.Create(path.Join(VolDir, fileNameFor(vol.Name)+"_vol.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package vols\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/app/ops\"\n")
		fmt.Fprintf(f, ")\n")

		fmt.Fprintf(f, "var %v = zc.Vol{\n", vol.Ident)
		fmt.Fprintf(f, "Name: \"%v\",\n", vol.Name)

		fmt.Fprintf(f, "Ops: []zc.Op{\n")
		for _, o := range vol.Ops {
			if o.Macro != "" || o.Stub {
				continue
			}
			fmt.Fprintf(f, "ops.%v,\n", o.Ident)
		}
		fmt.Fprintf(f, "},\n")
		fmt.Fprintf(f, "Macros: []zc.Macro{\n")
		for _, o := range vol.Ops {
			if o.Stub {
				continue
			}
			if o.Macro != "" {
				fmt.Fprintf(f, "{Name: \"%v\", Expr: \"%v\"},\n", o.Name, o.Macro)
			}
			for _, a := range o.Aliases {
				fmt.Fprintf(f, "{Name: \"%v\", Expr: \"%v\"},\n", a, o.Name)
			}
		}
		for _, row := range vol.Table {
			if len(row) < 2 || len(row) > 3 {
				log.Fatalf("expected 2 or 3 columns in row, got: %v", row)
			}
			fmt.Fprintf(f, "{Name: \"%v\", Expr: \"%v\"},\n", row[0], row[1])
		}
		fmt.Fprintf(f, "},\n")
		fmt.Fprintf(f, "}\n")
	}
}

func genTests(vols []zc.VolDef) {
	if err := os.MkdirAll(TestDir, 0755); err != nil {
		log.Fatalf("unable to make directory: %v: %v", TestDir, err)
	}
	for _, vol := range vols {
		if len(vol.Ops) == 0 {
			continue
		}
		f, err := os.Create(path.Join(TestDir, fileNameFor(vol.Name)+"_test.go"))
		if err != nil {
			log.Panic(err)
		}
		defer f.Close()

		fmt.Fprintf(f, "package doc_tests\n\n")
		fmt.Fprintf(f, "// Code generated by 'gen-ops'; DO NOT EDIT.\n\n")
		fmt.Fprintf(f, "import (\n")
		fmt.Fprintf(f, "\"testing\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6\"\n")
		fmt.Fprintf(f, "\"github.com/blackchip-org/zc/v6/app\"\n")
		fmt.Fprintf(f, ")\n")

		for _, op := range vol.Ops {
			if len(op.Example) > 0 {
				genTest(f, vol.Ident+"_"+op.Ident, vol.Setup, op.Example)
			}
			for _, test := range op.Tests {
				genTest(f, vol.Ident+"_"+op.Ident+"_"+test.Name, vol.Setup, test.Test)
			}
		}
	}
}

func genTest(f *os.File, name string, setup []string, test []zc.Expect) {
	fmt.Fprintf(f, "func TestOpDocs_%v(t *testing.T) {\n", name)
	fmt.Fprintf(f, "c := app.NewCalcTester(t)\n")

	if len(setup) > 0 {
		fmt.Fprintln(f)
		for _, s := range setup {
			fmt.Fprintf(f, "c.Eval(\"%v\")\n", s)
		}
		fmt.Fprintln(f)
	}

	for _, e := range test {
		fmt.Fprintf(f, "\nc.Eval(\"%v\")\n", e.Input)
		if e.Error != "" {
			fmt.Fprintf(f, "c.AssertError(\"%v\")\n", e.Error)
		} else if e.Notice != "" {
			fmt.Fprintf(f, "c.AssertNotice(\"%v\")\n", e.Notice)
		} else {
			fmt.Fprintf(f, "c.AssertStack(")
			for i, out := range e.Output {
				fmt.Fprintf(f, "\"%v\"", out)
				if i < len(e.Output)-1 {
					fmt.Fprintf(f, ", ")
				}
			}
			fmt.Fprintf(f, ")\n")
		}
	}
	fmt.Fprintf(f, "}\n\n")
}

func genOpDocs(vols []zc.VolDef) {
	if err := os.MkdirAll(DocOpsDir, 0755); err != nil {
		log.Fatalf("unable to make directory: %v: %v", DocOpsDir, err)
	}

	for _, vol := range vols {
		name := strings.ReplaceAll(vol.Name, "/", "_") + ".md"
		f, err := os.Create(path.Join(DocOpsDir, name))
		if err != nil {
			log.Panic(err)
		}

		fmt.Fprintf(f, "<!-- Document generated by \"gen-ops\"; DO NOT EDIT. -->\n")
		fmt.Fprintf(f, "\n")
		fmt.Fprintf(f, "# %v\n\n", vol.Name)
		fmt.Fprintf(f, "%v\n\n", vol.Title)
		if vol.Overview != "" {
			fmt.Fprintf(f, "## Overview\n\n")
			fmt.Fprintf(f, vol.Overview)
			fmt.Fprintf(f, "\n")
		}

		fmt.Fprintf(f, "## Index\n\n")

		if len(vol.Ops) > 0 {
			tab := pretty.NewMarkdownTable(2)
			tab.Heading("Operation", "Description")

			for _, op := range vol.Ops {
				var names []string
				names = append(names, op.Name)
				names = append(names, op.Aliases...)

				fmtNames := strings.Join(names, ", ")
				entry := fmt.Sprintf("[`%v`](#%v)", fmtNames, anchor(op.Name))
				title := op.Title
				if op.Subtitle != "" {
					title += ", " + op.Subtitle
				}
				tab.Row(entry, title)
			}
			fmt.Fprint(f, tab.Format())
			fmt.Fprintln(f)
		}

		if len(vol.Table) > 0 {
			cols := len(vol.Table[0])
			if cols < 2 || cols > 3 {
				log.Fatalf("expected 2 or 3 row entries, got: %v", cols)
			}

			tab := pretty.NewMarkdownTable(cols)
			if cols == 3 {
				tab.Heading("Name", "Value", "Description")
			} else {
				tab.Heading("Name", "Value")
			}

			for _, row := range vol.Table {
				if len(row) != cols {
					log.Fatalf("expected %v row entries, got: %v", cols, row)
				}
				drow := slices.Clone(row)
				if vol.RemoveSlash && drow[1][0] == '/' {
					drow[1] = drow[1][1:]
				}
				drow[0] = "`" + drow[0] + "`"
				drow[1] = "`" + drow[1] + "`"
				tab.Row(drow...)
			}
			fmt.Fprint(f, tab.Format())
			fmt.Fprintln(f)
		}

		// Find related volumes
		var rels []zc.VolDef
		for _, vol2 := range vols {
			idx := strings.Index(vol2.Name, "/")
			if idx >= 0 {
				parent := vol2.Name[:idx]
				if parent == vol.Name {
					rels = append(rels, vol2)
				}
			}
		}

		if len(rels) > 0 {
			slices.SortFunc(rels, func(a, b zc.VolDef) int {
				return cmp.Compare(a.Name, b.Name)
			})
			fmt.Fprintf(f, "## Related Volumes\n\n")
			for _, r := range rels {
				fmt.Fprintf(f, "- [%v](%v.md)\n", r.Name, fileNameFor(r.Name))
			}
			fmt.Fprintf(f, "\n")
		}

		if len(vol.Ops) > 0 {
			fmt.Fprintf(f, "\n## Operations\n")

			for _, op := range vol.Ops {
				genOpDoc(f, op)
			}
		}
	}
}

func genOpDoc(f *os.File, op zc.OpDef) {
	fmt.Fprintf(f, "\n### %v\n\n", op.Name)
	fmt.Fprintf(f, "%v\n\n", op.Desc)

	if len(op.Aliases) > 0 {
		if len(op.Aliases) == 1 {
			fmt.Fprintf(f, "Alias: ")
		} else {
			fmt.Fprintf(f, "Aliases: ")
		}
		var fmtAliases []string
		for _, a := range op.Aliases {
			fmtAliases = append(fmtAliases, fmt.Sprintf("`%v`", a))
		}
		fmt.Fprintf(f, "%v\n\n", strings.Join(fmtAliases, ", "))
	}

	if len(op.Funcs) > 0 {
		fmt.Fprintf(f, "Stack effects:\n```\n")
		for _, fn := range op.Funcs {
			fmt.Fprintf(f, "( ")
			fmt.Fprintf(f, "%v -- ", strings.Join(fn.Params, " "))
			fmt.Fprintf(f, "%v )\n", strings.Join(fn.Returns, " "))
		}
		fmt.Fprintf(f, "```\n")
		fmt.Fprintln(f, "")
	}
	if op.Macro != "" {
		fmt.Fprintf(f, "Macro definition:\n")
		fmt.Fprintf(f, "```\n")
		fmt.Fprintf(f, "def %v %v\n", op.Name, op.Macro)
		fmt.Fprintf(f, "```\n")
		fmt.Fprintln(f, "")
	}

	if len(op.Example) > 0 {
		fmt.Fprintf(f, "Example:\n\n")
		genOpExample(f, op.Example)
	}
}

func genOpExample(f *os.File, expected []zc.Expect) {
	tab := pretty.NewMarkdownTable(2)
	tab.Heading("Input", "Stack")
	for _, ex := range expected {
		i := "`" + ex.Input + "`"
		if ex.Notice != "" {
			tab.Row(i, "*"+ex.Notice+"*")
		} else if ex.Error != "" {
			tab.Row(i, "_"+ex.Error+"_")
		} else if len(ex.Output) == 0 {
			tab.Row(i, "")
		} else {
			o := strings.Join(ex.Output, " \\| ")
			tab.Row(i, "`"+o+"`")
		}
	}
	fmt.Fprint(f, tab.Format())
}

type entry struct {
	name   string
	anchor string
	title  string
}

var entrySort = func(a, b entry) int {
	return cmp.Compare(a.name, b.name)
}

func genIndex(vols []zc.VolDef) {
	f, err := os.Create(path.Join(DocDir, "index.md"))
	if err != nil {
		log.Panic(err)
	}
	defer f.Close()

	var entries []entry
	names := make(map[string]struct{})
	overloads := make(map[string]struct{})
	subs := make(map[string][]entry)

	for _, vol := range vols {
		if vol.NoIndex {
			continue
		}
		for _, op := range vol.Ops {
			names[op.Name] = struct{}{}
			slash := strings.Index(op.Name, "/")
			if slash != -1 {
				prefix := op.Name[:slash]
				title := vol.Subtitle
				if title == "" {
					title = op.Title
					if op.Subtitle != "" {
						title = op.Subtitle
					}
				}
				e := entry{
					name:   op.Name,
					anchor: opsAnchor(vol, op),
					title:  title,
				}
				entries := subs[prefix]
				entries = append(entries, e)
				subs[prefix] = entries
				continue
			} else if op.Subtitle != "" {
				e := entry{
					name:   op.Name,
					anchor: opsAnchor(vol, op),
					title:  op.Subtitle,
				}
				entries := subs[op.Name]
				entries = append(entries, e)
				subs[op.Name] = entries
				continue
			}
			if op.Stub {
				e := entry{
					name:  op.Name,
					title: op.Title,
				}
				entries = append(entries, e)
				continue
			}
			e := entry{
				name:   op.Name,
				anchor: opsAnchor(vol, op),
				title:  op.Title,
			}
			entries = append(entries, e)
			for _, a := range op.Aliases {
				e2 := entry{
					name:   a,
					anchor: opsAnchor(vol, op),
					title:  fmt.Sprintf("Alias for [%v](%v)", e.name, e.anchor),
				}
				entries = append(entries, e2)
			}
		}
		for _, row := range vol.Table {
			name := row[0]
			var title string
			if len(row) == 3 {
				title = row[2]
			} else {
				title = row[1]
			}
			e := entry{
				name:   name,
				anchor: volAnchor(vol),
				title:  title,
			}
			entries = append(entries, e)
		}
	}

	// Find operations that overload but don't yet have an entry for the
	// overloaded operation.
	for ov := range overloads {
		if _, ok := names[ov]; !ok {
			e := entry{
				name: ov,
			}
			entries = append(entries, e)
		}
	}

	slices.SortStableFunc(entries, entrySort)

	fmt.Fprintf(f, "<!-- Document generated by \"gen-ops\"; DO NOT EDIT. -->\n")
	fmt.Fprintf(f, "\n")
	fmt.Fprintf(f, "# Index\n\n")

	section := rune(0)
	seen := make(map[string]struct{})

	for _, e := range entries {
		if _, ok := seen[e.name]; ok {
			fmt.Printf("[WARN]: %v repeated\n", e.name)
		}
		seen[e.name] = struct{}{}

		ch, _ := utf8.DecodeRuneInString(e.name)
		if ch != section && unicode.IsLetter(ch) {
			section = ch
			fmt.Fprintf(f, "\n## %c\n", ch)
		}

		if e.anchor == "" {
			fmt.Fprintf(f, "- `%v`: %v\n", e.name, e.title)
		} else if e.title != "" {
			fmt.Fprintf(f, "- [`%v`](%v): %v\n", e.name, e.anchor, e.title)
		} else {
			fmt.Fprintf(f, "- `%v`\n", e.name)
		}
		entries, ok := subs[e.name]
		if ok {
			slices.SortStableFunc(entries, entrySort)
			for _, e := range entries {
				fmt.Fprintf(f, "  - [`%v`](%v): %v\n", e.name, e.anchor, e.title)
			}
		}
	}
}

func genOpRef(vols []zc.VolDef) {
	f, err := os.Create(path.Join(DocDir, "ops.md"))
	if err != nil {
		log.Panic(err)
	}
	defer f.Close()

	refs := make(map[string][]zc.VolDef)
	for _, cat := range zc.Categories {
		refs[cat.ID] = make([]zc.VolDef, 0)
	}

	for _, vol := range vols {
		if vol.Category == "" {
			continue
		}
		if vol.Subtitle != "" {
			continue
		}
		ref, ok := refs[vol.Category]
		if !ok {
			panic(fmt.Errorf("invalid category %v in volume %v", vol.Category, vol.Name))
		}
		ref = append(ref, vol)
		refs[vol.Category] = ref
	}

	fmt.Fprintf(f, "<!-- Document generated by \"gen-ops\"; DO NOT EDIT. -->\n")
	fmt.Fprintf(f, "\n")
	fmt.Fprintf(f, "# Operation Reference\n\n")

	for _, cat := range zc.Categories {
		fmt.Fprintf(f, "\n## %v\n", cat.Title)
		tab := pretty.NewMarkdownTable(2)
		tab.Heading("Volume", "Description")
		vols := refs[cat.ID]
		slices.SortFunc(vols, func(a, b zc.VolDef) int {
			return cmp.Compare(a.Name, b.Name)
		})
		for _, vol := range vols {
			name := fmt.Sprintf("[%v](ops/%v.md)", vol.Name, vol.Name)
			tab.Row(name, vol.Title)
		}
		fmt.Fprintf(f, "%v\n\n", tab.Format())
	}
}

func parseValDoc(v string) ValDef {
	s := scan.NewScannerFromString("", v)
	var val ValDef
	for s.HasMore() {
		if s.This == ':' {
			s.Skip()
			val.Label = s.Emit().Val
		} else if s.This == '*' && s.Next == scan.EndOfText {
			s.Skip()
			val.Var = true
		} else {
			s.Keep()
		}
	}
	val.Type = s.Emit().Val
	return val
}

func genValList(f *os.File, name string, varName string, vals []string) {
	fmt.Fprintf(f, "%v: []zc.Type{", name)

	vals = slices.Clone(vals)
	slices.Reverse(vals)
	var var_ string
	var list []string
	for _, v := range vals {
		valDoc := parseValDoc(v)
		if valDoc.Var {
			var_ = typeNameFor(valDoc.Type)
		} else {
			list = append(list, fmt.Sprintf("zc.%v", typeNameFor(valDoc.Type)))
		}
	}
	fmt.Fprintf(f, "%v},\n", strings.Join(list, ", "))
	if var_ != "" {
		fmt.Fprintf(f, "%v: zc.%v,\n", varName, var_)
	}
}

func fileNameFor(p string) string {
	return strings.ReplaceAll(p, "/", "_")
}

func typeNameFor(p string) string {
	n, ok := typeMap[p]
	if !ok {
		panic("unknown type: " + p)
	}
	return n
}

func opsAnchor(vol zc.VolDef, op zc.OpDef) string {
	name := anchor(op.Name)
	return fmt.Sprintf("ops/%v.md#%v", fileNameFor(vol.Name), name)
}

func volAnchor(vol zc.VolDef) string {
	return fmt.Sprintf("ops/%v.md", fileNameFor(vol.Name))
}

func anchor(s string) string {
	s = strings.ReplaceAll(s, ".", "")
	s = strings.ReplaceAll(s, "?", "")
	s = strings.ReplaceAll(s, "/", "")
	s = strings.ReplaceAll(s, "=", "")

	return s
}
