package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Dec = zc.Op{
		Name: "dec",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DMS},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.DecDMS,
			},
		},
	}
	DegRad = zc.Op{
		Name:  "deg-rad",
		Funcs: []zc.Func{},
	}
	DegMin = zc.Op{
		Name: "deg.min",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DMS},
				Returns: []zc.Type{zc.DMS},
				Eval:    funcs.DegMin,
			},
		},
	}
	DegMinRound = zc.Op{
		Name: "deg.min.round",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint, zc.DMS},
				Returns: []zc.Type{zc.DMS},
				Eval:    funcs.DegMinRound,
			},
		},
	}
	DegMinSec = zc.Op{
		Name: "deg.min.sec",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DMS},
				Returns: []zc.Type{zc.DMS},
				Eval:    funcs.DegMinSec,
			},
		},
	}
	DegMinSecRound = zc.Op{
		Name: "deg.min.sec.round",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint, zc.DMS},
				Returns: []zc.Type{zc.DMS},
				Eval:    funcs.DegMinSecRound,
			},
		},
	}
	DmsGet = zc.Op{
		Name: "dms?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.DMSIs,
			},
		},
	}
	MinutesDMS = zc.Op{
		Name: "minutes",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DMS},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.MinutesDMS,
			},
		},
	}
	RadDeg = zc.Op{
		Name:  "rad-deg",
		Funcs: []zc.Func{},
	}
	SecondsDMS = zc.Op{
		Name: "seconds",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DMS},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.SecondsDMS,
			},
		},
	}
)
