package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Label = zc.Op{
		Name:    "label",
		Params:  []zc.Type{zc.Any, zc.String},
		Returns: []zc.Type{zc.Any},
		Func:    funcs.Label,
	}
	Unit = zc.Op{
		Name:    "unit",
		Params:  []zc.Type{zc.Any, zc.String},
		Returns: []zc.Type{zc.Any},
		Func:    funcs.Unit,
	}
)
