package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Label = zc.Op{
		Name: "label",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String, zc.Any},
				Returns: []zc.Type{zc.Any},
				Eval:    funcs.Label,
			},
		},
	}
	Unit = zc.Op{
		Name: "unit",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String, zc.Any},
				Returns: []zc.Type{zc.Any},
				Eval:    funcs.Unit,
			},
		},
	}
)
