package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddDecimalSS = zc.Op{
		Name:    "add/d/ss",
		Params:  []zc.Type{zc.DecimalSS, zc.DecimalSS},
		Returns: []zc.Type{zc.DecimalSS},
		Func:    funcs.AddDecimalSS,
	}
	DivDecimalSS = zc.Op{
		Name:    "div/d/ss",
		Params:  []zc.Type{zc.DecimalSS, zc.DecimalSS},
		Returns: []zc.Type{zc.DecimalSS},
		Func:    funcs.DivDecimalSS,
	}
	MulDecimalSS = zc.Op{
		Name:    "mul/d/ss",
		Params:  []zc.Type{zc.DecimalSS, zc.DecimalSS},
		Returns: []zc.Type{zc.DecimalSS},
		Func:    funcs.MulDecimalSS,
	}
	NegDecimalSS = zc.Op{
		Name:    "neg/d/ss",
		Params:  []zc.Type{zc.DecimalSS},
		Returns: []zc.Type{zc.DecimalSS},
		Func:    funcs.NegDecimalSS,
	}
	SubDecimalSS = zc.Op{
		Name:    "sub/d/ss",
		Params:  []zc.Type{zc.DecimalSS, zc.DecimalSS},
		Returns: []zc.Type{zc.DecimalSS},
		Func:    funcs.SubDecimalSS,
	}
)
