package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	DivBigInt = zc.Op{
		Name:    "div/i",
		Params:  []zc.Type{zc.BigInt, zc.BigInt},
		Returns: []zc.Type{zc.BigInt},
		Func:    funcs.DivBigInt,
	}
	SqrtBigInt = zc.Op{
		Name:    "sqrt/i",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.BigInt},
		Func:    funcs.SqrtBigInt,
	}
)
