package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddUint64 = zc.Op{
		Name:    "add/u64",
		Params:  []zc.Type{zc.Uint64, zc.Uint64},
		Returns: []zc.Type{zc.Uint64},
		Func:    funcs.AddUint64,
	}
)
