package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddF = zc.Op{
		Name: "add/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.AddBigFloat,
			},
		},
	}
	DivF = zc.Op{
		Name: "div/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.DivBigFloat,
			},
		},
	}
	MulF = zc.Op{
		Name: "mul/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.MulBigFloat,
			},
		},
	}
	NegF = zc.Op{
		Name: "neg/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.NegBigFloat,
			},
		},
	}
	SignF = zc.Op{
		Name: "sign/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.SignBigFloat,
			},
		},
	}
	SqrtF = zc.Op{
		Name: "sqrt/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.SqrtBigFloat,
			},
		},
	}
	SubF = zc.Op{
		Name: "sub/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.SubBigFloat,
			},
		},
	}
)
