package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	Add  = zc.Op{Name: "add", Virtual: true}
	Cbrt = zc.Op{Name: "cbrt", Virtual: true}
	Div  = zc.Op{Name: "div", Virtual: true}
	Mod  = zc.Op{Name: "mod", Virtual: true}
	Mul  = zc.Op{Name: "mul", Virtual: true}
	Neg  = zc.Op{Name: "neg", Virtual: true}
	Pow  = zc.Op{Name: "pow", Virtual: true}
	Rem  = zc.Op{Name: "rem", Virtual: true}
	Sign = zc.Op{Name: "sign", Virtual: true}
	Sqrt = zc.Op{Name: "sqrt", Virtual: true}
	Sub  = zc.Op{Name: "sub", Virtual: true}
)
