package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddBigFloat = zc.Op{
		Name:    "add/f",
		Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns: []zc.Type{zc.BigFloat},
		Func:    funcs.AddBigFloat,
	}
	DivBigFloat = zc.Op{
		Name:    "div/f",
		Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns: []zc.Type{zc.BigFloat},
		Func:    funcs.DivBigFloat,
	}
	MulBigFloat = zc.Op{
		Name:    "mul/f",
		Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns: []zc.Type{zc.BigFloat},
		Func:    funcs.MulBigFloat,
	}
	NegBigFloat = zc.Op{
		Name:    "neg/f",
		Params:  []zc.Type{zc.BigFloat},
		Returns: []zc.Type{zc.BigFloat},
		Func:    funcs.NegBigFloat,
	}
	SignBigFloat = zc.Op{
		Name:    "sign/f",
		Params:  []zc.Type{zc.BigFloat},
		Returns: []zc.Type{zc.Int},
		Func:    funcs.SignBigFloat,
	}
	SqrtBigFloat = zc.Op{
		Name:    "sqrt/f",
		Params:  []zc.Type{zc.BigFloat},
		Returns: []zc.Type{zc.BigFloat},
		Func:    funcs.SqrtBigFloat,
	}
	SubBigFloat = zc.Op{
		Name:    "sub/f",
		Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns: []zc.Type{zc.BigFloat},
		Func:    funcs.SubBigFloat,
	}
)
