package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Add = zc.Op{
		Name: "add",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.AddBigInt,
			},
		},
	}
	DivI = zc.Op{
		Name: "div/i",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.DivBigInt,
			},
		},
	}
)
