package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddDecimal = zc.Op{
		Name:      "add/d",
		Overloads: "add",
		Params:    []zc.Type{zc.Decimal, zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.AddDecimal,
	}
	CbrtDecimal = zc.Op{
		Name:      "cube.root/d",
		Overloads: "cube.root",
		Params:    []zc.Type{zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.CbrtDecimal,
	}
	DivDecimal = zc.Op{
		Name:      "div/d",
		Overloads: "div",
		Params:    []zc.Type{zc.Decimal, zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.DivDecimal,
	}
	MulDecimal = zc.Op{
		Name:      "mul/d",
		Overloads: "mul",
		Params:    []zc.Type{zc.Decimal, zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.MulDecimal,
	}
	NegDecimal = zc.Op{
		Name:      "neg/d",
		Overloads: "neg",
		Params:    []zc.Type{zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.NegDecimal,
	}
	PowDecimal = zc.Op{
		Name:    "pow/d",
		Params:  []zc.Type{zc.Decimal, zc.Decimal},
		Returns: []zc.Type{zc.Decimal},
		Func:    funcs.PowDecimal,
	}
	RemDecimal = zc.Op{
		Name:      "rem/d",
		Overloads: "rem",
		Params:    []zc.Type{zc.Decimal, zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.RemDecimal,
	}
	SignDecimal = zc.Op{
		Name:      "sign/d",
		Overloads: "sign",
		Params:    []zc.Type{zc.Decimal},
		Returns:   []zc.Type{zc.Int},
		Func:      funcs.SignDecimal,
	}
	SqrtDecimal = zc.Op{
		Name:      "square.root/d",
		Overloads: "square.root",
		Params:    []zc.Type{zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.SqrtDecimal,
	}
	SubDecimal = zc.Op{
		Name:      "sub/d",
		Overloads: "sub",
		Params:    []zc.Type{zc.Decimal, zc.Decimal},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.SubDecimal,
	}
)
