package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddBigInt = zc.Op{
		Name:      "add/i",
		Overloads: "add",
		Params:    []zc.Type{zc.BigInt, zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.AddBigInt,
	}
	MulBigInt = zc.Op{
		Name:      "mul/i",
		Overloads: "mul",
		Params:    []zc.Type{zc.BigInt, zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.MulBigInt,
	}
	PowBigInt = zc.Op{
		Name:      "pow/i",
		Overloads: "pow",
		Params:    []zc.Type{zc.BigInt, zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.PowBigInt,
	}
	SqrtBigInt = zc.Op{
		Name:    "sqrt/i",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.BigInt},
		Func:    funcs.SqrtBigInt,
	}
	SubBigInt = zc.Op{
		Name:      "sub/i",
		Overloads: "sub",
		Params:    []zc.Type{zc.BigInt, zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.SubBigInt,
	}
)
