package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	SqrtComplex = zc.Op{
		Name:      "sqrt/c",
		Overloads: "sqrt",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.SqrtComplex,
	}
)
