package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddBigFloat = zc.Op{
		Name:      "add/f",
		Overloads: "add",
		Params:    []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns:   []zc.Type{zc.BigFloat},
		Func:      funcs.AddBigFloat,
	}
	DivBigFloat = zc.Op{
		Name:      "div/f",
		Overloads: "div",
		Params:    []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns:   []zc.Type{zc.BigFloat},
		Func:      funcs.DivBigFloat,
	}
	MulBigFloat = zc.Op{
		Name:      "mul/f",
		Overloads: "mul",
		Params:    []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns:   []zc.Type{zc.BigFloat},
		Func:      funcs.MulBigFloat,
	}
	NegBigFloat = zc.Op{
		Name:      "neg/f",
		Overloads: "neg",
		Params:    []zc.Type{zc.BigFloat},
		Returns:   []zc.Type{zc.BigFloat},
		Func:      funcs.NegBigFloat,
	}
	SignBigFloat = zc.Op{
		Name:      "sign/f",
		Overloads: "sign",
		Params:    []zc.Type{zc.BigFloat},
		Returns:   []zc.Type{zc.Int},
		Func:      funcs.SignBigFloat,
	}
	SqrtBigFloat = zc.Op{
		Name:      "square.root/f",
		Overloads: "square.root",
		Params:    []zc.Type{zc.BigFloat},
		Returns:   []zc.Type{zc.BigFloat},
		Func:      funcs.SqrtBigFloat,
	}
	SubBigFloat = zc.Op{
		Name:      "sub/f",
		Overloads: "sub",
		Params:    []zc.Type{zc.BigFloat, zc.BigFloat},
		Returns:   []zc.Type{zc.BigFloat},
		Func:      funcs.SubBigFloat,
	}
)
