package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AndBool = zc.Op{
		Name: "and",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Bool, zc.Bool},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.AndBool,
			},
		},
	}
	False = zc.Op{
		Name:  "false",
		Funcs: []zc.Func{},
	}
	NotBool = zc.Op{
		Name: "not",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Bool},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NotBool,
			},
		},
	}
	OrBool = zc.Op{
		Name: "or",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Bool, zc.Bool},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.OrBool,
			},
		},
	}
	True = zc.Op{
		Name:  "true",
		Funcs: []zc.Func{},
	}
)
