package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Eq = zc.Op{
		Name: "eq",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.EqBigInt,
			},
			{
				Params:  []zc.Type{zc.Decimal, zc.Decimal},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.EqDecimal,
			},
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.EqBigFloat,
			},
			{
				Params:  []zc.Type{zc.Rat, zc.Rat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.EqRat,
			},
			{
				Params:  []zc.Type{zc.Complex, zc.Complex},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.EqComplex,
			},
			{
				Params:  []zc.Type{zc.String, zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.EqString,
			},
		},
	}
	Gt = zc.Op{
		Name: "gt",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GtBigInt,
			},
			{
				Params:  []zc.Type{zc.Decimal, zc.Decimal},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GtDecimal,
			},
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GtBigFloat,
			},
			{
				Params:  []zc.Type{zc.Rat, zc.Rat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GtRat,
			},
			{
				Params:  []zc.Type{zc.String, zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GtString,
			},
		},
	}
	Gte = zc.Op{
		Name: "gte",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GteBigInt,
			},
			{
				Params:  []zc.Type{zc.Decimal, zc.Decimal},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GteDecimal,
			},
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GteBigFloat,
			},
			{
				Params:  []zc.Type{zc.Rat, zc.Rat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GteRat,
			},
			{
				Params:  []zc.Type{zc.String, zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.GteString,
			},
		},
	}
	Lt = zc.Op{
		Name: "lt",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LtBigInt,
			},
			{
				Params:  []zc.Type{zc.Decimal, zc.Decimal},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LtDecimal,
			},
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LtBigFloat,
			},
			{
				Params:  []zc.Type{zc.Rat, zc.Rat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LtRat,
			},
			{
				Params:  []zc.Type{zc.String, zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LtString,
			},
		},
	}
	Lte = zc.Op{
		Name: "lte",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LteBigInt,
			},
			{
				Params:  []zc.Type{zc.Decimal, zc.Decimal},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LteDecimal,
			},
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LteBigFloat,
			},
			{
				Params:  []zc.Type{zc.Rat, zc.Rat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LteRat,
			},
			{
				Params:  []zc.Type{zc.String, zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.LteString,
			},
		},
	}
	Neq = zc.Op{
		Name: "neq",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NeqBigInt,
			},
			{
				Params:  []zc.Type{zc.Decimal, zc.Decimal},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NeqDecimal,
			},
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NeqBigFloat,
			},
			{
				Params:  []zc.Type{zc.Rat, zc.Rat},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NeqRat,
			},
			{
				Params:  []zc.Type{zc.Complex, zc.Complex},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NeqComplex,
			},
			{
				Params:  []zc.Type{zc.String, zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.NeqString,
			},
		},
	}
	Sort = zc.Op{
		Name: "sort",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{},
				VarParam:  zc.Decimal,
				Returns:   []zc.Type{},
				VarReturn: zc.Decimal,
				Eval:      funcs.SortDecimal,
			},
			{
				Params:    []zc.Type{},
				VarParam:  zc.BigInt,
				Returns:   []zc.Type{},
				VarReturn: zc.BigInt,
				Eval:      funcs.SortBigInt,
			},
			{
				Params:    []zc.Type{},
				VarParam:  zc.Rat,
				Returns:   []zc.Type{},
				VarReturn: zc.Rat,
				Eval:      funcs.SortRat,
			},
			{
				Params:    []zc.Type{},
				VarParam:  zc.BigFloat,
				Returns:   []zc.Type{},
				VarReturn: zc.BigFloat,
				Eval:      funcs.SortBigFloat,
			},
			{
				Params:    []zc.Type{},
				VarParam:  zc.String,
				Returns:   []zc.Type{},
				VarReturn: zc.String,
				Eval:      funcs.SortString,
			},
		},
	}
	SortT = zc.Op{
		Name: "sort/t",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{},
				VarParam:  zc.String,
				Returns:   []zc.Type{},
				VarReturn: zc.String,
				Eval:      funcs.SortString,
			},
		},
	}
)
