package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	CmykRgb = zc.Op{
		Name: "cmyk-rgb",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint8, zc.Uint8, zc.Uint8, zc.Uint8},
				Returns: []zc.Type{zc.Uint8, zc.Uint8, zc.Uint8},
				Eval:    funcs.CMYKToRGB,
			},
		},
	}
	HslRgb = zc.Op{
		Name: "hsl-rgb",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Uint8, zc.Uint8, zc.Uint8},
				Eval:    funcs.HSLToRGB,
			},
		},
	}
	RgbCmyk = zc.Op{
		Name: "rgb-cmyk",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint8, zc.Uint8, zc.Uint8},
				Returns: []zc.Type{zc.Uint8, zc.Uint8, zc.Uint8, zc.Uint8},
				Eval:    funcs.RGBToCMYK,
			},
		},
	}
	RgbHsl = zc.Op{
		Name: "rgb-hsl",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint8, zc.Uint8, zc.Uint8},
				Returns: []zc.Type{zc.Float64, zc.Float64, zc.Float64},
				Eval:    funcs.RGBToHSL,
			},
		},
	}
)
