package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	SquareRootC = zc.Op{
		Name: "square.root/c",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.SqrtComplex,
			},
		},
	}
)
