package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	RoundingModeSet = zc.Op{
		Name: "rounding.mode=",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{},
				Eval:    funcs.RoundingModeSet,
			},
		},
	}
	RoundingModeGet = zc.Op{
		Name: "rounding.mode?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.String},
				Eval:    funcs.RoundingModeGet,
			},
		},
	}
)
