package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	E = zc.Op{
		Name:  "e",
		Funcs: []zc.Func{},
	}
	Pi = zc.Op{
		Name:  "pi",
		Funcs: []zc.Func{},
	}
)
