package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Md5 = zc.Op{
		Name: "md5",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Md5,
			},
		},
	}
	Rotate13 = zc.Op{
		Name: "rotate.13",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{zc.String},
				Eval:    funcs.Rotate13,
			},
		},
	}
	Sha1 = zc.Op{
		Name: "sha1",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha1,
			},
		},
	}
	Sha1Hmac = zc.Op{
		Name: "sha1.hmac",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data, zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha1Hmac,
			},
		},
	}
	Sha224 = zc.Op{
		Name: "sha224",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha224,
			},
		},
	}
	Sha224Hmac = zc.Op{
		Name: "sha224.hmac",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data, zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha224Hmac,
			},
		},
	}
	Sha256 = zc.Op{
		Name: "sha256",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha256,
			},
		},
	}
	Sha256Hmac = zc.Op{
		Name: "sha256.hmac",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data, zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha256Hmac,
			},
		},
	}
	Sha384 = zc.Op{
		Name: "sha384",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha384,
			},
		},
	}
	Sha384Hmac = zc.Op{
		Name: "sha384.hmac",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data, zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha384Hmac,
			},
		},
	}
	Sha512 = zc.Op{
		Name: "sha512",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha512,
			},
		},
	}
	Sha512Hmac = zc.Op{
		Name: "sha512.hmac",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Data, zc.Data},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.Sha512Hmac,
			},
		},
	}
)
