package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Dec = zc.Op{
		Name: "dec",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Decimal},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.Dec,
			},
			{
				Params:  []zc.Type{zc.Rat},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.DecRat,
			},
		},
	}
	RoundingModeD = zc.Op{
		Name: "rounding.mode/d",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{},
				Eval:    funcs.RoundingModeSet,
			},
		},
	}
	RoundingModeDQ = zc.Op{
		Name: "rounding.mode/d?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.String},
				Eval:    funcs.RoundingModeGet,
			},
		},
	}
	Trunc = zc.Op{
		Name: "trunc",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Decimal},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.Trunc,
			},
		},
	}
)
