package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddF = zc.Op{
		Name: "add/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AddFloat64,
			},
		},
	}
	AddSp = zc.Op{
		Name: "add/sp",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.AddFloat32,
			},
		},
	}
	AddV = zc.Op{
		Name: "add/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.AddBigFloat,
			},
		},
	}
	CbrtF = zc.Op{
		Name: "cbrt/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.CbrtFloat64,
			},
		},
	}
	DivF = zc.Op{
		Name: "div/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.DivFloat64,
			},
		},
	}
	DivSp = zc.Op{
		Name: "div/sp",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.DivFloat32,
			},
		},
	}
	DivV = zc.Op{
		Name: "div/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.DivBigFloat,
			},
		},
	}
	ExpF = zc.Op{
		Name: "exp/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.ExpFloat64,
			},
		},
	}
	LogF = zc.Op{
		Name: "log/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.LogFloat64,
			},
		},
	}
	Log10F = zc.Op{
		Name: "log10/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.Log10Float64,
			},
		},
	}
	MulF = zc.Op{
		Name: "mul/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.MulFloat64,
			},
		},
	}
	MulSp = zc.Op{
		Name: "mul/sp",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.MulFloat32,
			},
		},
	}
	MulV = zc.Op{
		Name: "mul/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.MulBigFloat,
			},
		},
	}
	NegF = zc.Op{
		Name: "neg/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.NegFloat64,
			},
		},
	}
	NegV = zc.Op{
		Name: "neg/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.NegBigFloat,
			},
		},
	}
	PrecV = zc.Op{
		Name: "prec/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint},
				Returns: []zc.Type{},
				Eval:    funcs.PrecFloat,
			},
		},
	}
	PrecVQ = zc.Op{
		Name: "prec/v?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.Uint},
				Eval:    funcs.PrecFloatGet,
			},
		},
	}
	SignF = zc.Op{
		Name: "sign/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.SignFloat64,
			},
		},
	}
	SqrtF = zc.Op{
		Name: "sqrt/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SqrtFloat64,
			},
		},
	}
	SqrtV = zc.Op{
		Name: "sqrt/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.SqrtBigFloat,
			},
		},
	}
	SubF = zc.Op{
		Name: "sub/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SubFloat64,
			},
		},
	}
	SubSp = zc.Op{
		Name: "sub/sp",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.SubFloat32,
			},
		},
	}
	SubV = zc.Op{
		Name: "sub/v",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.SubBigFloat,
			},
		},
	}
)
