package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddF = zc.Op{
		Name: "add/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AddFloat64,
			},
		},
	}
	AddQ = zc.Op{
		Name: "add/q",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.AddBigFloat,
			},
		},
	}
	AddSf = zc.Op{
		Name: "add/sf",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.AddFloat32,
			},
		},
	}
	CbrtF = zc.Op{
		Name: "cbrt/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.CbrtFloat64,
			},
		},
	}
	DivF = zc.Op{
		Name: "div/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.DivFloat64,
			},
		},
	}
	DivQ = zc.Op{
		Name: "div/q",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.DivBigFloat,
			},
		},
	}
	DivSf = zc.Op{
		Name: "div/sf",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.DivFloat32,
			},
		},
	}
	ExpF = zc.Op{
		Name: "exp/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.ExpFloat64,
			},
		},
	}
	LogF = zc.Op{
		Name: "log/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.LogFloat64,
			},
		},
	}
	Log10F = zc.Op{
		Name: "log10/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.Log10Float64,
			},
		},
	}
	MulF = zc.Op{
		Name: "mul/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.MulFloat64,
			},
		},
	}
	MulQ = zc.Op{
		Name: "mul/q",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.MulBigFloat,
			},
		},
	}
	MulSf = zc.Op{
		Name: "mul/sf",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.MulFloat32,
			},
		},
	}
	NegF = zc.Op{
		Name: "neg/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.NegFloat64,
			},
		},
	}
	NegQ = zc.Op{
		Name: "neg/q",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.NegBigFloat,
			},
		},
	}
	SignF = zc.Op{
		Name: "sign/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.SignFloat64,
			},
		},
	}
	SqrtF = zc.Op{
		Name: "sqrt/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SqrtFloat64,
			},
		},
	}
	SqrtQ = zc.Op{
		Name: "sqrt/q",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.SqrtBigFloat,
			},
		},
	}
	SubF = zc.Op{
		Name: "sub/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SubFloat64,
			},
		},
	}
	SubQ = zc.Op{
		Name: "sub/q",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigFloat, zc.BigFloat},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.SubBigFloat,
			},
		},
	}
	SubSf = zc.Op{
		Name: "sub/sf",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float32, zc.Float32},
				Returns: []zc.Type{zc.Float32},
				Eval:    funcs.SubFloat32,
			},
		},
	}
)
