package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	RoundDecimal = zc.Op{
		Name:      "round/d",
		Overloads: "round",
		Params:    []zc.Type{zc.Decimal, zc.Int32},
		Returns:   []zc.Type{zc.Decimal},
		Func:      funcs.RoundDecimal,
	}
	ScientificNotationDecimal = zc.Op{
		Name:      "scientific.notation/d",
		Overloads: "scientific.notation",
		Params:    []zc.Type{zc.Decimal},
		Returns:   []zc.Type{zc.String},
		Func:      funcs.ScientificNotationDecimal,
	}
)
