package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Round = zc.Op{
		Name: "round",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Int32, zc.Decimal},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.RoundDecimal,
			},
			{
				Params:  []zc.Type{zc.Int32, zc.Complex},
				Returns: []zc.Type{zc.String},
				Eval:    funcs.RoundComplex,
			},
		},
	}
	ScientificNotation = zc.Op{
		Name: "scientific.notation",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Decimal},
				Returns: []zc.Type{zc.Decimal},
				Eval:    funcs.SciDecimal,
			},
		},
	}
)
