package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	EarthRadius = zc.Op{
		Name:  "earth.radius",
		Funcs: []zc.Func{},
	}
	EarthRadiusEquatorial = zc.Op{
		Name:  "earth.radius.equatorial",
		Funcs: []zc.Func{},
	}
	EarthRadiusPolar = zc.Op{
		Name:  "earth.radius.polar",
		Funcs: []zc.Func{},
	}
	Haversine = zc.Op{
		Name: "haversine",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.AngleDMS, zc.AngleDMS, zc.AngleDMS, zc.AngleDMS},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.Haversine,
			},
		},
	}
	Proj = zc.Op{
		Name: "proj",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String, zc.String, zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64, zc.Float64},
				Eval:    funcs.Proj,
			},
		},
	}
)
