package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Apply = zc.Op{
		Name: "apply",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.Uint32, zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Apply,
			},
		},
	}
	Eval = zc.Op{
		Name: "eval",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Eval,
			},
		},
	}
	Filter = zc.Op{
		Name: "filter",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Filter,
			},
		},
	}
	Fold = zc.Op{
		Name: "fold",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Fold,
			},
		},
	}
	Map = zc.Op{
		Name: "map",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Map,
			},
		},
	}
	Repeat = zc.Op{
		Name: "repeat",
		Funcs: []zc.Func{
			{
				Params:   []zc.Type{zc.Uint, zc.String},
				VarParam: zc.Any,
				Returns:  []zc.Type{},
				Eval:     funcs.Repeat,
			},
		},
	}
)
