package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Eval = zc.Op{
		Name: "eval",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Eval,
			},
		},
	}
	Map = zc.Op{
		Name: "map",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				VarParam:  zc.Any,
				Returns:   []zc.Type{},
				VarReturn: zc.Any,
				Eval:      funcs.Map,
			},
		},
	}
)
