package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	IntData = zc.Op{
		Name: "int-data",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.Data},
				Eval:    funcs.IntToData,
			},
		},
	}
)
