package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	FtM = zc.Op{
		Name:  "ft-m",
		Funcs: []zc.Func{},
	}
	FtMi = zc.Op{
		Name:  "ft-mi",
		Funcs: []zc.Func{},
	}
	FtYd = zc.Op{
		Name:  "ft-yd",
		Funcs: []zc.Func{},
	}
	InMm = zc.Op{
		Name:  "in-mm",
		Funcs: []zc.Func{},
	}
	KmM = zc.Op{
		Name:  "km-m",
		Funcs: []zc.Func{},
	}
	KmMi = zc.Op{
		Name:  "km-mi",
		Funcs: []zc.Func{},
	}
	KmNmi = zc.Op{
		Name:  "km-nmi",
		Funcs: []zc.Func{},
	}
	MFt = zc.Op{
		Name:  "m-ft",
		Funcs: []zc.Func{},
	}
	MKm = zc.Op{
		Name:  "m-km",
		Funcs: []zc.Func{},
	}
	MNmi = zc.Op{
		Name:  "m-nmi",
		Funcs: []zc.Func{},
	}
	MYd = zc.Op{
		Name:  "m-yd",
		Funcs: []zc.Func{},
	}
	MiFt = zc.Op{
		Name:  "mi-ft",
		Funcs: []zc.Func{},
	}
	MiKm = zc.Op{
		Name:  "mi-km",
		Funcs: []zc.Func{},
	}
	MiNmi = zc.Op{
		Name:  "mi-nmi",
		Funcs: []zc.Func{},
	}
	MmIn = zc.Op{
		Name:  "mm-in",
		Funcs: []zc.Func{},
	}
	NmiKm = zc.Op{
		Name:  "nmi-km",
		Funcs: []zc.Func{},
	}
	NmiM = zc.Op{
		Name:  "nmi-m",
		Funcs: []zc.Func{},
	}
	YdFt = zc.Op{
		Name:  "yd-ft",
		Funcs: []zc.Func{},
	}
	YdM = zc.Op{
		Name:  "yd-m",
		Funcs: []zc.Func{},
	}
)
