package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	GKg = zc.Op{
		Name:  "g-kg",
		Funcs: []zc.Func{},
	}
	GOz = zc.Op{
		Name:  "g-oz",
		Funcs: []zc.Func{},
	}
	GOzt = zc.Op{
		Name:  "g-ozt",
		Funcs: []zc.Func{},
	}
	KgG = zc.Op{
		Name:  "kg-g",
		Funcs: []zc.Func{},
	}
	KgLb = zc.Op{
		Name:  "kg-lb",
		Funcs: []zc.Func{},
	}
	LbKg = zc.Op{
		Name:  "lb-kg",
		Funcs: []zc.Func{},
	}
	OzG = zc.Op{
		Name:  "oz-g",
		Funcs: []zc.Func{},
	}
	OztG = zc.Op{
		Name:  "ozt-g",
		Funcs: []zc.Func{},
	}
)
