package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddUint8 = zc.Op{
		Name:    "add/u8",
		Params:  []zc.Type{zc.Uint8, zc.Uint8},
		Returns: []zc.Type{zc.Uint8},
		Func:    funcs.AddUint8,
	}
	NegUint8 = zc.Op{
		Name:    "neg/u8",
		Params:  []zc.Type{zc.Uint8},
		Returns: []zc.Type{zc.Uint8},
		Func:    funcs.NegUint8,
	}
	SubUint8 = zc.Op{
		Name:    "sub/u8",
		Params:  []zc.Type{zc.Uint8, zc.Uint8},
		Returns: []zc.Type{zc.Uint8},
		Func:    funcs.SubUint8,
	}
)
