package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AndBigInt = zc.Op{
		Name:      "and/i",
		Overloads: "and",
		Params:    []zc.Type{zc.BigInt, zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.AndBigInt,
	}
	Bin = zc.Op{
		Name:    "bin",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.String},
		Func:    funcs.Bin,
	}
	Bit = zc.Op{
		Name:    "bit",
		Params:  []zc.Type{zc.BigInt, zc.Int},
		Returns: []zc.Type{zc.Uint},
		Func:    funcs.Bit,
	}
	Bits = zc.Op{
		Name:    "bits",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.Int},
		Func:    funcs.Bits,
	}
	Bytes = zc.Op{
		Name:    "bytes",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.Int},
		Func:    funcs.Bytes,
	}
	DecBigInt = zc.Op{
		Name:      "dec/i",
		Overloads: "dec",
		Params:    []zc.Type{zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.DecBigInt,
	}
	Hex = zc.Op{
		Name:    "hex",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.String},
		Func:    funcs.Hex,
	}
	Lsh = zc.Op{
		Name:    "left.shift",
		Params:  []zc.Type{zc.BigInt, zc.Uint},
		Returns: []zc.Type{zc.BigInt},
		Func:    funcs.Lsh,
	}
	NotBigInt = zc.Op{
		Name:      "not/i",
		Overloads: "not",
		Params:    []zc.Type{zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.NotBigInt,
	}
	Oct = zc.Op{
		Name:    "oct",
		Params:  []zc.Type{zc.BigInt},
		Returns: []zc.Type{zc.String},
		Func:    funcs.Oct,
	}
	OrBigInt = zc.Op{
		Name:      "or/i",
		Overloads: "or",
		Params:    []zc.Type{zc.BigInt, zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.OrBigInt,
	}
	Rsh = zc.Op{
		Name:    "right.shift",
		Params:  []zc.Type{zc.BigInt, zc.Uint},
		Returns: []zc.Type{zc.BigInt},
		Func:    funcs.Rsh,
	}
	XorBigInt = zc.Op{
		Name:    "xor",
		Params:  []zc.Type{zc.BigInt, zc.BigInt},
		Returns: []zc.Type{zc.BigInt},
		Func:    funcs.XorBigInt,
	}
)
