package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddInt8 = zc.Op{
		Name:    "add/s8",
		Params:  []zc.Type{zc.Int8, zc.Int8},
		Returns: []zc.Type{zc.Int8},
		Func:    funcs.AddInt8,
	}
)
