package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AndBigInt = zc.Op{
		Name: "and",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.AndBigInt,
			},
		},
	}
	Bin = zc.Op{
		Name: "bin",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Bin,
			},
		},
	}
	Bit = zc.Op{
		Name: "bit",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Int, zc.BigInt},
				Returns: []zc.Type{zc.Uint},
				Eval:    funcs.Bit,
			},
		},
	}
	BitLen = zc.Op{
		Name: "bit.len",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.BitLen,
			},
		},
	}
	ByteLen = zc.Op{
		Name: "byte.len",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.ByteLen,
			},
		},
	}
	DecBigInt = zc.Op{
		Name: "dec",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.DecBigInt,
			},
		},
	}
	Hex = zc.Op{
		Name: "hex",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Hex,
			},
		},
	}
	LeftShift = zc.Op{
		Name: "left.shift",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Lsh,
			},
		},
	}
	NotBigInt = zc.Op{
		Name: "not",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.NotBigInt,
			},
		},
	}
	Oct = zc.Op{
		Name: "oct",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Oct,
			},
		},
	}
	OrBigInt = zc.Op{
		Name: "or",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.OrBigInt,
			},
		},
	}
	RightShift = zc.Op{
		Name: "right.shift",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Rsh,
			},
		},
	}
	Xor = zc.Op{
		Name: "xor",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt, zc.BigInt},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Xor,
			},
		},
	}
)
