package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Rand = zc.Op{
		Name: "rand",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{},
				Eval:    funcs.Rand,
			},
		},
	}
	RandSeed = zc.Op{
		Name: "rand.seed",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.BigInt},
				Returns: []zc.Type{},
				Eval:    funcs.RandSeed,
			},
		},
	}
	RandSeedQ = zc.Op{
		Name: "rand.seed?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.RandSeedGet,
			},
		},
	}
	RandTake = zc.Op{
		Name: "rand.take",
		Funcs: []zc.Func{
			{
				Params:   []zc.Type{},
				VarParam: zc.Any,
				Returns:  []zc.Type{zc.Any},
				Eval:     funcs.RandTake,
			},
		},
	}
	RandI = zc.Op{
		Name: "rand/i",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Int},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.RandInt,
			},
		},
	}
	Roll = zc.Op{
		Name: "roll",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.String},
				Returns:   []zc.Type{},
				VarReturn: zc.Int,
				Eval:      funcs.Roll,
			},
		},
	}
)
