package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Abs          = zc.Op{Name: "abs", Virtual: true}
	Acos         = zc.Op{Name: "acos", Virtual: true}
	Acosh        = zc.Op{Name: "acosh", Virtual: true}
	Asin         = zc.Op{Name: "asin", Virtual: true}
	Asinh        = zc.Op{Name: "asinh", Virtual: true}
	Atan         = zc.Op{Name: "atan", Virtual: true}
	Atan2Float64 = zc.Op{
		Name:    "atan2",
		Params:  []zc.Type{zc.Float64, zc.Float64},
		Returns: []zc.Type{zc.Float64},
		Func:    funcs.Atan2Float64,
	}
	Atanh       = zc.Op{Name: "atanh", Virtual: true}
	CbrtFloat64 = zc.Op{
		Name:    "cbrt",
		Params:  []zc.Type{zc.Float64},
		Returns: []zc.Type{zc.Float64},
		Func:    funcs.CbrtFloat64,
	}
	Cos   = zc.Op{Name: "cos", Virtual: true}
	Cosh  = zc.Op{Name: "cosh", Virtual: true}
	Exp   = zc.Op{Name: "exp", Virtual: true}
	Log   = zc.Op{Name: "log", Virtual: true}
	Log10 = zc.Op{Name: "log10", Virtual: true}
	Sin   = zc.Op{Name: "sin", Virtual: true}
	Sinh  = zc.Op{Name: "sinh", Virtual: true}
	Tan   = zc.Op{Name: "tan", Virtual: true}
	Tanh  = zc.Op{Name: "tanh", Virtual: true}
)
