package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AbsComplex = zc.Op{
		Name:      "abs/c",
		Overloads: "abs",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AbsComplex,
	}
	AcosComplex = zc.Op{
		Name:      "acos/c",
		Overloads: "acos",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.AcosComplex,
	}
	AcoshComplex = zc.Op{
		Name:      "acosh/c",
		Overloads: "acosh",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.AcoshComplex,
	}
	AsinComplex = zc.Op{
		Name:      "asin/c",
		Overloads: "asin",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.AsinComplex,
	}
	AsinhComplex = zc.Op{
		Name:      "asinh/c",
		Overloads: "asinh",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.AsinhComplex,
	}
	AtanComplex = zc.Op{
		Name:      "atan/c",
		Overloads: "atan",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.AtanComplex,
	}
	AtanhComplex = zc.Op{
		Name:      "atanh/c",
		Overloads: "atanh",
		Params:    []zc.Type{zc.Complex},
		Returns:   []zc.Type{zc.Complex},
		Func:      funcs.AtanhComplex,
	}
)
