package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AbsFloat64 = zc.Op{
		Name:      "abs/f64",
		Overloads: "abs",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AbsFloat64,
	}
	AcosFloat64 = zc.Op{
		Name:      "acos/f64",
		Overloads: "acos",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AcosFloat64,
	}
	AcoshFloat64 = zc.Op{
		Name:      "acosh/f64",
		Overloads: "acosh",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AcoshFloat64,
	}
	AsinFloat64 = zc.Op{
		Name:      "asin/f64",
		Overloads: "asin",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AsinFloat64,
	}
	AsinhFloat64 = zc.Op{
		Name:      "asinh/f64",
		Overloads: "asinh",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AsinhFloat64,
	}
	AtanFloat64 = zc.Op{
		Name:      "atan/f64",
		Overloads: "atan",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AtanFloat64,
	}
	AtanhFloat64 = zc.Op{
		Name:      "atanh/f64",
		Overloads: "atanh",
		Params:    []zc.Type{zc.Float64},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AtanhFloat64,
	}
)
