package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AbsBigInt = zc.Op{
		Name:      "abs/i",
		Overloads: "abs",
		Params:    []zc.Type{zc.BigInt},
		Returns:   []zc.Type{zc.BigInt},
		Func:      funcs.AbsBigInt,
	}
)
