package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AbsComplex128 = zc.Op{
		Name:      "abs/c128",
		Overloads: "abs",
		Params:    []zc.Type{zc.Complex128},
		Returns:   []zc.Type{zc.Float64},
		Func:      funcs.AbsComplex128,
	}
)
