package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Acos = zc.Op{
		Name: "acos",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AcosFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.AcosComplex,
			},
		},
	}
	Acosh = zc.Op{
		Name: "acosh",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AcoshFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.AcoshComplex,
			},
		},
	}
	Asin = zc.Op{
		Name: "asin",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AsinFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.AsinComplex,
			},
		},
	}
	Asinh = zc.Op{
		Name: "asinh",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AsinhFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.AsinhComplex,
			},
		},
	}
	Atan = zc.Op{
		Name: "atan",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AtanFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.AtanComplex,
			},
		},
	}
	Atan2 = zc.Op{
		Name: "atan2",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64, zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.Atan2Float64,
			},
		},
	}
	Atanh = zc.Op{
		Name: "atanh",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.AtanhFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.AtanhComplex,
			},
		},
	}
	Cos = zc.Op{
		Name: "cos",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.CosFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.CosComplex,
			},
		},
	}
	Cosh = zc.Op{
		Name: "cosh",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.CoshFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.CoshComplex,
			},
		},
	}
	E = zc.Op{
		Name:  "e",
		Funcs: []zc.Func{},
	}
	Pi = zc.Op{
		Name:  "pi",
		Funcs: []zc.Func{},
	}
	Sin = zc.Op{
		Name: "sin",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SinFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.SinComplex,
			},
		},
	}
	Sinh = zc.Op{
		Name: "sinh",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SinhFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.SinhComplex,
			},
		},
	}
	Tan = zc.Op{
		Name: "tan",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.TanFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.TanComplex,
			},
		},
	}
	Tanh = zc.Op{
		Name: "tanh",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Float64},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.TanhFloat64,
			},
			{
				Params:  []zc.Type{zc.Complex},
				Returns: []zc.Type{zc.Complex},
				Eval:    funcs.TanhComplex,
			},
		},
	}
)
