package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AbsDecimal = zc.Op{
		Name:    "abs/d",
		Params:  []zc.Type{zc.Decimal},
		Returns: []zc.Type{zc.Decimal},
		Func:    funcs.AbsDecimal,
	}
	CbrtDecimal = zc.Op{
		Name:    "cbrt/d",
		Params:  []zc.Type{zc.Decimal},
		Returns: []zc.Type{zc.Decimal},
		Func:    funcs.CbrtDecimal,
	}
)
