package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Fibonacci = zc.Op{
		Name: "fibonacci",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Fibonacci,
			},
		},
	}
	Sequence = zc.Op{
		Name: "sequence",
		Funcs: []zc.Func{
			{
				Params:    []zc.Type{zc.BigInt, zc.BigInt},
				Returns:   []zc.Type{},
				VarReturn: zc.BigInt,
				Eval:      funcs.Sequence,
			},
		},
	}
)
