package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Clear = zc.Op{
		Name: "clear",
		Funcs: []zc.Func{
			{
				Params:   []zc.Type{},
				VarParam: zc.Any,
				Returns:  []zc.Type{},
				Eval:     funcs.Clear,
			},
		},
	}
	Dup = zc.Op{
		Name: "dup",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Any},
				Returns: []zc.Type{zc.Any, zc.Any},
				Eval:    funcs.Dup,
			},
		},
	}
)
