package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Clear = zc.Op{
		Name: "clear",
		Funcs: []zc.Func{
			{
				Params:   []zc.Type{},
				VarParam: zc.Any,
				Returns:  []zc.Type{},
				Eval:     funcs.Clear,
			},
		},
	}
	Drop = zc.Op{
		Name: "drop",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Any},
				Returns: []zc.Type{},
				Eval:    funcs.Drop,
			},
		},
	}
	Dup = zc.Op{
		Name: "dup",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Any},
				Returns: []zc.Type{zc.Any, zc.Any},
				Eval:    funcs.Dup,
			},
		},
	}
	N = zc.Op{
		Name: "n",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.Uint},
				Eval:    funcs.N,
			},
		},
	}
	Swap = zc.Op{
		Name: "swap",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Any, zc.Any},
				Returns: []zc.Type{zc.Any, zc.Any},
				Eval:    funcs.Swap,
			},
		},
	}
	Tuck = zc.Op{
		Name: "tuck",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Any, zc.Any},
				Returns: []zc.Type{zc.BigInt, zc.Any, zc.BigInt},
				Eval:    funcs.Tuck,
			},
		},
	}
)
