package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Average = zc.Op{
		Name:  "average",
		Funcs: []zc.Func{},
	}
	Factorial = zc.Op{
		Name: "factorial",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Fact,
			},
		},
	}
	Prod = zc.Op{
		Name:  "prod",
		Funcs: []zc.Func{},
	}
	StandardDevPop = zc.Op{
		Name:  "standard.dev.pop",
		Funcs: []zc.Func{},
	}
	StandardDevSamp = zc.Op{
		Name:  "standard.dev.samp",
		Funcs: []zc.Func{},
	}
	Sum = zc.Op{
		Name:  "sum",
		Funcs: []zc.Func{},
	}
	VariancePop = zc.Op{
		Name: "variance.pop",
		Funcs: []zc.Func{
			{
				Params:   []zc.Type{},
				VarParam: zc.Real,
				Returns:  []zc.Type{zc.Real},
				Eval:     funcs.VariancePop,
			},
		},
	}
	VarianceSamp = zc.Op{
		Name: "variance.samp",
		Funcs: []zc.Func{
			{
				Params:   []zc.Type{},
				VarParam: zc.Real,
				Returns:  []zc.Type{zc.Real},
				Eval:     funcs.VarianceSamp,
			},
		},
	}
)
