package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Average = zc.Op{
		Name:  "average",
		Funcs: []zc.Func{},
	}
	Factorial = zc.Op{
		Name: "factorial",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Fact,
			},
		},
	}
	Prod = zc.Op{
		Name:  "prod",
		Funcs: []zc.Func{},
	}
	Sum = zc.Op{
		Name:  "sum",
		Funcs: []zc.Func{},
	}
)
