package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Factorial = zc.Op{
		Name: "factorial",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint},
				Returns: []zc.Type{zc.BigInt},
				Eval:    funcs.Fact,
			},
		},
	}
	FactorialF = zc.Op{
		Name: "factorial/f",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Uint},
				Returns: []zc.Type{zc.BigFloat},
				Eval:    funcs.FactBigFloat,
			},
		},
	}
)
