package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	CF = zc.Op{
		Name:  "c-f",
		Funcs: []zc.Func{},
	}
	CK = zc.Op{
		Name:  "c-k",
		Funcs: []zc.Func{},
	}
	FC = zc.Op{
		Name:  "f-c",
		Funcs: []zc.Func{},
	}
	KC = zc.Op{
		Name:  "k-c",
		Funcs: []zc.Func{},
	}
)
