package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Len = zc.Op{
		Name: "len",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.Len,
			},
		},
	}
)
