package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddTime = zc.Op{
		Name: "add",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Duration, zc.Duration},
				Returns: []zc.Type{zc.Duration},
				Eval:    funcs.AddDuration,
			},
			{
				Params:  []zc.Type{zc.DateTime, zc.Duration},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.AddDurationDateTime,
			},
			{
				Params:  []zc.Type{zc.Duration, zc.DateTime},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.AddDateTimeDuration,
			},
		},
	}
	Date = zc.Op{
		Name: "date",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{zc.Date},
				Eval:    funcs.Date,
			},
		},
	}
	DateTime = zc.Op{
		Name: "date.time",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.DateTime,
			},
		},
	}
	DateTimeQ = zc.Op{
		Name: "date.time?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.DateTimeIs,
			},
		},
	}
	DateQ = zc.Op{
		Name: "date?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.DateIs,
			},
		},
	}
	DayYear = zc.Op{
		Name: "day.year",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{zc.Int},
				Eval:    funcs.DayYear,
			},
		},
	}
	Hours = zc.Op{
		Name: "hours",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Duration},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.Hours,
			},
		},
	}
	LocalZone = zc.Op{
		Name: "local.zone",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{},
				Eval:    funcs.LocalZoneSet,
			},
		},
	}
	LocalZoneQ = zc.Op{
		Name: "local.zone?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.String},
				Eval:    funcs.LocalZone,
			},
		},
	}
	MinutesTime = zc.Op{
		Name: "minutes",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Duration},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.MinutesTime,
			},
		},
	}
	Now = zc.Op{
		Name: "now",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.Now,
			},
		},
	}
	NowReset = zc.Op{
		Name: "now.reset",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{},
				Eval:    funcs.NowReset,
			},
		},
	}
	NowE = zc.Op{
		Name: "now=",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{},
				Eval:    funcs.NowSet,
			},
		},
	}
	SecondsTime = zc.Op{
		Name: "seconds",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Duration},
				Returns: []zc.Type{zc.Float64},
				Eval:    funcs.SecondsTime,
			},
		},
	}
	SubTime = zc.Op{
		Name: "sub",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Duration, zc.Duration},
				Returns: []zc.Type{zc.Duration},
				Eval:    funcs.SubDuration,
			},
			{
				Params:  []zc.Type{zc.Duration, zc.DateTime},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.SubDateTimeDuration,
			},
			{
				Params:  []zc.Type{zc.DateTime, zc.DateTime},
				Returns: []zc.Type{zc.Duration},
				Eval:    funcs.SubDateTime,
			},
		},
	}
	Time = zc.Op{
		Name: "time",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{zc.Time},
				Eval:    funcs.Time,
			},
		},
	}
	TimeZone = zc.Op{
		Name: "time.zone",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String, zc.DateTime},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.TimeZone,
			},
		},
	}
	TimeQ = zc.Op{
		Name: "time?",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{zc.Bool},
				Eval:    funcs.TimeIs,
			},
		},
	}
)
