package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddTime = zc.Op{
		Name: "add",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.Duration, zc.Duration},
				Returns: []zc.Type{zc.Duration},
				Eval:    funcs.AddDuration,
			},
			{
				Params:  []zc.Type{zc.DateTime, zc.Duration},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.AddDurationDateTime,
			},
			{
				Params:  []zc.Type{zc.Duration, zc.DateTime},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.AddDateTimeDuration,
			},
		},
	}
	LocalZoneSet = zc.Op{
		Name: "local.zone=",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.String},
				Returns: []zc.Type{},
				Eval:    funcs.LocalZoneSet,
			},
		},
	}
	Now = zc.Op{
		Name: "now",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{},
				Returns: []zc.Type{zc.DateTime},
				Eval:    funcs.Now,
			},
		},
	}
	NowSet = zc.Op{
		Name: "now=",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{},
				Eval:    funcs.NowSet,
			},
		},
	}
	Time = zc.Op{
		Name: "time",
		Funcs: []zc.Func{
			{
				Params:  []zc.Type{zc.DateTime},
				Returns: []zc.Type{zc.Time},
				Eval:    funcs.Time,
			},
		},
	}
)
