package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	MaxUint = zc.Op{
		Name:    "max.u",
		Params:  []zc.Type{},
		Returns: []zc.Type{zc.Uint},
		Func:    funcs.MaxUint,
	}
)
