package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/funcs"
	"github.com/blackchip-org/zc/v6/calc/types"
)

var (
	AddDecimal = zc.Op{
		Name:      "add/d",
		Overloads: "add",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.AddDecimal,
	}
	DivDecimal = zc.Op{
		Name:      "div/d",
		Overloads: "div",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.DivDecimal,
	}
	MulDecimal = zc.Op{
		Name:      "mul/d",
		Overloads: "mul",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.MulDecimal,
	}
	NegDecimal = zc.Op{
		Name:      "neg/d",
		Overloads: "neg",
		Params:    []zc.Type{types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.NegDecimal,
	}
	PowDecimal = zc.Op{
		Name:    "pow/d",
		Params:  []zc.Type{types.Dec, types.Dec},
		Returns: []zc.Type{types.Dec},
		Func:    funcs.PowDecimal,
	}
	SubDecimal = zc.Op{
		Name:      "sub/d",
		Overloads: "sub",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.SubDecimal,
	}
)
