package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/calc/funcs"
	"github.com/blackchip-org/zc/v6/calc/types"
)

var (
	AddBigInt = zc.Op{
		Name:      "add/i",
		Overloads: "add",
		Params:    []zc.Type{types.Int, types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.AddBigInt,
	}
	DivBigInt = zc.Op{
		Name:    "div/i",
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.DivBigInt,
	}
	ModBigInt = zc.Op{
		Name:      "mod/i",
		Overloads: "mod",
		Params:    []zc.Type{types.Int, types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.ModBigInt,
	}
	MulBigInt = zc.Op{
		Name:      "mul/i",
		Overloads: "mul",
		Params:    []zc.Type{types.Int, types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.MulBigInt,
	}
	NegBigInt = zc.Op{
		Name:      "neg/i",
		Overloads: "neg",
		Params:    []zc.Type{types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.NegBigInt,
	}
	PowBigInt = zc.Op{
		Name:      "pow/i",
		Overloads: "pow",
		Params:    []zc.Type{types.Int, types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.PowBigInt,
	}
	RemBigInt = zc.Op{
		Name:      "rem/i",
		Overloads: "rem",
		Params:    []zc.Type{types.Int, types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.RemBigInt,
	}
	SignBigInt = zc.Op{
		Name:      "sign/i",
		Overloads: "sign",
		Params:    []zc.Type{types.Int},
		Returns:   []zc.Type{types.IntA},
		Func:      funcs.SignBigInt,
	}
	SqrtBigInt = zc.Op{
		Name:      "sqrt/i",
		Overloads: "sqrt",
		Params:    []zc.Type{types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.SqrtBigInt,
	}
	SubBigInt = zc.Op{
		Name:      "sub/i",
		Overloads: "sub",
		Params:    []zc.Type{types.Int, types.Int},
		Returns:   []zc.Type{types.Int},
		Func:      funcs.SubBigInt,
	}
)
