package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
)

var (
	Round              = zc.Op{Name: "round", Virtual: true}
	ScientificNotation = zc.Op{Name: "scientific.notation", Virtual: true}
)
