package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddUint32 = zc.Op{
		Name:    "add/u32",
		Params:  []zc.Type{zc.Uint32, zc.Uint32},
		Returns: []zc.Type{zc.Uint32},
		Func:    funcs.AddUint32,
	}
)
