package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddRat = zc.Op{
		Name:      "add/r",
		Overloads: "add",
		Params:    []zc.Type{zc.Rat, zc.Rat},
		Returns:   []zc.Type{zc.Rat},
		Func:      funcs.AddRat,
	}
	DivRat = zc.Op{
		Name:      "div/r",
		Overloads: "div",
		Params:    []zc.Type{zc.Rat, zc.Rat},
		Returns:   []zc.Type{zc.Rat},
		Func:      funcs.DivRat,
	}
	MulRat = zc.Op{
		Name:      "mul/r",
		Overloads: "mul",
		Params:    []zc.Type{zc.Rat, zc.Rat},
		Returns:   []zc.Type{zc.Rat},
		Func:      funcs.MulRat,
	}
	NegRat = zc.Op{
		Name:      "neg/r",
		Overloads: "neg",
		Params:    []zc.Type{zc.Rat},
		Returns:   []zc.Type{zc.Rat},
		Func:      funcs.NegRat,
	}
	SubRat = zc.Op{
		Name:      "sub/r",
		Overloads: "sub",
		Params:    []zc.Type{zc.Rat, zc.Rat},
		Returns:   []zc.Type{zc.Rat},
		Func:      funcs.SubRat,
	}
)
