package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddUint = zc.Op{
		Name:    "add/u",
		Params:  []zc.Type{zc.Uint, zc.Uint},
		Returns: []zc.Type{zc.Uint},
		Func:    funcs.AddUint,
	}
)
