package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	AddUint16 = zc.Op{
		Name:    "add/u16",
		Params:  []zc.Type{zc.Uint16, zc.Uint16},
		Returns: []zc.Type{zc.Uint16},
		Func:    funcs.AddUint16,
	}
)
