package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	RoundingModeSet = zc.Op{
		Name:    "rounding.mode=",
		Params:  []zc.Type{zc.String},
		Returns: []zc.Type{},
		Func:    funcs.RoundingModeSet,
	}
	RoundingModeGet = zc.Op{
		Name:    "rounding.mode?",
		Params:  []zc.Type{},
		Returns: []zc.Type{zc.String},
		Func:    funcs.RoundingModeGet,
	}
)
