package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	CbrtFloat64 = zc.Op{
		Name:    "cbrt/f",
		Params:  []zc.Type{zc.Float64},
		Returns: []zc.Type{zc.Float64},
		Func:    funcs.CbrtFloat64,
	}
	ExpFloat64 = zc.Op{
		Name:    "exp/f",
		Params:  []zc.Type{zc.Float64},
		Returns: []zc.Type{zc.Float64},
		Func:    funcs.ExpFloat64,
	}
	Log10Float64 = zc.Op{
		Name:    "log10/f",
		Params:  []zc.Type{zc.Float64},
		Returns: []zc.Type{zc.Float64},
		Func:    funcs.Log10Float64,
	}
)
