package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/app/funcs"
)

var (
	Types = zc.Op{
		Name:      "types",
		Params:    []zc.Type{},
		VarParam:  zc.Any,
		Returns:   []zc.Type{},
		VarReturn: zc.Any,
		Func:      funcs.Types,
	}
)
