package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	AddDecSS = zc.Op{
		Name:      "add/d/ss",
		Overloads: "add",
		Params:    []zc.Type{types.DecSS, types.DecSS},
		Returns:   []zc.Type{types.DecSS},
		Func:      funcs.AddDecSS,
	}
	DivDecSS = zc.Op{
		Name:      "div/d/ss",
		Overloads: "div",
		Params:    []zc.Type{types.DecSS, types.DecSS},
		Returns:   []zc.Type{types.DecSS},
		Func:      funcs.DivDecSS,
	}
	MulDecSS = zc.Op{
		Name:      "mul/d/ss",
		Overloads: "mul",
		Params:    []zc.Type{types.DecSS, types.DecSS},
		Returns:   []zc.Type{types.DecSS},
		Func:      funcs.MulDecSS,
	}
	NegDecSS = zc.Op{
		Name:      "neg/d/ss",
		Overloads: "neg",
		Params:    []zc.Type{types.DecSS},
		Returns:   []zc.Type{types.DecSS},
		Func:      funcs.NegDecSS,
	}
	SubDecSS = zc.Op{
		Name:      "sub/d/ss",
		Overloads: "sub",
		Params:    []zc.Type{types.DecSS, types.DecSS},
		Returns:   []zc.Type{types.DecSS},
		Func:      funcs.SubDecSS,
	}
)
