package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	AddBigInt = zc.Op{
		Name: "add/i",
		Aliases: []string{
			"add",
		},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.AddBigInt,
	}
	DivBigInt = zc.Op{
		Name:    "div/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.DivBigInt,
	}
	ModBigInt = zc.Op{
		Name:    "mod/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.ModBigInt,
	}
	MulBigInt = zc.Op{
		Name:    "mul/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.MulBigInt,
	}
	NegBigInt = zc.Op{
		Name:    "neg/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.NegBigInt,
	}
	PowBigInt = zc.Op{
		Name:    "pow/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.PowBigInt,
	}
	RemBigInt = zc.Op{
		Name:    "rem/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.RemBigInt,
	}
	SignBigInt = zc.Op{
		Name:    "sign/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int},
		Returns: []zc.Type{types.IntArch},
		Func:    funcs.SignBigInt,
	}
	SqrtBigInt = zc.Op{
		Name:    "sqrt/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.SqrtBigInt,
	}
	SubBigInt = zc.Op{
		Name:    "sub/i",
		Aliases: []string{},
		Params:  []zc.Type{types.Int, types.Int},
		Returns: []zc.Type{types.Int},
		Func:    funcs.SubBigInt,
	}
)
