package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	AddDec = zc.Op{
		Name:      "add/d",
		Overloads: "add",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.AddDec,
	}
	DivDec = zc.Op{
		Name:      "div/d",
		Overloads: "div",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.DivDec,
	}
	MulDec = zc.Op{
		Name:      "mul/d",
		Overloads: "mul",
		Params:    []zc.Type{types.Dec, types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.MulDec,
	}
	NegDec = zc.Op{
		Name:      "neg/d",
		Overloads: "neg",
		Params:    []zc.Type{types.Dec},
		Returns:   []zc.Type{types.Dec},
		Func:      funcs.NegDec,
	}
)
