package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	AddDecSS = zc.Op{
		Name:    "add/d/ss",
		Params:  []zc.Type{types.DecSS, types.DecSS},
		Returns: []zc.Type{types.DecSS},
		Func:    funcs.AddDecSS,
	}
	DivDecSS = zc.Op{
		Name:    "div/d/ss",
		Params:  []zc.Type{types.DecSS, types.DecSS},
		Returns: []zc.Type{types.DecSS},
		Func:    funcs.DivDecSS,
	}
	MulDecSS = zc.Op{
		Name:    "mul/d/ss",
		Params:  []zc.Type{types.DecSS, types.DecSS},
		Returns: []zc.Type{types.DecSS},
		Func:    funcs.MulDecSS,
	}
	NegDecSS = zc.Op{
		Name:    "neg/d/ss",
		Params:  []zc.Type{types.DecSS},
		Returns: []zc.Type{types.DecSS},
		Func:    funcs.NegDecSS,
	}
	SubDecSS = zc.Op{
		Name:    "sub/d/ss",
		Params:  []zc.Type{types.DecSS, types.DecSS},
		Returns: []zc.Type{types.DecSS},
		Func:    funcs.SubDecSS,
	}
)
