package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	AddBigFloat = zc.Op{
		Name:    "add/f",
		Aliases: []string{},
		Params:  []zc.Type{types.Float, types.Float},
		Returns: []zc.Type{types.Float},
		Func:    funcs.AddBigFloat,
	}
)
