package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	AddBigFloat = zc.Op{
		Name:      "add/f",
		Overloads: "add",
		Params:    []zc.Type{types.Float, types.Float},
		Returns:   []zc.Type{types.Float},
		Func:      funcs.AddBigFloat,
	}
	DivBigFloat = zc.Op{
		Name:      "div/f",
		Overloads: "div",
		Params:    []zc.Type{types.Float, types.Float},
		Returns:   []zc.Type{types.Float},
		Func:      funcs.DivBigFloat,
	}
)
