package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	FloatPrecSet = zc.Op{
		Name:    "float.prec=",
		Params:  []zc.Type{types.IntU},
		Returns: []zc.Type{},
		Func:    funcs.FloatPrecSet,
	}
	FloatPrecGet = zc.Op{
		Name:    "float.prec?",
		Params:  []zc.Type{},
		Returns: []zc.Type{types.IntU},
		Func:    funcs.FloatPrecGet,
	}
)
