package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

var (
	Add        = "add"
	AddFloat   = "add.float"
	AddFloat64 = "add.float64"
	AddI16     = "add.int16"
	AddI32     = "add.int32"
	AddI64     = "add.int64"
	AddI8      = "add.int8"
	AddInt     = "add.int"
	AddIntArch = "add.intarch"
	Clear      = "clear"
	Down       = "down"
	Dup        = "dup"
	Int8       = "int8"
	Int8Max    = "int8.max"
	IsInt8     = "int8?"
	PowInt     = "pow.int"
	Sub        = "sub"
	SubInt     = "sub.int"
)
