package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

var (
	Add        = "add"
	AddFloat   = "add.float"
	AddFloat64 = "add.float64"
	AddInt     = "add.int"
	AddIntArch = "add.intarch"
	Clear      = "clear"
	Down       = "down"
	Dup        = "dup"
	Int8       = "int8"
	Sub        = "sub"
	SubInt     = "sub.int"
)
