package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	Clear = zc.Op{
		Name:     "clear",
		Params:   []zc.Type{},
		VarParam: types.Val,
		Returns:  []zc.Type{},
		Func:     funcs.Clear,
	}
	Down = zc.Op{
		Name:      "down",
		Params:    []zc.Type{},
		VarParam:  types.Val,
		Returns:   []zc.Type{},
		VarReturn: types.Val,
		Func:      funcs.Down,
	}
	Dup = zc.Op{
		Name:    "dup",
		Params:  []zc.Type{types.Val},
		Returns: []zc.Type{types.Val, types.Val},
		Func:    funcs.Dup,
	}
)
