package ops

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/funcs"
	"github.com/blackchip-org/zc/v6/types"
)

var (
	Factorial = zc.Op{
		Name:    "fact",
		Params:  []zc.Type{types.IntU},
		Returns: []zc.Type{types.Int},
		Func:    funcs.Factorial,
	}
)
