//go:generate go run gen-doc-tests.go

package main

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"path"
	"regexp"
	"strings"
)

var (
	evalDirective = regexp.MustCompile(`<!-- eval: (.*) -->`)
	testBanner    = regexp.MustCompile(`<!-- test: (.*) *-->`)
	tableHeader   = regexp.MustCompile(`.*Input.*Stack`)

	RootDir = path.Join("..", "..")
	TestDir = path.Join(RootDir, "app", "test", "docs")
)

func main() {
	files := []string{
		"README.md",
	}
	dirs := []string{}

	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			log.Fatal(err)
		}
		for _, entry := range entries {
			files = append(files, path.Join(dir, entry.Name()))
		}
	}

	for _, name := range files {
		genTestsForFile(name)
	}
}

func genTestsForFile(name string) {
	testName := ""
	var setup []string

	in, err := os.Open(path.Join(RootDir, name))
	if err != nil {
		log.Fatal(err)
	}
	defer in.Close()

	outName := strings.ReplaceAll(name, ".", "_") + "_test.go"
	out, err := os.Create(path.Join(TestDir, outName))
	if err != nil {
		log.Fatal(err)
	}
	defer out.Close()

	fmt.Fprintf(out, "package docs\n\n")
	fmt.Fprintf(out, "// Code generated by 'gen-doc-tests; DO NOT EDIT.\n\n")
	fmt.Fprintf(out, "import (\n")
	fmt.Fprintf(out, "\"testing\"\n")
	fmt.Fprintf(out, "\"github.com/blackchip-org/zc/v6/app/repl\"\n")
	fmt.Fprintf(out, ")\n")

	s := bufio.NewScanner(in)
	for s.Scan() {
		if s.Err() != nil {
			log.Fatal(s.Err())
		}
		line := s.Text()

		matches := evalDirective.FindStringSubmatch(line)
		if matches != nil {
			setup = append(setup, matches[1])
			continue
		}

		matches = testBanner.FindStringSubmatch(line)
		if matches == nil {
			continue
		}
		testName = strings.TrimSpace(matches[1])

		fmt.Fprintf(out, "func Test%v(t *testing.T) {\n", testName)
		for s.Scan() {
			line = s.Text()
			if strings.TrimSpace(line) != "" || s.Err() != nil {
				break
			}
		}
		line = s.Text()
		if !tableHeader.MatchString(line) {
			log.Fatalf("expected table header but got: %v", line)
		}
		s.Scan()
		s.Scan()
		genTestForFile(s, out, setup)
		fmt.Fprintf(out, "}\n\n")
	}
}

func genTestForFile(s *bufio.Scanner, f *os.File, setup []string) {
	fmt.Fprintf(f, "c := repl.NewReplTester(t)\n\n")

	for _, l := range setup {
		fmt.Fprintf(f, "c.Eval(\"%v\")\n", l)
	}

	for {
		line := s.Text()
		fields := strings.SplitN(line, "|", 3)
		if len(fields) != 3 {
			break
		}

		in := strings.ReplaceAll(fields[1], "`", "")
		in = strings.TrimSpace(in)

		out := ""
		notice := ""

		f2 := strings.TrimSpace(fields[2])
		if strings.HasPrefix(f2, "*") {
			notice = f2
		} else {
			out = strings.ReplaceAll(f2, "`", "")
			out = strings.ReplaceAll(out, "\\|", "|")
			out = strings.TrimSpace(out)
		}

		fmt.Fprintf(f, "\nc.Eval(\"%v\")\n", in)
		if notice != "" {
			notice = strings.TrimLeft(notice, "* ")
			notice = strings.TrimRight(notice, "* ")
			fmt.Fprintf(f, "c.AssertNotice(\"%v\")\n", notice)
		} else {
			items := strings.Split(out, "|")
			for i, item := range items {
				items[i] = "\"" + strings.TrimSpace(item) + "\""
			}
			fmt.Fprintf(f, "c.AssertStack(%v)\n", strings.Join(items, ", "))
		}
		s.Scan()
		if s.Err() != nil {
			log.Fatal(s.Err())
		}
	}
}
