package doc

var GroupTitles = map[string]string{
	"angle":  "Angular calculations",
	"anno":   "Annotations",
	"basic":  "Basic calculator",
	"bool":   "Boolean operations",
	"color":  "Color conversions",
	"conv":   "Type conversions",
	"cmp":    "Comparisons",
	"crypto": "Cryptographic ciphers",
	"epsg":   "EPSG Geodetic Parameter Dataset",
	"format": "Value formatting",
	"geo":    "Geo-spatial calculations",
	"hof":    "Higher-order functions",
	"len":    "Length",
	"prog":   "Programmer's calculator",
	"rand":   "Random number generation",
	"sci":    "Scientific calculator",
	"si":     "International System of Units",
	"stack":  "Stack manipulations",
	"stat":   "Statistical calculations",
	"temp":   "Temperature",
	"text":   "Text operations",
	"time":   "Date, time, and duration operations",
	"tz":     "Time zone database",
	"zc":     "About this calculator",
}
