package doc

var GroupTitles = map[string]string{
	"angle":    "Angular calculations",
	"anno":     "Annotations",
	"basic":    "Basic calculator",
	"bin":      "Binary data",
	"bool":     "Boolean operations",
	"color":    "Color conversions",
	"complex":  "Complex numbers",
	"cmp":      "Comparisons",
	"crypto":   "Cryptographic ciphers",
	"decimal":  "Decimal numbers",
	"entity":   "HTML entity characters",
	"emoji":    "Unicode emoji characters",
	"epsg":     "EPSG Geodetic Parameter Dataset",
	"format":   "Value formatting",
	"geo":      "Geo-spatial calculations",
	"hof":      "Higher-order functions",
	"iec":      "IEC binary prefixes",
	"len":      "Length conversions",
	"mass":     "Mass conversions",
	"prog":     "Programmer's calculator",
	"rand":     "Random number generation",
	"rational": "Rational numbers (fractions)",
	"sci":      "Scientific calculator",
	"seq":      "Integer sequences",
	"si":       "International System of Units",
	"stack":    "Stack manipulations",
	"stat":     "Statistical calculations",
	"temp":     "Temperature conversions",
	"text":     "Text operations",
	"time":     "Date, time, and duration operations",
	"tz":       "Time zone database",
	"zc":       "About this calculator",
}
