# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Dependencies
      run: sudo apt install libproj-dev
      
    - name: Build
      run: go build -tags proj ./...

    - name: Test
      run: go test -tags proj ./...
 
    - name: WASM
      run: GOOS=js GOARCH=wasm go build -o web/zc.wasm cmd/wasm/main.go
      
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'web'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
