package ints

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	AddIntArch = zc.Op{
		Name: "add.intarch",
		Aliases: []string{
			"addia",
		},
		Params:  []string{kinds.IntArch, kinds.IntArch},
		Returns: []string{kinds.IntArch},
		Func:    addIntArch,
	}
	Int8 = zc.Op{
		Name:    "int8",
		Aliases: []string{},
		Params:  []string{kinds.Int64},
		Returns: []string{kinds.Int8},
		Func:    int8_,
	}
)
