package ints

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/kinds"
)

var (
	AddIntarch = zc.Op{
		Name:    "add.intarch",
		Aliases: []string{},
		Params:  []string{kinds.IntArch, kinds.IntArch},
		Returns: []string{kinds.IntArch},
		Func:    add,
	}
)
