// Code generated by 'gen-ops'; DO NOT EDIT
package ints

import (
	"github.com/blackchip-org/zc/v6"
)

var Volume = zc.Vol{
	Name: "ints",
	Kinds: []zc.Kind{
		IntArchKind,
	},
	Ops: []zc.Op{
		AddIntarch,
	},
}
