package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/types"
)

var Basic = zc.Vol{
	Name: "basic",
	Types: []zc.Type{
		types.Int,
		types.Str,
	},
}
