package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/ops"
	"github.com/blackchip-org/zc/v6/types"
)

var BasicDecSS = zc.Vol{
	Name: "basic/Dec/SS",
	Types: []zc.Type{
		types.DecSS,
	},
	Ops: []zc.Op{
		ops.AddDecimalSS,
		ops.DivDecimalSS,
		ops.MulDecimalSS,
		ops.NegDecimalSS,
		ops.SubDecimalSS,
	},
	Macros: []zc.Macro{},
}
