package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/ops"
)

var BasicDec = zc.Vol{
	Name: "basic/Dec",
	Ops: []zc.Op{
		ops.AddDec,
		ops.DivDec,
		ops.MulDec,
		ops.NegDec,
		ops.SubDec,
	},
	Macros: []zc.Macro{},
}
