package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/ops"
	"github.com/blackchip-org/zc/v6/types"
)

var Basic = zc.Vol{
	Name: "basic",
	Types: []zc.Type{
		types.Int,
		types.Dec,
		types.Float,
		types.Str,
	},
	Ops: []zc.Op{
		ops.Add,
		ops.Mul,
	},
	Macros: []zc.Macro{
		{Name: "a", Expr: "add"},
		{Name: "+", Expr: "add"},
	},
}
