package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/ops"
)

var Stat = zc.Vol{
	Name: "stat",
	Ops: []zc.Op{
		ops.Factorial,
	},
	Macros: []zc.Macro{},
}
