package vols

// Code generated by 'gen-ops'; DO NOT EDIT.

import (
	"github.com/blackchip-org/zc/v6"
	"github.com/blackchip-org/zc/v6/ops"
)

var Zcalc = zc.Vol{
	Name: "zcalc",
	Ops: []zc.Op{
		ops.Clear,
		ops.Down,
		ops.Dup,
	},
}
